[topbanana-dev]
image=fedora-toolbox:43
additional_packages="git golang"
additional_packages="libXrender libXtst libXi libXext libXcomposite libXcursor libXdamage libXfixes libXrandr mesa-libGL mesa-libEGL freetype fontconfig dejavu-fonts-all libwayland-client libwayland-cursor libwayland-egl adwaita-cursor-theme gsettings-desktop-schemas nss at-spi2-atk atk cairo pango cups-libs alsa-lib libxkbcommon"
replace=true
#init=false
#nvidia=false
#pull=true
#root=false
#start_now=false
init_hooks="curl -sSfL https://golangci-lint.run/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.10.1"
init_hooks="go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest"
