## Version 2026/07/05
# make sure that your topbanana container is named topbanana
# make sure that your dns has a cname set for topbanana
# on the topbanana container, set BASE_URL to your https url, and set
# TRUSTED_PROXY_IPS to this proxy's docker network subnet (see the README)

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name topbanana.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app topbanana;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
