-- name: CreateSession :one
-- Inserts a hosted room. id is an xid generated by the store; join_code is the
-- collision-checked short code minted by the domain layer. quiz_id is nullable
-- (#836): a room can be opened with no current quiz (the "no game running yet"
-- staging state where the host picks the first quiz ad-hoc) or with a
-- preselected first quiz (the "Host live" entry from a quiz). phase defaults to 'lobby'
-- at the DB level. A duplicate join_code trips the UNIQUE constraint, which the
-- store surfaces so the caller can regenerate.
INSERT INTO sessions (id, quiz_id, host_player_id, join_code)
VALUES (sqlc.arg('id'), sqlc.narg('quiz_id'), sqlc.arg('host_player_id'), sqlc.arg('join_code'))
RETURNING *;

-- name: GetSession :one
SELECT *
FROM sessions
WHERE id = ?;

-- name: GetSessionByJoinCode :one
-- Resolves a typed/scanned room code to its session. join_code is UNIQUE so
-- this returns at most one row.
SELECT *
FROM sessions
WHERE join_code = ?;

-- name: GetActiveSessionForHost :one
-- The host's current active (non-finished) room (#836), most recent first, so
-- the UI can offer a "Resume hosting" link back into it. A host opens a room up
-- front and may browse away; this finds the one still alive (any phase except
-- the terminal finished) to return to. Ordered by created_at desc so the newest
-- room wins if a host somehow has more than one open. Returns no row (the store
-- maps it to nil) when the host has no active room.
SELECT *
FROM sessions
WHERE host_player_id = ?
  AND phase != 'finished'
ORDER BY created_at DESC, id DESC
LIMIT 1;

-- name: JoinCodeExists :one
-- Cheap existence probe for a candidate join code so the generator can
-- regenerate on collision before paying for the INSERT.
SELECT EXISTS(SELECT 1 FROM sessions WHERE join_code = ?) AS code_exists;

-- name: ListFinishedSessionPlaysForPlayer :many
-- Finished live-quiz plays for the given player, newest-first, one row per
-- quiz. A play is a roster row in a finished session; collapsing to one row
-- per quiz keeps the admin detail list to "quizzes this player has played"
-- rather than every individual session. finished_at is the most recent
-- finish time among the player's sessions of that quiz, read off the
-- representative session row (not aggregated) so it stays a typed DATETIME.
-- Joined to quizzes for the title so the detail view renders without a
-- second round trip.
--
-- Rooms (#836): a session is only 'finished' once the room is terminally closed
-- (the runner ends each game in intermission and reaches finished only on an
-- explicit End or idle auto-close); s.quiz_id holds the room's LAST quiz then.
-- This read is deliberately NOT game_seq-scoped (it reads no answers, only the
-- roster + finish time) and so reports the room's final quiz, not every quiz it
-- cycled through. Per-game history is out of scope for this admin list.
SELECT
    CAST(s.quiz_id AS INTEGER) AS quiz_id,
    CAST(q.title AS TEXT)      AS quiz_title,
    s.finished_at              AS finished_at
FROM sessions s
JOIN quizzes q ON q.id = s.quiz_id
WHERE s.phase = 'finished'
  AND s.finished_at = (
      SELECT MAX(s2.finished_at)
      FROM sessions s2
      JOIN session_players sp2 ON sp2.session_id = s2.id
      WHERE s2.quiz_id = s.quiz_id
        AND s2.phase = 'finished'
        AND sp2.player_id = sqlc.arg('player_id')
  )
  AND EXISTS (
      SELECT 1 FROM session_players sp
      WHERE sp.session_id = s.id
        AND sp.player_id = sqlc.arg('player_id')
  )
GROUP BY s.quiz_id
ORDER BY s.finished_at DESC, s.quiz_id DESC
LIMIT sqlc.arg('row_limit');

-- name: UpsertSessionPlayer :one
-- Adds a player to a session's roster, or revives an existing row on re-join
-- (clearing left_at and refreshing last_seen_at). The display name is no
-- longer stored per session (#716): the roster reads join players and select
-- the current players.display_name, so a rename propagates everywhere. The
-- (session_id, player_id) UNIQUE makes the upsert idempotent for the same
-- player.
INSERT INTO session_players (session_id, player_id)
VALUES (?, ?)
ON CONFLICT (session_id, player_id)
    DO UPDATE SET left_at      = NULL,
                  last_seen_at = CURRENT_TIMESTAMP
RETURNING *;

-- name: GetSessionPlayer :one
SELECT *
FROM session_players
WHERE session_id = ?
  AND player_id = ?;

-- name: SetSessionPlayerReady :execresult
-- Toggles a participant's ready flag and refreshes last_seen_at. Scoped to
-- (session_id, player_id) so it only ever touches the caller's own roster
-- row. The execresult lets the store map zero rows affected to "not a
-- participant".
UPDATE session_players
SET is_ready     = ?,
    last_seen_at = CURRENT_TIMESTAMP
WHERE session_id = ?
  AND player_id = ?;

-- name: ListSessionPlayers :many
-- The lobby roster in join order. Excludes players who have left (left_at
-- set, MP-10) so the lobby shows the current room. display_name is the
-- player's CURRENT players.display_name (#716), joined live so a rename shows
-- everywhere rather than a per-session snapshot.
SELECT sp.id,
       sp.session_id,
       sp.player_id,
       CAST(p.display_name AS TEXT) AS display_name,
       sp.is_ready,
       sp.joined_at,
       sp.last_seen_at,
       sp.left_at
FROM session_players sp
         JOIN players p ON p.id = sp.player_id
WHERE sp.session_id = ?
  AND sp.left_at IS NULL
ORDER BY sp.joined_at, sp.id;

-- name: ListLiveSessionIDs :many
-- Ids of every session not yet finished, in creation order. The runner scans
-- these each beat to auto-start lobbies and advance in-flight games; finished
-- sessions are skipped so the scan stays bounded to active rooms.
SELECT id
FROM sessions
WHERE phase != 'finished'
ORDER BY created_at, id;

-- name: StartSession :execresult
-- Stamps started_at and moves the session out of the lobby. Scoped to a
-- session still in the lobby so a re-issued start (host double-click, or the
-- auto-start racing the host) is a no-op rather than resetting the clock.
UPDATE sessions
SET started_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND started_at IS NULL;

-- name: ArmSessionStart :execresult
-- Arms the host's last-call countdown: stamps start_at with the absolute
-- server deadline at which the runner begins the game. Scoped to a session
-- still in the lobby (started_at IS NULL, the same "not yet begun" gate
-- StartSession uses) so arming a started game is a no-op; re-arming while in
-- the lobby overwrites the deadline (the host can re-arm). The execresult lets
-- the store map zero rows affected to "not in the lobby".
UPDATE sessions
SET start_at = ?
WHERE id = ?
  AND started_at IS NULL;

-- name: CancelSessionStart :execresult
-- Cancels an armed last-call countdown by clearing start_at. Scoped to a
-- session still in the lobby (started_at IS NULL) so a cancel after the game
-- has begun is a no-op. The execresult lets the store map zero rows affected
-- to "not in the lobby".
UPDATE sessions
SET start_at = NULL
WHERE id = ?
  AND started_at IS NULL;

-- name: SetSessionRoundIntro :exec
-- Moves the session into the round_intro phase for the given round and clears
-- the per-question runner columns (the intro screen runs before any question
-- is issued).
UPDATE sessions
SET phase               = 'round_intro',
    current_round_id    = ?,
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL
WHERE id = ?;

-- name: SetSessionQuestion :exec
-- Issues a question: records the current round + question and the server
-- answer window (started_at -> expires_at), and moves into the question phase.
UPDATE sessions
SET phase               = 'question',
    current_round_id    = ?,
    current_question_id = ?,
    question_started_at = ?,
    question_expires_at = ?
WHERE id = ?;

-- name: SetSessionReveal :exec
-- Moves the session into the reveal phase, leaving the current question and
-- its window in place so a reader still sees which question is being revealed.
UPDATE sessions
SET phase = 'reveal'
WHERE id = ?;

-- name: SetSessionFinished :exec
-- Ends the session: marks it finished and clears the per-question runner
-- columns.
UPDATE sessions
SET phase               = 'finished',
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL,
    finished_at         = CURRENT_TIMESTAMP
WHERE id = ?;

-- name: SetSessionIntermission :execresult
-- Ends a game without closing the room (#836): marks it intermission (the
-- between-games screen showing the final standings while the host arms the next
-- quiz) and clears the per-question runner columns. finished_at is stamped so
-- the just-ended game has a finish time, but the room stays alive - distinct
-- from SetSessionFinished, which terminates the room. Scoped to a non-terminal
-- phase so a second invocation against an already-intermission or finished room
-- matches no row; the store layer keys the #891 play_count bump on rows
-- affected, so an accidental repeat call cannot double-bump the counter.
UPDATE sessions
SET phase               = 'intermission',
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL,
    finished_at         = CURRENT_TIMESTAMP
WHERE id = ?
  AND phase NOT IN ('intermission', 'finished');

-- name: RearmSession :execresult
-- Arms a quiz to play in a room whenever no game is running (#836): the first
-- game from an empty lobby (a room created with no quiz) and every later game
-- from the between-games intermission share this path. It points the room at
-- the chosen quiz, resets to the lobby, and clears every per-game runner column
-- (current round/question, the answer window, and the start/finish timestamps).
-- game_seq is bumped only when re-arming from intermission (the previous game
-- counted), so the first game from an empty lobby stays at the default 1 rather
-- than skipping to 2. Scoped to a room with no game in flight - either sitting
-- in intermission, or still in the lobby having never started (started_at IS
-- NULL) - so re-arming a live game or a terminally finished room is a no-op; the
-- execresult lets the store map zero rows affected to "no game can be armed now".
UPDATE sessions
SET quiz_id             = sqlc.arg('quiz_id'),
    game_seq            = CASE WHEN phase = 'intermission' THEN game_seq + 1 ELSE game_seq END,
    phase               = 'lobby',
    current_round_id    = NULL,
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL,
    started_at          = NULL,
    finished_at         = NULL,
    start_at            = NULL
WHERE id = sqlc.arg('id')
  AND (phase = 'intermission'
       OR (phase = 'lobby' AND started_at IS NULL));

-- name: ResetSessionPlayersReady :exec
-- Clears every roster player's ready flag for a room, used when re-arming the
-- next game (#836) so players start the new game's lobby un-readied rather than
-- carrying their previous game's ready state.
UPDATE session_players
SET is_ready = 0
WHERE session_id = ?;

-- name: UpsertSessionAnswer :exec
-- Records a player's pick for the current session question, tagged with the
-- room's current game_seq (#836) so a re-run of the same quiz records a fresh
-- pick per game rather than overwriting the previous game's. answered_at is the
-- server timestamp the pick landed. Idempotent on (session_id, question_id,
-- player_id, game_seq): a re-submit within the same game overwrites the option
-- and timestamp rather than duplicating, so a double-tap before close is the
-- last pick rather than an error. score stays NULL until the question closes.
INSERT INTO session_answers (session_id, question_id, player_id, option_id, answered_at, game_seq)
VALUES (sqlc.arg('session_id'),
        sqlc.arg('question_id'),
        sqlc.arg('player_id'),
        sqlc.arg('option_id'),
        sqlc.arg('answered_at'),
        (SELECT game_seq FROM sessions WHERE id = sqlc.arg('session_id')))
ON CONFLICT (session_id, question_id, player_id, game_seq)
    DO UPDATE SET option_id   = excluded.option_id,
                  answered_at = excluded.answered_at;

-- name: CountSessionAnswersForQuestion :one
-- Number of players who have picked for the given session question in the room's
-- current game (#836). The runner closes a question early once this reaches the
-- active-player count. Scoped to the session's current game_seq so a re-run of
-- the same quiz does not count the previous game's picks.
SELECT count(*) AS answer_count
FROM session_answers sa
WHERE sa.session_id = sqlc.arg('session_id')
  AND sa.question_id = sqlc.arg('question_id')
  AND sa.game_seq = (SELECT s.game_seq FROM sessions s WHERE s.id = sqlc.arg('session_id'));

-- name: TouchSessionPlayerLastSeen :execresult
-- Refreshes a participant's last_seen_at, the active-player heartbeat. The SSE
-- events handler calls it when the connection opens and periodically while it
-- is held, so a dropped player's last_seen_at goes stale and the runner stops
-- counting them as active (MP-10). Keyed on (join_code, player_id) so the
-- handler need only carry the code it already gates on.
UPDATE session_players
SET last_seen_at = CURRENT_TIMESTAMP
WHERE player_id = sqlc.arg('player_id')
  AND session_id = (SELECT id FROM sessions WHERE join_code = sqlc.arg('join_code'));

-- name: RefreshSessionPlayerLastSeenAt :exec
-- Stamps a participant's last_seen_at to a bound timestamp, the answer-as-
-- liveness refresh: recording a pick proves the player is present, so the
-- answer write bumps last_seen_at in the same transaction (see #712). seen is
-- bound as a CURRENT_TIMESTAMP-format text string ('YYYY-MM-DD HH:MM:SS') via
-- the CAST, so the value lands in the exact encoding the active-window
-- comparison in CountActivePlayersForSession reads (a bound Go time.Time would
-- arrive in a different format and the cross-format string compare would
-- silently lie). Bound (not CURRENT_TIMESTAMP) so a fake-clock test stays
-- deterministic.
UPDATE session_players
SET last_seen_at = CAST(sqlc.arg('seen') AS TEXT)
WHERE session_id = sqlc.arg('session_id')
  AND player_id = sqlc.arg('player_id');

-- name: TouchSessionHostLastSeen :execresult
-- Refreshes the host's host_last_seen_at, the host-presence heartbeat. The SSE
-- events handler calls it when the host's connection opens and periodically
-- while it is held, so a host who disconnects lets their presence age out, which
-- the runner's idle-close sweep reads to close a room gone idle (host away AND
-- no active players, #836). Keyed on join_code so the handler need only carry
-- the code it already gates on. The
-- execresult lets the store tell a missed update (unknown code) from a hit.
UPDATE sessions
SET host_last_seen_at = CURRENT_TIMESTAMP
WHERE join_code = sqlc.arg('join_code');

-- name: MarkSessionPlayerLeft :execresult
-- Marks the participant as having left the session identified by join code,
-- stamping left_at so the live presence reads (roster, answered-order badges)
-- drop them immediately. The standings deliberately keep a left player who has
-- already answered, so their score stays on the board across a TV refresh
-- (#766). Scoped to left_at IS NULL so a second leave is a no-op rather than
-- re-stamping the timestamp; the execresult lets the store map zero rows
-- affected to "not an active participant". Keyed on join code so the handler
-- need only carry the code it already gates on.
UPDATE session_players
SET left_at = CURRENT_TIMESTAMP
WHERE player_id = sqlc.arg('player_id')
  AND left_at IS NULL
  AND session_id = (SELECT id FROM sessions WHERE join_code = sqlc.arg('join_code'));

-- name: CountActivePlayersUnansweredForQuestion :one
-- Number of roster players who are still active (last_seen_at within the
-- heartbeat window) but have not yet picked for the given session question. The
-- runner early-closes a question once this reaches 0, so a dropped player whose
-- last_seen_at has gone stale no longer holds the question open. Excludes
-- players who have left (left_at set). since is the active-window cutoff the
-- runner computes from its injected clock, bound as a CURRENT_TIMESTAMP-format
-- text string ('YYYY-MM-DD HH:MM:SS') so both sides of the comparison share the
-- encoding last_seen_at is stored in; a bound Go time.Time would arrive in a
-- different format and the cross-format string comparison would silently lie
-- (the same trap retention.sql documents).
SELECT count(*) AS unanswered_count
FROM session_players sp
WHERE sp.session_id = sqlc.arg('session_id')
  AND sp.left_at IS NULL
  AND sp.last_seen_at >= CAST(sqlc.arg('since') AS TEXT)
  AND NOT EXISTS (
      SELECT 1
      FROM session_answers sa
      WHERE sa.session_id = sp.session_id
        AND sa.question_id = sqlc.arg('question_id')
        AND sa.player_id = sp.player_id
        AND sa.game_seq = (SELECT s.game_seq FROM sessions s WHERE s.id = sp.session_id)
  );

-- name: CountActivePlayersForSession :one
-- Number of roster players still active (last_seen_at within the heartbeat
-- window), excluding those who have left. Lets the runner tell an empty / all-
-- stale roster (which must time out, never early-close) from a roster with at
-- least one active player. since is the active-window cutoff the runner computes
-- from its injected clock, bound as a CURRENT_TIMESTAMP-format text string (see
-- CountActivePlayersUnansweredForQuestion for why a bound time.Time is wrong).
SELECT count(*) AS active_count
FROM session_players sp
WHERE sp.session_id = sqlc.arg('session_id')
  AND sp.left_at IS NULL
  AND sp.last_seen_at >= CAST(sqlc.arg('since') AS TEXT);

-- name: ListSessionAnswersForQuestion :many
-- Every pick for the given session question in answered order, joined to the
-- chosen option's correctness. Drives scoring at close and the answered-order
-- view. is_correct is the option flag; the runner only surfaces it to clients
-- in the reveal phase. Deliberately NOT filtered by session_players.left_at:
-- this read also backs scoring at close (the runner scores every recorded
-- pick), so a player who answered then left must still be scored, which keeps
-- their contribution to the quiz leaderboard intact (MP-10 decision 3). The
-- answered-order badges drop left players at the display layer instead, gated
-- on the live roster the state read already carries.
SELECT sa.player_id,
       sa.option_id,
       sa.answered_at,
       sa.score,
       o.is_correct
FROM session_answers sa
         JOIN options o ON o.id = sa.option_id
WHERE sa.session_id = sqlc.arg('session_id')
  AND sa.question_id = sqlc.arg('question_id')
  AND sa.game_seq = (SELECT s.game_seq FROM sessions s WHERE s.id = sqlc.arg('session_id'))
ORDER BY sa.answered_at, sa.id;

-- name: SetSessionAnswerScore :exec
-- Writes the computed score for one pick at question close, scoped to the room's
-- current game (#836) so scoring a re-run does not overwrite the previous game's
-- recorded score for the same question/player.
UPDATE session_answers
SET score = sqlc.arg('score')
WHERE session_id = sqlc.arg('session_id')
  AND question_id = sqlc.arg('question_id')
  AND player_id = sqlc.arg('player_id')
  AND game_seq = (SELECT s.game_seq FROM sessions s WHERE s.id = sqlc.arg('session_id'));

-- name: SetSessionRoundResults :exec
-- Moves the session into the round_results phase shown after the last question
-- of a round (before the next round's intro). current_round_id stays put so the
-- state read knows which round just finished; the per-question runner columns
-- are cleared because no question is live in this phase.
UPDATE sessions
SET phase               = 'round_results',
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL
WHERE id = ?;

-- name: ListSessionStandings :many
-- Per-player standings for a session: the score the player earned in the given
-- round (round_score) and their cumulative score across the whole session
-- (total_score). Anchored on the roster (LEFT JOIN to scored answers) so a
-- player who never answered still appears at 0, which the bar graph needs. The
-- round is selected by questions.round_id; coalesce turns "no scored answer" /
-- "score still NULL" into 0. display_name is the player's CURRENT
-- players.display_name (#716), joined live so a rename shows in the standings.
-- Ordered by total_score desc, then display_name so ranking is stable across
-- reads. A player belongs in the standings if they are still present
-- (left_at IS NULL) OR have actually played (recorded at least one session
-- answer): the standings are a stable record of everyone who played, so a player
-- who answered and then closed their browser keeps their score on the board
-- across a TV refresh (#766). Someone who left during the lobby/intro without
-- ever answering never played and so does not appear.
SELECT sp.player_id                 AS player_id,
       CAST(p.display_name AS TEXT) AS display_name,
       CAST(COALESCE(SUM(CASE WHEN q.round_id = sqlc.arg('round_id') THEN sa.score END), 0) AS INTEGER) AS round_score,
       CAST(COALESCE(SUM(sa.score), 0) AS INTEGER)                                                      AS total_score
FROM session_players sp
         JOIN players p ON p.id = sp.player_id
         LEFT JOIN session_answers sa
                   ON sa.session_id = sp.session_id AND sa.player_id = sp.player_id
                       AND sa.game_seq = (SELECT s.game_seq FROM sessions s WHERE s.id = sp.session_id)
         LEFT JOIN questions q ON q.id = sa.question_id
WHERE sp.session_id = sqlc.arg('session_id')
  AND (sp.left_at IS NULL
       OR EXISTS (SELECT 1 FROM session_answers sa2
                  WHERE sa2.session_id = sp.session_id AND sa2.player_id = sp.player_id
                    AND sa2.game_seq = (SELECT s.game_seq FROM sessions s WHERE s.id = sp.session_id)))
GROUP BY sp.player_id, p.display_name
ORDER BY total_score DESC, p.display_name;

-- name: GetSessionPlayerScore :one
-- One player's cumulative score for the current game in a session: the sum of
-- their scored answers, scoped to the session's current game_seq, with a NULL
-- (no scored answers yet) coalesced to 0. Backs the live answer-pad HUD, which
-- shows the viewer their running score during the question and reveal phases,
-- where Standings is not populated (#956). Uses the same per-game scoping and
-- score aggregation as ListSessionFinalStandings, narrowed to one player, so the
-- HUD score matches the standings total once the round results appear.
SELECT CAST(COALESCE(SUM(sa.score), 0) AS INTEGER) AS total_score
FROM session_answers sa
WHERE sa.session_id = sqlc.arg('session_id')
  AND sa.player_id = sqlc.arg('player_id')
  AND sa.game_seq = (SELECT s.game_seq FROM sessions s WHERE s.id = sa.session_id);

-- name: ListSessionFinalStandings :many
-- Per-player final standings for a session: cumulative score across the whole
-- session, anchored on the roster so non-answerers appear at 0. display_name is
-- the player's CURRENT players.display_name (#716), joined live so a rename
-- shows in the final standings. Same ordering as ListSessionStandings; used at
-- the finished phase, where there is no "current round" to break out. A player
-- belongs in the final standings if they are still present (left_at IS NULL) OR
-- have actually played (recorded at least one session answer): the finished
-- board is a stable record of everyone who played, so a player who answered and
-- then closed their browser keeps their score across a TV refresh (#766).
-- Someone who left during the lobby/intro without ever answering never played
-- and so does not appear.
SELECT sp.player_id                              AS player_id,
       CAST(p.display_name AS TEXT)              AS display_name,
       CAST(COALESCE(SUM(sa.score), 0) AS INTEGER) AS total_score
FROM session_players sp
         JOIN players p ON p.id = sp.player_id
         LEFT JOIN session_answers sa
                   ON sa.session_id = sp.session_id AND sa.player_id = sp.player_id
                       AND sa.game_seq = (SELECT s.game_seq FROM sessions s WHERE s.id = sp.session_id)
WHERE sp.session_id = sqlc.arg('session_id')
  AND (sp.left_at IS NULL
       OR EXISTS (SELECT 1 FROM session_answers sa2
                  WHERE sa2.session_id = sp.session_id AND sa2.player_id = sp.player_id
                    AND sa2.game_seq = (SELECT s.game_seq FROM sessions s WHERE s.id = sp.session_id)))
GROUP BY sp.player_id, p.display_name
ORDER BY total_score DESC, p.display_name;
