-- name: CreateSession :one
-- Inserts a hosted session. id is an xid generated by the store; join_code
-- is the collision-checked short code minted by the domain layer. phase
-- defaults to 'lobby' at the DB level. A duplicate join_code trips the
-- UNIQUE constraint, which the store surfaces so the caller can regenerate.
INSERT INTO sessions (id, quiz_id, host_player_id, join_code)
VALUES (?, ?, ?, ?)
RETURNING *;

-- name: GetSession :one
SELECT *
FROM sessions
WHERE id = ?;

-- name: GetSessionByJoinCode :one
-- Resolves a typed/scanned room code to its session. join_code is UNIQUE so
-- this returns at most one row.
SELECT *
FROM sessions
WHERE join_code = ?;

-- name: JoinCodeExists :one
-- Cheap existence probe for a candidate join code so the generator can
-- regenerate on collision before paying for the INSERT.
SELECT EXISTS(SELECT 1 FROM sessions WHERE join_code = ?) AS code_exists;

-- name: PlayerFinishedSessionForQuiz :one
-- Reports whether the player has a roster row in a finished session of the
-- given quiz. Backs the replay gate: a live quiz may be played once, so a
-- player who already sat through a finished session of it is blocked from
-- joining a new one until an admin resets their participation.
SELECT EXISTS (
    SELECT 1
    FROM session_players sp
    JOIN sessions s ON s.id = sp.session_id
    WHERE sp.player_id = sqlc.arg('player_id')
      AND s.quiz_id = sqlc.arg('quiz_id')
      AND s.phase = 'finished'
) AS has_finished;

-- name: SessionHasPlayer :one
-- Reports whether the player has EVER held a roster row in the session
-- identified by join code, regardless of left_at. Backs the reconnect/resume
-- gate in Service.Join: a prior participant - including one whose row is marked
-- left_at (e.g. a beforeunload leave beacon fired on a reload) - may re-Join
-- past the lobby, which revives their row. Deliberately NOT filtered by left_at,
-- unlike the live roster read, so a reloading player who just left can still
-- resume; a player who never joined matches nothing and is rejected as a late
-- joiner.
SELECT EXISTS (
    SELECT 1
    FROM session_players sp
    JOIN sessions s ON s.id = sp.session_id
    WHERE s.join_code = sqlc.arg('join_code')
      AND sp.player_id = sqlc.arg('player_id')
) AS has_player;

-- name: ListFinishedSessionPlaysForPlayer :many
-- Finished live-quiz plays for the given player, newest-first, one row per
-- quiz. A play is a roster row in a finished session; collapsing to one row
-- per quiz keeps the admin detail list to "quizzes this player has played"
-- rather than every individual session. finished_at is the most recent
-- finish time among the player's sessions of that quiz, read off the
-- representative session row (not aggregated) so it stays a typed DATETIME.
-- Joined to quizzes for the title so the detail view renders without a
-- second round trip.
SELECT
    s.quiz_id              AS quiz_id,
    CAST(q.title AS TEXT)  AS quiz_title,
    s.finished_at          AS finished_at
FROM sessions s
JOIN quizzes q ON q.id = s.quiz_id
WHERE s.phase = 'finished'
  AND s.finished_at = (
      SELECT MAX(s2.finished_at)
      FROM sessions s2
      JOIN session_players sp2 ON sp2.session_id = s2.id
      WHERE s2.quiz_id = s.quiz_id
        AND s2.phase = 'finished'
        AND sp2.player_id = sqlc.arg('player_id')
  )
  AND EXISTS (
      SELECT 1 FROM session_players sp
      WHERE sp.session_id = s.id
        AND sp.player_id = sqlc.arg('player_id')
  )
GROUP BY s.quiz_id
ORDER BY s.finished_at DESC, s.quiz_id DESC
LIMIT sqlc.arg('row_limit');

-- name: DeleteSessionAnswersForPlayerOnQuiz :exec
-- Hard-deletes the player's recorded picks across every session of the given
-- quiz. Run before DeleteSessionPlayersForPlayerOnQuiz so the answer rows go
-- first (session_answers has no FK to session_players, so order is not
-- enforced, but deleting children-then-roster reads cleanly).
DELETE FROM session_answers
WHERE player_id = sqlc.arg('player_id')
  AND session_id IN (SELECT id FROM sessions WHERE quiz_id = sqlc.arg('quiz_id'));

-- name: DeleteSessionPlayersForPlayerOnQuiz :exec
-- Hard-deletes the player's roster rows across every session of the given
-- quiz, clearing the replay gate so the player can join a new session of it.
DELETE FROM session_players
WHERE player_id = sqlc.arg('player_id')
  AND session_id IN (SELECT id FROM sessions WHERE quiz_id = sqlc.arg('quiz_id'));

-- name: UpsertSessionPlayer :one
-- Adds a player to a session's roster, or revives an existing row on re-join
-- (clearing left_at and refreshing last_seen_at). The display name is no
-- longer stored per session (#716): the roster reads join players and select
-- the current players.display_name, so a rename propagates everywhere. The
-- (session_id, player_id) UNIQUE makes the upsert idempotent for the same
-- player.
INSERT INTO session_players (session_id, player_id)
VALUES (?, ?)
ON CONFLICT (session_id, player_id)
    DO UPDATE SET left_at      = NULL,
                  last_seen_at = CURRENT_TIMESTAMP
RETURNING *;

-- name: GetSessionPlayer :one
SELECT *
FROM session_players
WHERE session_id = ?
  AND player_id = ?;

-- name: SetSessionPlayerReady :execresult
-- Toggles a participant's ready flag and refreshes last_seen_at. Scoped to
-- (session_id, player_id) so it only ever touches the caller's own roster
-- row. The execresult lets the store map zero rows affected to "not a
-- participant".
UPDATE session_players
SET is_ready     = ?,
    last_seen_at = CURRENT_TIMESTAMP
WHERE session_id = ?
  AND player_id = ?;

-- name: ListSessionPlayers :many
-- The lobby roster in join order. Excludes players who have left (left_at
-- set, MP-10) so the lobby shows the current room. display_name is the
-- player's CURRENT players.display_name (#716), joined live so a rename shows
-- everywhere rather than a per-session snapshot.
SELECT sp.id,
       sp.session_id,
       sp.player_id,
       CAST(p.display_name AS TEXT) AS display_name,
       sp.is_ready,
       sp.joined_at,
       sp.last_seen_at,
       sp.left_at
FROM session_players sp
         JOIN players p ON p.id = sp.player_id
WHERE sp.session_id = ?
  AND sp.left_at IS NULL
ORDER BY sp.joined_at, sp.id;

-- name: ListLiveSessionIDs :many
-- Ids of every session not yet finished, in creation order. The runner scans
-- these each beat to auto-start lobbies and advance in-flight games; finished
-- sessions are skipped so the scan stays bounded to active rooms.
SELECT id
FROM sessions
WHERE phase != 'finished'
ORDER BY created_at, id;

-- name: StartSession :execresult
-- Stamps started_at and moves the session out of the lobby. Scoped to a
-- session still in the lobby so a re-issued start (host double-click, or the
-- auto-start racing the host) is a no-op rather than resetting the clock.
UPDATE sessions
SET started_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND started_at IS NULL;

-- name: ArmSessionStart :execresult
-- Arms the host's last-call countdown: stamps start_at with the absolute
-- server deadline at which the runner begins the game. Scoped to a session
-- still in the lobby (started_at IS NULL, the same "not yet begun" gate
-- StartSession uses) so arming a started game is a no-op; re-arming while in
-- the lobby overwrites the deadline (the host can re-arm). The execresult lets
-- the store map zero rows affected to "not in the lobby".
UPDATE sessions
SET start_at = ?
WHERE id = ?
  AND started_at IS NULL;

-- name: CancelSessionStart :execresult
-- Cancels an armed last-call countdown by clearing start_at. Scoped to a
-- session still in the lobby (started_at IS NULL) so a cancel after the game
-- has begun is a no-op. The execresult lets the store map zero rows affected
-- to "not in the lobby".
UPDATE sessions
SET start_at = NULL
WHERE id = ?
  AND started_at IS NULL;

-- name: SetSessionRoundIntro :exec
-- Moves the session into the round_intro phase for the given round and clears
-- the per-question runner columns (the intro screen runs before any question
-- is issued).
UPDATE sessions
SET phase               = 'round_intro',
    current_round_id    = ?,
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL
WHERE id = ?;

-- name: SetSessionQuestion :exec
-- Issues a question: records the current round + question and the server
-- answer window (started_at -> expires_at), and moves into the question phase.
UPDATE sessions
SET phase               = 'question',
    current_round_id    = ?,
    current_question_id = ?,
    question_started_at = ?,
    question_expires_at = ?
WHERE id = ?;

-- name: SetSessionReveal :exec
-- Moves the session into the reveal phase, leaving the current question and
-- its window in place so a reader still sees which question is being revealed.
UPDATE sessions
SET phase = 'reveal'
WHERE id = ?;

-- name: SetSessionFinished :exec
-- Ends the session: marks it finished and clears the per-question runner
-- columns.
UPDATE sessions
SET phase               = 'finished',
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL,
    finished_at         = CURRENT_TIMESTAMP
WHERE id = ?;

-- name: UpsertSessionAnswer :exec
-- Records a player's pick for the current session question. answered_at is the
-- server timestamp the pick landed. Idempotent on (session_id, question_id,
-- player_id): a re-submit overwrites the option and timestamp rather than
-- duplicating, so a double-tap before close is the last pick rather than an
-- error. score stays NULL until the question closes.
INSERT INTO session_answers (session_id, question_id, player_id, option_id, answered_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (session_id, question_id, player_id)
    DO UPDATE SET option_id   = excluded.option_id,
                  answered_at = excluded.answered_at;

-- name: CountSessionAnswersForQuestion :one
-- Number of players who have picked for the given session question. The runner
-- closes a question early once this reaches the active-player count.
SELECT count(*) AS answer_count
FROM session_answers
WHERE session_id = ?
  AND question_id = ?;

-- name: TouchSessionPlayerLastSeen :execresult
-- Refreshes a participant's last_seen_at, the active-player heartbeat. The SSE
-- events handler calls it when the connection opens and periodically while it
-- is held, so a dropped player's last_seen_at goes stale and the runner stops
-- counting them as active (MP-10). Keyed on (join_code, player_id) so the
-- handler need only carry the code it already gates on.
UPDATE session_players
SET last_seen_at = CURRENT_TIMESTAMP
WHERE player_id = sqlc.arg('player_id')
  AND session_id = (SELECT id FROM sessions WHERE join_code = sqlc.arg('join_code'));

-- name: TouchSessionHostLastSeen :execresult
-- Refreshes the host's host_last_seen_at, the host-presence heartbeat. The SSE
-- events handler calls it when the host's connection opens and periodically
-- while it is held, so a host who disconnects mid-game goes stale and the
-- runner's abandon sweep finishes the lingering session (MP-10). Keyed on
-- join_code so the handler need only carry the code it already gates on. The
-- execresult lets the store tell a missed update (unknown code) from a hit.
UPDATE sessions
SET host_last_seen_at = CURRENT_TIMESTAMP
WHERE join_code = sqlc.arg('join_code');

-- name: MarkSessionPlayerLeft :execresult
-- Marks the participant as having left the session identified by join code,
-- stamping left_at so the live reads (roster, answered-order badges,
-- standings) drop them immediately. Scoped to left_at IS NULL so a second
-- leave is a no-op rather than re-stamping the timestamp; the execresult lets
-- the store map zero rows affected to "not an active participant". Keyed on
-- join code so the handler need only carry the code it already gates on.
UPDATE session_players
SET left_at = CURRENT_TIMESTAMP
WHERE player_id = sqlc.arg('player_id')
  AND left_at IS NULL
  AND session_id = (SELECT id FROM sessions WHERE join_code = sqlc.arg('join_code'));

-- name: CountActivePlayersUnansweredForQuestion :one
-- Number of roster players who are still active (last_seen_at within the
-- heartbeat window) but have not yet picked for the given session question. The
-- runner early-closes a question once this reaches 0, so a dropped player whose
-- last_seen_at has gone stale no longer holds the question open. Excludes
-- players who have left (left_at set). since is the active-window cutoff the
-- runner computes from its injected clock, bound as a CURRENT_TIMESTAMP-format
-- text string ('YYYY-MM-DD HH:MM:SS') so both sides of the comparison share the
-- encoding last_seen_at is stored in; a bound Go time.Time would arrive in a
-- different format and the cross-format string comparison would silently lie
-- (the same trap retention.sql documents).
SELECT count(*) AS unanswered_count
FROM session_players sp
WHERE sp.session_id = sqlc.arg('session_id')
  AND sp.left_at IS NULL
  AND sp.last_seen_at >= CAST(sqlc.arg('since') AS TEXT)
  AND NOT EXISTS (
      SELECT 1
      FROM session_answers sa
      WHERE sa.session_id = sp.session_id
        AND sa.question_id = sqlc.arg('question_id')
        AND sa.player_id = sp.player_id
  );

-- name: CountActivePlayersForSession :one
-- Number of roster players still active (last_seen_at within the heartbeat
-- window), excluding those who have left. Lets the runner tell an empty / all-
-- stale roster (which must time out, never early-close) from a roster with at
-- least one active player. since is the active-window cutoff the runner computes
-- from its injected clock, bound as a CURRENT_TIMESTAMP-format text string (see
-- CountActivePlayersUnansweredForQuestion for why a bound time.Time is wrong).
SELECT count(*) AS active_count
FROM session_players sp
WHERE sp.session_id = sqlc.arg('session_id')
  AND sp.left_at IS NULL
  AND sp.last_seen_at >= CAST(sqlc.arg('since') AS TEXT);

-- name: ListSessionAnswersForQuestion :many
-- Every pick for the given session question in answered order, joined to the
-- chosen option's correctness. Drives scoring at close and the answered-order
-- view. is_correct is the option flag; the runner only surfaces it to clients
-- in the reveal phase. Deliberately NOT filtered by session_players.left_at:
-- this read also backs scoring at close (the runner scores every recorded
-- pick), so a player who answered then left must still be scored, which keeps
-- their contribution to the quiz leaderboard intact (MP-10 decision 3). The
-- answered-order badges drop left players at the display layer instead, gated
-- on the live roster the state read already carries.
SELECT sa.player_id,
       sa.option_id,
       sa.answered_at,
       sa.score,
       o.is_correct
FROM session_answers sa
         JOIN options o ON o.id = sa.option_id
WHERE sa.session_id = ?
  AND sa.question_id = ?
ORDER BY sa.answered_at, sa.id;

-- name: SetSessionAnswerScore :exec
-- Writes the computed score for one pick at question close.
UPDATE session_answers
SET score = ?
WHERE session_id = ?
  AND question_id = ?
  AND player_id = ?;

-- name: SetSessionRoundResults :exec
-- Moves the session into the round_results phase shown after the last question
-- of a round (before the next round's intro). current_round_id stays put so the
-- state read knows which round just finished; the per-question runner columns
-- are cleared because no question is live in this phase.
UPDATE sessions
SET phase               = 'round_results',
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL
WHERE id = ?;

-- name: ListSessionStandings :many
-- Per-player standings for a session: the score the player earned in the given
-- round (round_score) and their cumulative score across the whole session
-- (total_score). Anchored on the roster (LEFT JOIN to scored answers) so a
-- player who never answered still appears at 0, which the bar graph needs. The
-- round is selected by questions.round_id; coalesce turns "no scored answer" /
-- "score still NULL" into 0. display_name is the player's CURRENT
-- players.display_name (#716), joined live so a rename shows in the standings.
-- Ordered by total_score desc, then display_name so ranking is stable across
-- reads.
SELECT sp.player_id                 AS player_id,
       CAST(p.display_name AS TEXT) AS display_name,
       CAST(COALESCE(SUM(CASE WHEN q.round_id = sqlc.arg('round_id') THEN sa.score END), 0) AS INTEGER) AS round_score,
       CAST(COALESCE(SUM(sa.score), 0) AS INTEGER)                                                      AS total_score
FROM session_players sp
         JOIN players p ON p.id = sp.player_id
         LEFT JOIN session_answers sa
                   ON sa.session_id = sp.session_id AND sa.player_id = sp.player_id
         LEFT JOIN questions q ON q.id = sa.question_id
WHERE sp.session_id = sqlc.arg('session_id')
  AND sp.left_at IS NULL
GROUP BY sp.player_id, p.display_name
ORDER BY total_score DESC, p.display_name;

-- name: ListSessionFinalStandings :many
-- Per-player final standings for a session: cumulative score across the whole
-- session, anchored on the roster so non-answerers appear at 0. display_name is
-- the player's CURRENT players.display_name (#716), joined live so a rename
-- shows in the final standings. Same ordering as ListSessionStandings; used at
-- the finished phase, where there is no "current round" to break out.
SELECT sp.player_id                              AS player_id,
       CAST(p.display_name AS TEXT)              AS display_name,
       CAST(COALESCE(SUM(sa.score), 0) AS INTEGER) AS total_score
FROM session_players sp
         JOIN players p ON p.id = sp.player_id
         LEFT JOIN session_answers sa
                   ON sa.session_id = sp.session_id AND sa.player_id = sp.player_id
WHERE sp.session_id = sqlc.arg('session_id')
  AND sp.left_at IS NULL
GROUP BY sp.player_id, p.display_name
ORDER BY total_score DESC, p.display_name;

-- name: ListSessionResultsForQuizLeaderboard :many
-- One row per (player) summing their score across every FINISHED live session
-- of the given quiz, so the quiz's standard leaderboard reflects hosted games
-- alongside solo play (decision 3). A live session contributes only once it is
-- finished, so a game in progress does not pollute the board; re-finishing a
-- session changes nothing here (the phase is already 'finished'), which keeps
-- the contribution idempotent. Anchored on the roster so a player who joined
-- but never scored still surfaces at 0, matching the solo leaderboard's
-- joined-but-unanswered behaviour (#335). Scores are read straight from
-- session_answers.score (already computed at close with the same CalculateScore
-- curve solo play uses) rather than recomputed. Keyed on player_id alone (a
-- player may host or play more than one finished session of the same quiz);
-- their scores sum. display_name is the player's CURRENT players.display_name
-- (#716), joined live so a rename reflects on the quiz's standard leaderboard
-- exactly as solo play already does (games.sql joins players the same way).
-- left_at is deliberately NOT filtered here (unlike the live roster /
-- standings reads): a player who played still counts toward the quiz's
-- standard leaderboard even if they left the room before the session
-- finished (MP-10). Leaving drops a player from the in-session surfaces, not
-- from the record of having played.
SELECT sp.player_id                               AS player_id,
       CAST(p.display_name AS TEXT)               AS display_name,
       CAST(COALESCE(SUM(sa.score), 0) AS INTEGER) AS total_score
FROM sessions s
         JOIN session_players sp ON sp.session_id = s.id
         JOIN players p ON p.id = sp.player_id
         LEFT JOIN session_answers sa
                   ON sa.session_id = sp.session_id AND sa.player_id = sp.player_id
WHERE s.quiz_id = ?
  AND s.phase = 'finished'
GROUP BY sp.player_id, p.display_name;
