-- name: CreateSession :one
-- Inserts a hosted session. id is an xid generated by the store; join_code
-- is the collision-checked short code minted by the domain layer. phase
-- defaults to 'lobby' at the DB level. A duplicate join_code trips the
-- UNIQUE constraint, which the store surfaces so the caller can regenerate.
INSERT INTO sessions (id, quiz_id, host_player_id, join_code)
VALUES (?, ?, ?, ?)
RETURNING *;

-- name: GetSession :one
SELECT *
FROM sessions
WHERE id = ?;

-- name: GetSessionByJoinCode :one
-- Resolves a typed/scanned room code to its session. join_code is UNIQUE so
-- this returns at most one row.
SELECT *
FROM sessions
WHERE join_code = ?;

-- name: JoinCodeExists :one
-- Cheap existence probe for a candidate join code so the generator can
-- regenerate on collision before paying for the INSERT.
SELECT EXISTS(SELECT 1 FROM sessions WHERE join_code = ?) AS code_exists;

-- name: UpsertSessionPlayer :one
-- Adds a player to a session's roster, or revives an existing row on
-- re-join (clearing left_at and refreshing last_seen_at + display_name).
-- A per-session display-name collision trips UNIQUE (session_id,
-- display_name); the caller retries with a petname. The (session_id,
-- player_id) UNIQUE makes the upsert idempotent for the same player.
INSERT INTO session_players (session_id, player_id, display_name)
VALUES (?, ?, ?)
ON CONFLICT (session_id, player_id)
    DO UPDATE SET display_name = excluded.display_name,
                  left_at      = NULL,
                  last_seen_at = CURRENT_TIMESTAMP
RETURNING *;

-- name: GetSessionPlayer :one
SELECT *
FROM session_players
WHERE session_id = ?
  AND player_id = ?;

-- name: SetSessionPlayerReady :execresult
-- Toggles a participant's ready flag and refreshes last_seen_at. Scoped to
-- (session_id, player_id) so it only ever touches the caller's own roster
-- row. The execresult lets the store map zero rows affected to "not a
-- participant".
UPDATE session_players
SET is_ready     = ?,
    last_seen_at = CURRENT_TIMESTAMP
WHERE session_id = ?
  AND player_id = ?;

-- name: ListSessionPlayers :many
-- The lobby roster in join order. Excludes players who have left (left_at
-- set, MP-10) so the lobby shows the current room.
SELECT *
FROM session_players
WHERE session_id = ?
  AND left_at IS NULL
ORDER BY joined_at, id;

-- name: ListLiveSessionIDs :many
-- Ids of every session not yet finished, in creation order. The runner scans
-- these each beat to auto-start lobbies and advance in-flight games; finished
-- sessions are skipped so the scan stays bounded to active rooms.
SELECT id
FROM sessions
WHERE phase != 'finished'
ORDER BY created_at, id;

-- name: StartSession :execresult
-- Stamps started_at and moves the session out of the lobby. Scoped to a
-- session still in the lobby so a re-issued start (host double-click, or the
-- auto-start racing the host) is a no-op rather than resetting the clock.
UPDATE sessions
SET started_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND started_at IS NULL;

-- name: SetSessionRoundIntro :exec
-- Moves the session into the round_intro phase for the given round and clears
-- the per-question runner columns (the intro screen runs before any question
-- is issued).
UPDATE sessions
SET phase               = 'round_intro',
    current_round_id    = ?,
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL
WHERE id = ?;

-- name: SetSessionQuestion :exec
-- Issues a question: records the current round + question and the server
-- answer window (started_at -> expires_at), and moves into the question phase.
UPDATE sessions
SET phase               = 'question',
    current_round_id    = ?,
    current_question_id = ?,
    question_started_at = ?,
    question_expires_at = ?
WHERE id = ?;

-- name: SetSessionReveal :exec
-- Moves the session into the reveal phase, leaving the current question and
-- its window in place so a reader still sees which question is being revealed.
UPDATE sessions
SET phase = 'reveal'
WHERE id = ?;

-- name: SetSessionFinished :exec
-- Ends the session: marks it finished and clears the per-question runner
-- columns.
UPDATE sessions
SET phase               = 'finished',
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL,
    finished_at         = CURRENT_TIMESTAMP
WHERE id = ?;

-- name: UpsertSessionAnswer :exec
-- Records a player's pick for the current session question. answered_at is the
-- server timestamp the pick landed. Idempotent on (session_id, question_id,
-- player_id): a re-submit overwrites the option and timestamp rather than
-- duplicating, so a double-tap before close is the last pick rather than an
-- error. score stays NULL until the question closes.
INSERT INTO session_answers (session_id, question_id, player_id, option_id, answered_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (session_id, question_id, player_id)
    DO UPDATE SET option_id   = excluded.option_id,
                  answered_at = excluded.answered_at;

-- name: CountSessionAnswersForQuestion :one
-- Number of players who have picked for the given session question. The runner
-- closes a question early once this reaches the active-player count.
SELECT count(*) AS answer_count
FROM session_answers
WHERE session_id = ?
  AND question_id = ?;

-- name: ListSessionAnswersForQuestion :many
-- Every pick for the given session question in answered order, joined to the
-- chosen option's correctness. Drives scoring at close and the answered-order
-- view. is_correct is the option flag; the runner only surfaces it to clients
-- in the reveal phase.
SELECT sa.player_id,
       sa.option_id,
       sa.answered_at,
       sa.score,
       o.is_correct
FROM session_answers sa
         JOIN options o ON o.id = sa.option_id
WHERE sa.session_id = ?
  AND sa.question_id = ?
ORDER BY sa.answered_at, sa.id;

-- name: SetSessionAnswerScore :exec
-- Writes the computed score for one pick at question close.
UPDATE session_answers
SET score = ?
WHERE session_id = ?
  AND question_id = ?
  AND player_id = ?;

-- name: SetSessionRoundResults :exec
-- Moves the session into the round_results phase shown after the last question
-- of a round (before the next round's intro). current_round_id stays put so the
-- state read knows which round just finished; the per-question runner columns
-- are cleared because no question is live in this phase.
UPDATE sessions
SET phase               = 'round_results',
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL
WHERE id = ?;

-- name: ListSessionStandings :many
-- Per-player standings for a session: the score the player earned in the given
-- round (round_score) and their cumulative score across the whole session
-- (total_score). Anchored on the roster (LEFT JOIN to scored answers) so a
-- player who never answered still appears at 0, which the bar graph needs. The
-- round is selected by questions.round_id; coalesce turns "no scored answer" /
-- "score still NULL" into 0. Ordered by total_score desc, then display_name so
-- ranking is stable across reads.
SELECT sp.player_id    AS player_id,
       sp.display_name AS display_name,
       CAST(COALESCE(SUM(CASE WHEN q.round_id = sqlc.arg('round_id') THEN sa.score END), 0) AS INTEGER) AS round_score,
       CAST(COALESCE(SUM(sa.score), 0) AS INTEGER)                                                      AS total_score
FROM session_players sp
         LEFT JOIN session_answers sa
                   ON sa.session_id = sp.session_id AND sa.player_id = sp.player_id
         LEFT JOIN questions q ON q.id = sa.question_id
WHERE sp.session_id = sqlc.arg('session_id')
  AND sp.left_at IS NULL
GROUP BY sp.player_id, sp.display_name
ORDER BY total_score DESC, sp.display_name;

-- name: ListSessionFinalStandings :many
-- Per-player final standings for a session: cumulative score across the whole
-- session, anchored on the roster so non-answerers appear at 0. Same ordering
-- as ListSessionStandings; used at the finished phase, where there is no
-- "current round" to break out.
SELECT sp.player_id                              AS player_id,
       sp.display_name                           AS display_name,
       CAST(COALESCE(SUM(sa.score), 0) AS INTEGER) AS total_score
FROM session_players sp
         LEFT JOIN session_answers sa
                   ON sa.session_id = sp.session_id AND sa.player_id = sp.player_id
WHERE sp.session_id = sqlc.arg('session_id')
  AND sp.left_at IS NULL
GROUP BY sp.player_id, sp.display_name
ORDER BY total_score DESC, sp.display_name;

-- name: ListSessionResultsForQuizLeaderboard :many
-- One row per (player) summing their score across every FINISHED live session
-- of the given quiz, so the quiz's standard leaderboard reflects hosted games
-- alongside solo play (decision 3). A live session contributes only once it is
-- finished, so a game in progress does not pollute the board; re-finishing a
-- session changes nothing here (the phase is already 'finished'), which keeps
-- the contribution idempotent. Anchored on the roster so a player who joined
-- but never scored still surfaces at 0, matching the solo leaderboard's
-- joined-but-unanswered behaviour (#335). Scores are read straight from
-- session_answers.score (already computed at close with the same CalculateScore
-- curve solo play uses) rather than recomputed. Keyed on player_id alone (a
-- player may host or play more than one finished session of the same quiz);
-- their scores sum and MAX(display_name) picks one stable name for the row.
SELECT sp.player_id                               AS player_id,
       CAST(MAX(sp.display_name) AS TEXT)          AS display_name,
       CAST(COALESCE(SUM(sa.score), 0) AS INTEGER) AS total_score
FROM sessions s
         JOIN session_players sp ON sp.session_id = s.id AND sp.left_at IS NULL
         LEFT JOIN session_answers sa
                   ON sa.session_id = sp.session_id AND sa.player_id = sp.player_id
WHERE s.quiz_id = ?
  AND s.phase = 'finished'
GROUP BY sp.player_id;
