// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countPlayersByOnboardingState = `-- name: CountPlayersByOnboardingState :many
SELECT
    CASE
        WHEN EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id) THEN 'oauth'
        WHEN p.email_verified_at IS NOT NULL THEN 'verified'
        WHEN p.password_hash IS NOT NULL THEN 'unverified'
        ELSE 'anonymous'
    END AS state,
    COUNT(*) AS player_count
FROM players p
GROUP BY state
`

type CountPlayersByOnboardingStateRow struct {
	State       string
	PlayerCount int64
}

// One row per onboarding state bucket. Feeds the tab-strip counts on the
// admin players list. The CASE expression here must match the one in
// ListPlayersByOnboardingState below; if a branch shifts in one query but
// not the other, the tabs will show counts that disagree with the page.
func (q *Queries) CountPlayersByOnboardingState(ctx context.Context) ([]CountPlayersByOnboardingStateRow, error) {
	rows, err := q.db.QueryContext(ctx, countPlayersByOnboardingState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountPlayersByOnboardingStateRow
	for rows.Next() {
		var i CountPlayersByOnboardingStateRow
		if err := rows.Scan(&i.State, &i.PlayerCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPlayersInOnboardingState = `-- name: CountPlayersInOnboardingState :one
SELECT COUNT(*) FROM players p
WHERE
    CAST(?1 AS TEXT) = 'all'
    OR (
        CASE
            WHEN EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id) THEN 'oauth'
            WHEN p.email_verified_at IS NOT NULL THEN 'verified'
            WHEN p.password_hash IS NOT NULL THEN 'unverified'
            ELSE 'anonymous'
        END
    ) = CAST(?1 AS TEXT)
`

// Total rows matching the supplied state filter; powers the page-count
// math when a non-default ?state= filter is applied. The CASE must stay
// in lockstep with ListPlayersByOnboardingState above.
func (q *Queries) CountPlayersInOnboardingState(ctx context.Context, state string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayersInOnboardingState, state)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlayerByAdmin = `-- name: CreatePlayerByAdmin :one
INSERT INTO players (username, email, password_hash, email_verified_at, role, username_claimed)
VALUES (
    ?1,
    ?2,
    ?3,
    CURRENT_TIMESTAMP,
    'player',
    1
)
RETURNING id, username, email, password_hash, role, created_at, username_claimed, email_verified_at, session_version, role_changed_at
`

type CreatePlayerByAdminParams struct {
	Username     string
	Email        sql.NullString
	PasswordHash sql.NullString
}

// Admin-initiated player creation (#450). Stamps email_verified_at at
// CURRENT_TIMESTAMP so the new row bypasses the email loop entirely; the
// admin hands the credentials to the recipient out-of-band. password_hash
// is nullable on the column but the handler enforces a non-empty hash so
// the row can log in immediately. role is fixed to 'player' - the admin
// promotion CASE only fires on the public register/oauth paths.
func (q *Queries) CreatePlayerByAdmin(ctx context.Context, arg CreatePlayerByAdminParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayerByAdmin, arg.Username, arg.Email, arg.PasswordHash)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
		&i.EmailVerifiedAt,
		&i.SessionVersion,
		&i.RoleChangedAt,
	)
	return i, err
}

const getPlayerWithOnboardingState = `-- name: GetPlayerWithOnboardingState :one
SELECT
    p.id, p.username, p.email, p.password_hash, p.role, p.created_at, p.username_claimed, p.email_verified_at, p.session_version, p.role_changed_at,
    EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id) AS has_oauth,
    CAST(COALESCE(
        (SELECT pi.provider FROM player_identities pi WHERE pi.player_id = p.id ORDER BY pi.provider LIMIT 1),
        ''
    ) AS TEXT) AS oauth_provider,
    CAST(
        CASE
            WHEN EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id) THEN 'oauth'
            WHEN p.email_verified_at IS NOT NULL THEN 'verified'
            WHEN p.password_hash IS NOT NULL THEN 'unverified'
            ELSE 'anonymous'
        END
    AS TEXT) AS onboarding_state
FROM players p
WHERE p.id = ?1
LIMIT 1
`

type GetPlayerWithOnboardingStateRow struct {
	ID              int64
	Username        string
	Email           sql.NullString
	PasswordHash    sql.NullString
	Role            string
	CreatedAt       time.Time
	UsernameClaimed int64
	EmailVerifiedAt sql.NullTime
	SessionVersion  int64
	RoleChangedAt   sql.NullTime
	HasOauth        bool
	OauthProvider   string
	OnboardingState string
}

// Single-row variant used by the per-player detail view. Returns the
// player columns plus the derived has_oauth / oauth_provider /
// onboarding_state fields so the handler does not have to compute them
// separately. The CASE must stay in lockstep with the list query above.
func (q *Queries) GetPlayerWithOnboardingState(ctx context.Context, id int64) (GetPlayerWithOnboardingStateRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayerWithOnboardingState, id)
	var i GetPlayerWithOnboardingStateRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
		&i.EmailVerifiedAt,
		&i.SessionVersion,
		&i.RoleChangedAt,
		&i.HasOauth,
		&i.OauthProvider,
		&i.OnboardingState,
	)
	return i, err
}

const insertAdminAudit = `-- name: InsertAdminAudit :exec
INSERT INTO admin_audit (actor_player_id, target_player_id, action, payload)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type InsertAdminAuditParams struct {
	ActorPlayerID  sql.NullInt64
	TargetPlayerID int64
	Action         string
	Payload        string
}

// Records one admin-initiated mutation against a player row. payload is a
// JSON blob the writer encodes (e.g. {"new_email":"..."} for email_set);
// the column carries it verbatim so a future schema change need not migrate
// existing rows. created_at falls through to the column default so every
// row stamps in the DB's wall clock, not the caller's.
func (q *Queries) InsertAdminAudit(ctx context.Context, arg InsertAdminAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertAdminAudit,
		arg.ActorPlayerID,
		arg.TargetPlayerID,
		arg.Action,
		arg.Payload,
	)
	return err
}

const listAdminAuditForTarget = `-- name: ListAdminAuditForTarget :many
SELECT
    a.id,
    a.actor_player_id,
    CAST(COALESCE(p.username, '') AS TEXT) AS actor_username,
    a.target_player_id,
    a.action,
    a.payload,
    a.created_at
FROM admin_audit a
LEFT JOIN players p ON p.id = a.actor_player_id
WHERE a.target_player_id = ?1
ORDER BY a.created_at DESC, a.id DESC
LIMIT ?2
`

type ListAdminAuditForTargetParams struct {
	TargetPlayerID int64
	RowLimit       int64
}

type ListAdminAuditForTargetRow struct {
	ID             int64
	ActorPlayerID  sql.NullInt64
	ActorUsername  string
	TargetPlayerID int64
	Action         string
	Payload        string
	CreatedAt      time.Time
}

// Returns the most-recent admin actions taken against the given target
// player, ordered newest-first. Backs the "Recent admin actions" section
// on the per-player detail view. The index admin_audit_target_idx covers
// both the WHERE clause and the ORDER BY so the LIMIT is hit straight off
// the index.
func (q *Queries) ListAdminAuditForTarget(ctx context.Context, arg ListAdminAuditForTargetParams) ([]ListAdminAuditForTargetRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminAuditForTarget, arg.TargetPlayerID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminAuditForTargetRow
	for rows.Next() {
		var i ListAdminAuditForTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorPlayerID,
			&i.ActorUsername,
			&i.TargetPlayerID,
			&i.Action,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayersByOnboardingState = `-- name: ListPlayersByOnboardingState :many
SELECT
    p.id, p.username, p.email, p.password_hash, p.role, p.created_at, p.username_claimed, p.email_verified_at, p.session_version, p.role_changed_at,
    EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id) AS has_oauth,
    CAST(COALESCE(
        (SELECT pi.provider FROM player_identities pi WHERE pi.player_id = p.id ORDER BY pi.provider LIMIT 1),
        ''
    ) AS TEXT) AS oauth_provider,
    CAST(
        CASE
            WHEN EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id) THEN 'oauth'
            WHEN p.email_verified_at IS NOT NULL THEN 'verified'
            WHEN p.password_hash IS NOT NULL THEN 'unverified'
            ELSE 'anonymous'
        END
    AS TEXT) AS onboarding_state
FROM players p
WHERE
    CAST(?1 AS TEXT) = 'all'
    OR (
        CASE
            WHEN EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id) THEN 'oauth'
            WHEN p.email_verified_at IS NOT NULL THEN 'verified'
            WHEN p.password_hash IS NOT NULL THEN 'unverified'
            ELSE 'anonymous'
        END
    ) = CAST(?1 AS TEXT)
ORDER BY p.created_at DESC, p.id DESC
LIMIT ?3 OFFSET ?2
`

type ListPlayersByOnboardingStateParams struct {
	State     string
	RowOffset int64
	RowLimit  int64
}

type ListPlayersByOnboardingStateRow struct {
	ID              int64
	Username        string
	Email           sql.NullString
	PasswordHash    sql.NullString
	Role            string
	CreatedAt       time.Time
	UsernameClaimed int64
	EmailVerifiedAt sql.NullTime
	SessionVersion  int64
	RoleChangedAt   sql.NullTime
	HasOauth        bool
	OauthProvider   string
	OnboardingState string
}

// Page of players ordered by created_at DESC for the admin list (#450).
// The CASE-derived onboarding_state column is matched against
// sqlc.arg('state'); 'all' (or any unrecognised value) returns every row.
// Branch order matters: each row must match exactly one bucket, so OAuth
// takes precedence over verified (an OAuth-only row may not have a
// password_hash but Google attests the email), then verified, then
// unverified, then anonymous as the fallthrough.
func (q *Queries) ListPlayersByOnboardingState(ctx context.Context, arg ListPlayersByOnboardingStateParams) ([]ListPlayersByOnboardingStateRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayersByOnboardingState, arg.State, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersByOnboardingStateRow
	for rows.Next() {
		var i ListPlayersByOnboardingStateRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UsernameClaimed,
			&i.EmailVerifiedAt,
			&i.SessionVersion,
			&i.RoleChangedAt,
			&i.HasOauth,
			&i.OauthProvider,
			&i.OnboardingState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentFinishedGamesForPlayer = `-- name: ListRecentFinishedGamesForPlayer :many
SELECT
    g.id        AS game_id,
    g.quiz_id   AS quiz_id,
    CAST(q.title AS TEXT) AS quiz_title,
    g.created_at AS created_at
FROM game_participants gp
JOIN games g ON g.id = gp.game_id
JOIN quizzes q ON q.id = g.quiz_id
WHERE gp.player_id = ?1
  AND EXISTS (SELECT 1 FROM questions qe WHERE qe.quiz_id = g.quiz_id)
  AND (SELECT COUNT(*) FROM game_questions gq WHERE gq.game_id = g.id) >=
      (SELECT COUNT(*) FROM questions qc WHERE qc.quiz_id = g.quiz_id)
ORDER BY g.created_at DESC, g.id DESC
LIMIT ?2
`

type ListRecentFinishedGamesForPlayerParams struct {
	PlayerID int64
	RowLimit int64
}

type ListRecentFinishedGamesForPlayerRow struct {
	GameID    string
	QuizID    int64
	QuizTitle string
	CreatedAt time.Time
}

// Newest-first finished games the given player participated in. A
// finished game is one where every quiz question has been issued (mirrors
// the predicate ListPlayerFinishStats uses). Joined with quizzes so the
// detail view can render the quiz title without a second round trip.
// LIMIT is supplied by the caller so this query stays reusable for
// future "last N games" surfaces.
func (q *Queries) ListRecentFinishedGamesForPlayer(ctx context.Context, arg ListRecentFinishedGamesForPlayerParams) ([]ListRecentFinishedGamesForPlayerRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentFinishedGamesForPlayer, arg.PlayerID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentFinishedGamesForPlayerRow
	for rows.Next() {
		var i ListRecentFinishedGamesForPlayerRow
		if err := rows.Scan(
			&i.GameID,
			&i.QuizID,
			&i.QuizTitle,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlayerEmail = `-- name: SetPlayerEmail :execrows
UPDATE players
SET email = ?1,
    email_verified_at = NULL
WHERE id = ?2
`

type SetPlayerEmailParams struct {
	Email sql.NullString
	ID    int64
}

// Updates players.email and clears email_verified_at so a changed address
// must be re-proven. Used by the admin "Set / overwrite email" action;
// the admin then marks the account verified (or triggers a resend) once
// the new address should be treated as proven. Clearing verification keeps
// the onboarding bucket honest: a freshly-set address starts unverified
// rather than inheriting the old address's verified state. A UNIQUE
// collision on players.email surfaces as the driver's constraint error
// which the store wrapper maps to auth.ErrEmailTaken so the handler can
// render a clean banner.
func (q *Queries) SetPlayerEmail(ctx context.Context, arg SetPlayerEmailParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPlayerEmail, arg.Email, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPlayerEmailVerifiedNow = `-- name: SetPlayerEmailVerifiedNow :execrows
UPDATE players
SET email_verified_at = CURRENT_TIMESTAMP
WHERE id = ?1
`

// Stamps email_verified_at to the current time even when the column is
// already populated. Used by the admin "Mark verified" action where the
// intent is to flip an unverified row; the action also rewrites an
// already-verified row to refresh the timestamp. Returns the number of
// affected rows so the wrapper can map "no rows" to ErrPlayerNotFound.
func (q *Queries) SetPlayerEmailVerifiedNow(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPlayerEmailVerifiedNow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
