// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: breaks.sql

package db

import (
	"context"
	"database/sql"
)

const createBreak = `-- name: CreateBreak :one
INSERT INTO breaks (quiz_id, text, position)
VALUES (?, ?, ?)
RETURNING id, quiz_id, position, text, created_at, updated_at
`

type CreateBreakParams struct {
	QuizID   int64
	Text     string
	Position int64
}

func (q *Queries) CreateBreak(ctx context.Context, arg CreateBreakParams) (Break, error) {
	row := q.db.QueryRowContext(ctx, createBreak, arg.QuizID, arg.Text, arg.Position)
	var i Break
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Position,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBreak = `-- name: DeleteBreak :execresult
DELETE FROM breaks
WHERE id = ?
`

func (q *Queries) DeleteBreak(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteBreak, id)
}

const getBreak = `-- name: GetBreak :one
SELECT id, quiz_id, position, text, created_at, updated_at
FROM breaks
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetBreak(ctx context.Context, id int64) (Break, error) {
	row := q.db.QueryRowContext(ctx, getBreak, id)
	var i Break
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Position,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBreaksByQuiz = `-- name: ListBreaksByQuiz :many
SELECT id, quiz_id, position, text, created_at, updated_at
FROM breaks
WHERE quiz_id = ?
ORDER BY position
`

func (q *Queries) ListBreaksByQuiz(ctx context.Context, quizID int64) ([]Break, error) {
	rows, err := q.db.QueryContext(ctx, listBreaksByQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Break
	for rows.Next() {
		var i Break
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Position,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBreak = `-- name: UpdateBreak :execresult
UPDATE breaks
SET text       = ?,
    position   = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateBreakParams struct {
	Text     string
	Position int64
	ID       int64
}

func (q *Queries) UpdateBreak(ctx context.Context, arg UpdateBreakParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBreak, arg.Text, arg.Position, arg.ID)
}

const updateBreakPosition = `-- name: UpdateBreakPosition :execresult
UPDATE breaks
SET position = ?
WHERE id = ?
`

type UpdateBreakPositionParams struct {
	Position int64
	ID       int64
}

// Position-only update used by the per-row up/down reorder buttons on
// the admin quiz view. Mirrors UpdateQuestionPosition so the move
// path can rewrite a single column without touching text or
// updated_at - the admin reorder is not a content edit.
func (q *Queries) UpdateBreakPosition(ctx context.Context, arg UpdateBreakPositionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBreakPosition, arg.Position, arg.ID)
}
