// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: breaks.sql

package db

import (
	"context"
	"database/sql"
)

const createBreak = `-- name: CreateBreak :one
INSERT INTO breaks (quiz_id, text, position)
VALUES (?, ?, ?)
RETURNING id, quiz_id, position, text, created_at, updated_at
`

type CreateBreakParams struct {
	QuizID   int64
	Text     string
	Position int64
}

func (q *Queries) CreateBreak(ctx context.Context, arg CreateBreakParams) (Break, error) {
	row := q.db.QueryRowContext(ctx, createBreak, arg.QuizID, arg.Text, arg.Position)
	var i Break
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Position,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBreak = `-- name: DeleteBreak :execresult
DELETE FROM breaks
WHERE id = ?
`

func (q *Queries) DeleteBreak(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteBreak, id)
}

const getBreak = `-- name: GetBreak :one
SELECT id, quiz_id, position, text, created_at, updated_at
FROM breaks
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetBreak(ctx context.Context, id int64) (Break, error) {
	row := q.db.QueryRowContext(ctx, getBreak, id)
	var i Break
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Position,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBreaksByQuiz = `-- name: ListBreaksByQuiz :many
SELECT id, quiz_id, position, text, created_at, updated_at
FROM breaks
WHERE quiz_id = ?
ORDER BY position
`

func (q *Queries) ListBreaksByQuiz(ctx context.Context, quizID int64) ([]Break, error) {
	rows, err := q.db.QueryContext(ctx, listBreaksByQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Break
	for rows.Next() {
		var i Break
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Position,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBreakPosition = `-- name: NextBreakPosition :one
SELECT CAST(COALESCE(MAX(position), 0) AS INTEGER) AS max_position
FROM breaks
WHERE quiz_id = ?
`

// Returns the highest position in use for the given quiz, or 0 when the
// quiz has no breaks yet. The CAST + COALESCE forces sqlc to type the
// result as int64 instead of interface{} (raw MAX can return NULL).
// Callers add 1 to get the next-position to assign on a new break.
// Mirrors MaxQuestionPosition (#352).
func (q *Queries) NextBreakPosition(ctx context.Context, quizID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextBreakPosition, quizID)
	var max_position int64
	err := row.Scan(&max_position)
	return max_position, err
}

const updateBreak = `-- name: UpdateBreak :execresult
UPDATE breaks
SET text       = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateBreakParams struct {
	Text string
	ID   int64
}

func (q *Queries) UpdateBreak(ctx context.Context, arg UpdateBreakParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateBreak, arg.Text, arg.ID)
}
