// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO game_answers (game_id, player_id, game_question_id, option_id, answered_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, game_id, player_id, game_question_id, option_id, answered_at
`

type CreateAnswerParams struct {
	GameID         string
	PlayerID       int64
	GameQuestionID int64
	OptionID       int64
	AnsweredAt     time.Time
}

// answered_at is passed in from the handler instead of being SQLite's
// CURRENT_TIMESTAMP (#237). The handler accepts the client's tappedAt
// and clamps it to [question.started_at, time.Now()] before this
// INSERT runs, so an honest player on a slow link gets the network
// latency refunded instead of being scored late, and a malicious or
// clock-skewed client can't claim a time outside that window.
func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (GameAnswer, error) {
	row := q.db.QueryRowContext(ctx, createAnswer,
		arg.GameID,
		arg.PlayerID,
		arg.GameQuestionID,
		arg.OptionID,
		arg.AnsweredAt,
	)
	var i GameAnswer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.GameQuestionID,
		&i.OptionID,
		&i.AnsweredAt,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (id, quiz_id)
VALUES (?, ?)
RETURNING id, quiz_id, created_at, started_at
`

type CreateGameParams struct {
	ID     string
	QuizID int64
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame, arg.ID, arg.QuizID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.CreatedAt,
		&i.StartedAt,
	)
	return i, err
}

const createGameQuestion = `-- name: CreateGameQuestion :one
INSERT INTO game_questions (game_id, question_id, started_at, expired_at)
VALUES (?, ?, ?, ?)
RETURNING id, game_id, question_id, started_at, expired_at
`

type CreateGameQuestionParams struct {
	GameID     string
	QuestionID int64
	StartedAt  time.Time
	ExpiredAt  time.Time
}

func (q *Queries) CreateGameQuestion(ctx context.Context, arg CreateGameQuestionParams) (GameQuestion, error) {
	row := q.db.QueryRowContext(ctx, createGameQuestion,
		arg.GameID,
		arg.QuestionID,
		arg.StartedAt,
		arg.ExpiredAt,
	)
	var i GameQuestion
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.QuestionID,
		&i.StartedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO game_participants (game_id, player_id, quiz_id)
VALUES (?, ?, ?)
RETURNING id, game_id, player_id, quiz_id, joined_at
`

type CreateParticipantParams struct {
	GameID   string
	PlayerID int64
	QuizID   sql.NullInt64
}

// quiz_id is denormalised onto game_participants so the UNIQUE INDEX
// on (player_id, quiz_id) can enforce the one-attempt-per-(player, quiz)
// rule at the DB level (#273). Callers populate it from games.quiz_id
// inside the same Service.CreateGame call.
func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (GameParticipant, error) {
	row := q.db.QueryRowContext(ctx, createParticipant, arg.GameID, arg.PlayerID, arg.QuizID)
	var i GameParticipant
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.QuizID,
		&i.JoinedAt,
	)
	return i, err
}

const deleteGameAnswersByGameIDs = `-- name: DeleteGameAnswersByGameIDs :exec
DELETE
FROM game_answers
WHERE game_id IN (/*SLICE:game_ids*/?)
`

// Hard-deletes every game_answers row attached to the given game IDs. Used
// by the player-on-quiz reset flow with the IDs gathered up front by
// ListGameIDsForPlayerOnQuiz.
func (q *Queries) DeleteGameAnswersByGameIDs(ctx context.Context, gameIds []string) error {
	query := deleteGameAnswersByGameIDs
	var queryParams []interface{}
	if len(gameIds) > 0 {
		for _, v := range gameIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:game_ids*/?", strings.Repeat(",?", len(gameIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:game_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteGameAnswersByGameQuestionIDs = `-- name: DeleteGameAnswersByGameQuestionIDs :exec
DELETE
FROM game_answers
WHERE game_question_id IN (/*SLICE:game_question_ids*/?)
`

// Hard-deletes game_answers rows that reference the given game_question
// IDs. Filtering by game_question_id (not game_id) is deliberate: a single
// game can hold answers for many questions, and the question delete must
// only wipe the answers tied to the question being deleted, leaving the
// other questions in the same game untouched.
func (q *Queries) DeleteGameAnswersByGameQuestionIDs(ctx context.Context, gameQuestionIds []int64) error {
	query := deleteGameAnswersByGameQuestionIDs
	var queryParams []interface{}
	if len(gameQuestionIds) > 0 {
		for _, v := range gameQuestionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:game_question_ids*/?", strings.Repeat(",?", len(gameQuestionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:game_question_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteGameParticipantsByGameIDs = `-- name: DeleteGameParticipantsByGameIDs :exec
DELETE
FROM game_participants
WHERE game_id IN (/*SLICE:game_ids*/?)
`

// Hard-deletes every game_participants row attached to the given game IDs.
func (q *Queries) DeleteGameParticipantsByGameIDs(ctx context.Context, gameIds []string) error {
	query := deleteGameParticipantsByGameIDs
	var queryParams []interface{}
	if len(gameIds) > 0 {
		for _, v := range gameIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:game_ids*/?", strings.Repeat(",?", len(gameIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:game_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteGameQuestionsByGameIDs = `-- name: DeleteGameQuestionsByGameIDs :exec
DELETE
FROM game_questions
WHERE game_id IN (/*SLICE:game_ids*/?)
`

// Hard-deletes every game_questions row attached to the given game IDs.
func (q *Queries) DeleteGameQuestionsByGameIDs(ctx context.Context, gameIds []string) error {
	query := deleteGameQuestionsByGameIDs
	var queryParams []interface{}
	if len(gameIds) > 0 {
		for _, v := range gameIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:game_ids*/?", strings.Repeat(",?", len(gameIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:game_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const deleteGameQuestionsByQuestionID = `-- name: DeleteGameQuestionsByQuestionID :exec
DELETE
FROM game_questions
WHERE question_id = ?
`

// Hard-deletes every game_questions row issued for the given question.
// Once the dependent game_answers rows are gone (see
// DeleteGameAnswersByGameQuestionIDs) the FK on game_answers.game_question_id
// no longer blocks, so a single-arg delete by question_id is enough.
func (q *Queries) DeleteGameQuestionsByQuestionID(ctx context.Context, questionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteGameQuestionsByQuestionID, questionID)
	return err
}

const deleteGamesByIDs = `-- name: DeleteGamesByIDs :exec
DELETE
FROM games
WHERE id IN (/*SLICE:ids*/?)
`

// Hard-deletes the given games themselves. Run last; the participant /
// question / answer rows referencing these games have already been removed.
func (q *Queries) DeleteGamesByIDs(ctx context.Context, ids []string) error {
	query := deleteGamesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getGame = `-- name: GetGame :one
SELECT id, quiz_id, created_at, started_at
FROM games
WHERE id = ?
`

func (q *Queries) GetGame(ctx context.Context, id string) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.CreatedAt,
		&i.StartedAt,
	)
	return i, err
}

const getGameByPlayerAndQuiz = `-- name: GetGameByPlayerAndQuiz :one
SELECT g.id, g.quiz_id, g.created_at, g.started_at
FROM games g
         JOIN game_participants gp ON gp.game_id = g.id
WHERE gp.player_id = ?
  AND g.quiz_id = ?
ORDER BY g.created_at DESC
LIMIT 1
`

type GetGameByPlayerAndQuizParams struct {
	PlayerID int64
	QuizID   int64
}

// Returns the most-recent game for the given (player, quiz) pair. Used by the
// player-side resume flow (GET /api/quizzes/{slugID}/my-game) and as a
// defensive backstop in CreateGame so the same player cannot start a second
// attempt at a quiz they have already played.
func (q *Queries) GetGameByPlayerAndQuiz(ctx context.Context, arg GetGameByPlayerAndQuizParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByPlayerAndQuiz, arg.PlayerID, arg.QuizID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.CreatedAt,
		&i.StartedAt,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, username, email, password_hash, role, created_at, username_claimed
FROM players
WHERE id = ?
`

func (q *Queries) GetPlayer(ctx context.Context, id int64) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
	)
	return i, err
}

const listAnswersByGameQuestionID = `-- name: ListAnswersByGameQuestionID :many
SELECT id, game_id, player_id, game_question_id, option_id, answered_at
FROM game_answers
WHERE game_question_id = ?
`

func (q *Queries) ListAnswersByGameQuestionID(ctx context.Context, gameQuestionID int64) ([]GameAnswer, error) {
	rows, err := q.db.QueryContext(ctx, listAnswersByGameQuestionID, gameQuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameAnswer
	for rows.Next() {
		var i GameAnswer
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.GameQuestionID,
			&i.OptionID,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswersForQuizLeaderboard = `-- name: ListAnswersForQuizLeaderboard :many
SELECT ga.player_id        AS player_id,
       p.username           AS username,
       gq.started_at        AS question_started_at,
       gq.expired_at        AS question_expired_at,
       ga.answered_at       AS answered_at,
       o.is_correct         AS is_correct
FROM game_answers ga
         JOIN games g ON g.id = ga.game_id
         JOIN game_questions gq ON gq.id = ga.game_question_id
         JOIN options o ON o.id = ga.option_id
         JOIN players p ON p.id = ga.player_id
WHERE g.quiz_id = ?
  AND (SELECT COUNT(*) FROM game_questions gqc WHERE gqc.game_id = g.id) >=
      (SELECT COUNT(*) FROM questions qc WHERE qc.quiz_id = g.quiz_id)
`

type ListAnswersForQuizLeaderboardRow struct {
	PlayerID          int64
	Username          string
	QuestionStartedAt time.Time
	QuestionExpiredAt time.Time
	AnsweredAt        time.Time
	IsCorrect         bool
}

// Selects the per-answer scoring inputs for every completed game of the
// given quiz. A game counts as complete when every quiz question has
// been issued, i.e. the count of game_questions rows for the game has
// caught up with the count of questions on the quiz. Partial games
// (where the player walked away mid-quiz) are filtered out so the
// leaderboard only compares finishers. The one-attempt-per-(player,
// quiz) constraint enforced by #145 keeps a player from showing up more
// than once.
func (q *Queries) ListAnswersForQuizLeaderboard(ctx context.Context, quizID int64) ([]ListAnswersForQuizLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnswersForQuizLeaderboard, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnswersForQuizLeaderboardRow
	for rows.Next() {
		var i ListAnswersForQuizLeaderboardRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.Username,
			&i.QuestionStartedAt,
			&i.QuestionExpiredAt,
			&i.AnsweredAt,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameIDsForPlayerOnQuiz = `-- name: ListGameIDsForPlayerOnQuiz :many
SELECT g.id
FROM games g
         JOIN game_participants gp ON gp.game_id = g.id
WHERE gp.player_id = ?
  AND g.quiz_id = ?
`

type ListGameIDsForPlayerOnQuizParams struct {
	PlayerID int64
	QuizID   int64
}

// Lists every game ID the player has on the given quiz. The reset flow
// collects these once at the start of the in-Go transaction and feeds them
// into the dependent deletes; doing it that way avoids a delete-order
// problem where each subsequent statement's subquery would see fewer rows
// as we drained the dependency tables.
func (q *Queries) ListGameIDsForPlayerOnQuiz(ctx context.Context, arg ListGameIDsForPlayerOnQuizParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGameIDsForPlayerOnQuiz, arg.PlayerID, arg.QuizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameIDsForQuiz = `-- name: ListGameIDsForQuiz :many
SELECT id
FROM games
WHERE quiz_id = ?
`

// Lists every game ID for the quiz, regardless of player. Used by the
// quiz delete flow so the in-Go transaction can drop dependent
// game_answers / game_questions / game_participants / games rows before
// the quiz row itself is deleted (questions and options cascade from
// the quiz, but the game_* tables do not).
func (q *Queries) ListGameIDsForQuiz(ctx context.Context, quizID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGameIDsForQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameQuestionIDsForQuestion = `-- name: ListGameQuestionIDsForQuestion :many
SELECT id
FROM game_questions
WHERE question_id = ?
`

// Lists every game_questions.id where the given question has been issued.
// Used by the question delete flow so the in-Go transaction can drop
// dependent game_answers rows scoped to THIS question's game_question rows
// before deleting the game_questions and the question itself. Snapshotted
// up front so subsequent deletes do not see a moving target as rows drain.
func (q *Queries) ListGameQuestionIDsForQuestion(ctx context.Context, questionID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listGameQuestionIDsForQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameQuestionsByGameID = `-- name: ListGameQuestionsByGameID :many
SELECT id, game_id, question_id, started_at, expired_at
FROM game_questions
WHERE game_id = ?
ORDER BY id
`

// Ordered by id so callers can rely on the last element being the
// most recently issued question. GetNextQuestion's resume path needs
// that to decide whether to return the in-flight question or advance.
func (q *Queries) ListGameQuestionsByGameID(ctx context.Context, gameID string) ([]GameQuestion, error) {
	rows, err := q.db.QueryContext(ctx, listGameQuestionsByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameQuestion
	for rows.Next() {
		var i GameQuestion
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.QuestionID,
			&i.StartedAt,
			&i.ExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByGameID = `-- name: ListParticipantsByGameID :many
SELECT id, game_id, player_id, quiz_id, joined_at
FROM game_participants
WHERE game_id = ?
`

func (q *Queries) ListParticipantsByGameID(ctx context.Context, gameID string) ([]GameParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listParticipantsByGameID, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameParticipant
	for rows.Next() {
		var i GameParticipant
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.QuizID,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizIDsForPlayer = `-- name: ListQuizIDsForPlayer :many
SELECT DISTINCT g.quiz_id
FROM game_answers ga
         JOIN games g ON g.id = ga.game_id
WHERE ga.player_id = ?
`

// Lists distinct quiz IDs where the given player has at least one
// recorded answer. The claim-name flow uses this to know which
// leaderboard SSE streams to repaint when a player updates their
// display name: every quiz they appear on gets a fresh snapshot
// pushed to its subscribers. Filtering on game_answers rather than
// game_participants means we skip quizzes the player joined but
// never actually answered on, which would not show up on the
// leaderboard anyway.
func (q *Queries) ListQuizIDsForPlayer(ctx context.Context, playerID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listQuizIDsForPlayer, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var quiz_id int64
		if err := rows.Scan(&quiz_id); err != nil {
			return nil, err
		}
		items = append(items, quiz_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startGame = `-- name: StartGame :execresult
UPDATE games
SET started_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) StartGame(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, startGame, id)
}
