// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: home.sql

package db

import (
	"context"
	"time"
)

const listMostActivePlayers = `-- name: ListMostActivePlayers :many
SELECT p.id              AS id,
       p.display_name        AS display_name,
       COUNT(DISTINCT g.id) AS finished_count
FROM players p
JOIN game_participants gp ON gp.player_id = p.id
JOIN games g ON g.id = gp.game_id
WHERE g.created_at >= datetime('now', '-30 days')
  AND p.display_name_claimed = 1
  AND EXISTS (SELECT 1 FROM questions qe WHERE qe.quiz_id = g.quiz_id)
  AND (SELECT COUNT(*) FROM game_questions gq WHERE gq.game_id = g.id) >=
      (SELECT COUNT(*) FROM questions qc WHERE qc.quiz_id = g.quiz_id)
GROUP BY p.id
ORDER BY finished_count DESC, p.display_name ASC
`

type ListMostActivePlayersRow struct {
	ID            int64
	DisplayName   string
	FinishedCount int64
}

// Returns the players with the most finished games in the last 30
// days, descending. The finished definition matches
// ListPopularQuizzes and ListAnswersForQuizLeaderboard, and the
// 30-day window matches ListPopularQuizzes -- without it the home
// page's two leaderboards disagreed on what "recently active" meant
// and a long-dormant player could outrank a current one (#355).
//
// Anonymous (auto-petname) players are filtered out via
// display_name_claimed = 1 so the public list only shows names a player
// deliberately picked. The start-page leaderboard would otherwise be
// cluttered with throwaway "happy-banana-xyz" entries from one-shot
// visitors.
//
// The EXISTS gate on questions excludes empty-quiz "plays" for the
// same reason as ListPopularQuizzes above (#275).
//
// LIMIT applied by the caller; see ListPopularQuizzes above for why.
func (q *Queries) ListMostActivePlayers(ctx context.Context) ([]ListMostActivePlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMostActivePlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMostActivePlayersRow
	for rows.Next() {
		var i ListMostActivePlayersRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.FinishedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewestQuizzes = `-- name: ListNewestQuizzes :many
SELECT q.id          AS id,
       q.title       AS title,
       q.slug        AS slug,
       q.description AS description,
       q.created_at  AS created_at,
       (SELECT COUNT(*) FROM questions qc WHERE qc.quiz_id = q.id) AS question_count
FROM quizzes q
WHERE q.visibility = 'public'
  AND EXISTS (SELECT 1 FROM questions qe WHERE qe.quiz_id = q.id)
ORDER BY q.created_at DESC, q.id DESC
`

type ListNewestQuizzesRow struct {
	ID            int64
	Title         string
	Slug          string
	Description   string
	CreatedAt     time.Time
	QuestionCount int64
}

// Returns the most-recently-created public quizzes, newest first. Backs
// the "Newest" tab on the start page so freshly-authored quizzes are
// discoverable before they accumulate enough plays to reach the popular
// list.
//
// Visibility gate (#103): only quizzes the public can play surface on
// the start page. Unlisted is link-only; private requires a logged-in
// player, neither of which fits this anonymous list.
//
// The EXISTS gate on questions excludes quizzes with zero questions:
// they cannot be played, so they have no business on a "pick a quiz"
// list (#275). Same exclusion ListPopularQuizzes applies.
//
// No LIMIT in SQL: sqlc's SQLite parser truncates the surrounding
// statement in multi-query files when a LIMIT clause is present, so the
// caller slices the result. See ListPopularQuizzes above.
func (q *Queries) ListNewestQuizzes(ctx context.Context) ([]ListNewestQuizzesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNewestQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewestQuizzesRow
	for rows.Next() {
		var i ListNewestQuizzesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopularQuizzes = `-- name: ListPopularQuizzes :many
SELECT q.id          AS id,
       q.title       AS title,
       q.slug        AS slug,
       q.description AS description,
       q.updated_at  AS updated_at,
       COUNT(DISTINCT g.id) AS play_count
FROM quizzes q
JOIN games g ON g.quiz_id = q.id
WHERE g.created_at >= datetime('now', '-30 days')
  AND q.visibility = 'public'
  AND EXISTS (SELECT 1 FROM questions qe WHERE qe.quiz_id = q.id)
  AND (SELECT COUNT(*) FROM game_questions gq WHERE gq.game_id = g.id) >=
      (SELECT COUNT(*) FROM questions qc WHERE qc.quiz_id = q.id)
GROUP BY q.id
ORDER BY play_count DESC, q.updated_at DESC
`

type ListPopularQuizzesRow struct {
	ID          int64
	Title       string
	Slug        string
	Description string
	UpdatedAt   time.Time
	PlayCount   int64
}

// Returns the most-played quizzes over the last 30 days, scored by number of
// finished games. A game counts as finished when every quiz question has
// been issued, i.e. the count of game_questions rows for the game has
// caught up with the count of questions on the quiz. Same finisher
// condition as ListAnswersForQuizLeaderboard so the home page and the
// per-quiz leaderboard agree on what "played" means.
//
// The EXISTS gate on questions excludes quizzes with zero questions:
// without it the finisher predicate above degenerates to 0 >= 0 and
// promotes empty quizzes to the popular list (#275). It also keeps
// the home query consistent with game.Game.IsCompleted, which only
// treats a game as finished when the quiz has at least one question.
//
// No LIMIT in SQL: sqlc's SQLite parser truncates the surrounding
// statement in multi-query files when a LIMIT clause is present, so the
// caller slices the result. Real-world traffic is tiny enough that this
// is fine.
//
// Visibility gate (#103): only quizzes the public can play surface on
// the start page. Unlisted is link-only; private requires a logged-in
// player, neither of which fits this anonymous list.
func (q *Queries) ListPopularQuizzes(ctx context.Context) ([]ListPopularQuizzesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPopularQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPopularQuizzesRow
	for rows.Next() {
		var i ListPopularQuizzesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.UpdatedAt,
			&i.PlayCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
