// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const consumeInvite = `-- name: ConsumeInvite :one
UPDATE invites
SET status = 'accepted',
    accepted_at = ?1
WHERE token_hash = ?2
  AND status = 'pending'
  AND expires_at > ?3
RETURNING id
`

type ConsumeInviteParams struct {
	AcceptedAt sql.NullTime
	TokenHash  string
	Now        time.Time
}

// Atomic single-use consume: succeeds only when the row is still pending and
// not expired. Marks the invite accepted and stamps accepted_at in one
// statement so two concurrent accepts cannot both win. Returns the id so the
// caller can confirm exactly one row moved. sql.ErrNoRows means the invite was
// already accepted, revoked, expired, or never existed.
func (q *Queries) ConsumeInvite(ctx context.Context, arg ConsumeInviteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, consumeInvite, arg.AcceptedAt, arg.TokenHash, arg.Now)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO invites (email, invited_by_player_id, token_hash, note, expires_at)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type CreateInviteParams struct {
	Email             string
	InvitedByPlayerID sql.NullInt64
	TokenHash         string
	Note              sql.NullString
	ExpiresAt         time.Time
}

// Stores the sha256 hash of a freshly minted invite token (#318). The raw
// token only exists on the way out the door in the email; a DB leak should
// not be replayable against POST /accept-invite. invited_by_player_id is the
// audit actor (the admin who sent the invite); it is nullable so a deleted
// admin leaves the invite intact via ON DELETE SET NULL. note is an optional
// free-text reminder the admin can attach.
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.db.ExecContext(ctx, createInvite,
		arg.Email,
		arg.InvitedByPlayerID,
		arg.TokenHash,
		arg.Note,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredInvites = `-- name: DeleteExpiredInvites :exec
DELETE FROM invites
WHERE status = 'pending'
  AND expires_at <= ?1
`

// Housekeeping for the startup + periodic sweep. Drops every still-pending
// invite whose link has expired so the table does not grow without bound.
// Accepted and revoked rows are kept as an audit trail. The caller passes
// 'now' so the comparison runs in the driver's time.Time.String() text encoding.
func (q *Queries) DeleteExpiredInvites(ctx context.Context, now time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredInvites, now)
	return err
}

const getLiveInviteByTokenHash = `-- name: GetLiveInviteByTokenHash :one
SELECT id, email, invited_by_player_id
FROM invites
WHERE token_hash = ?1
  AND status = 'pending'
  AND expires_at > ?2
LIMIT 1
`

type GetLiveInviteByTokenHashParams struct {
	TokenHash string
	Now       time.Time
}

type GetLiveInviteByTokenHashRow struct {
	ID                int64
	Email             string
	InvitedByPlayerID sql.NullInt64
}

// Look up an invite by token hash, but only when it is still acceptable:
// pending (not accepted, not revoked) and not expired. Used by the
// GET /accept-invite preflight to short-circuit the form render for dead
// links, and re-checked by POST. The caller passes 'now' so both sides of the
// expires_at comparison use the driver's time.Time.String() text encoding
// (mixing time.Time with CURRENT_TIMESTAMP produces strings of different
// lengths and the lexicographic comparison silently lies). sql.ErrNoRows means consumed,
// revoked, expired, or never existed; the caller maps that to a single
// user-facing "invite link is no longer valid" response.
func (q *Queries) GetLiveInviteByTokenHash(ctx context.Context, arg GetLiveInviteByTokenHashParams) (GetLiveInviteByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getLiveInviteByTokenHash, arg.TokenHash, arg.Now)
	var i GetLiveInviteByTokenHashRow
	err := row.Scan(&i.ID, &i.Email, &i.InvitedByPlayerID)
	return i, err
}

const listPendingInvites = `-- name: ListPendingInvites :many
SELECT
    invites.id,
    invites.email,
    invites.invited_by_player_id,
    players.display_name AS inviter_display_name,
    invites.created_at,
    invites.expires_at
FROM invites
LEFT JOIN players ON players.id = invites.invited_by_player_id
WHERE invites.status = 'pending'
ORDER BY invites.created_at DESC, invites.id DESC
`

type ListPendingInvitesRow struct {
	ID                 int64
	Email              string
	InvitedByPlayerID  sql.NullInt64
	InviterDisplayName sql.NullString
	CreatedAt          time.Time
	ExpiresAt          time.Time
}

// Lists every still-pending invite for the admin management view (#318),
// newest first. LEFT JOIN players surfaces the inviter's display_name for the
// "invited by X" column; inviter_display_name is NULL when the invite carries
// no actor (invited_by_player_id NULL) or the inviting admin's row has since
// been deleted (ON DELETE SET NULL). Includes still-expired-but-not-swept
// rows so the list matches what the sweep has actually pruned; the template
// surfaces expires_at so the admin can tell a stale link apart.
func (q *Queries) ListPendingInvites(ctx context.Context) ([]ListPendingInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInvitesRow
	for rows.Next() {
		var i ListPendingInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.InvitedByPlayerID,
			&i.InviterDisplayName,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :one
UPDATE invites
SET status = 'revoked'
WHERE id = ?1
  AND status = 'pending'
RETURNING id
`

// Marks a pending invite revoked so its link stops resolving (#318). Only a
// pending row moves; an already-accepted, already-revoked, or non-existent id
// matches nothing and returns sql.ErrNoRows, which the handler maps to a clear
// "no longer pending" flash rather than a 500. RETURNING id confirms exactly
// one row changed.
func (q *Queries) RevokeInvite(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, revokeInvite, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const rotateInviteToken = `-- name: RotateInviteToken :one
UPDATE invites
SET token_hash = ?1,
    expires_at = ?2
WHERE id = ?3
  AND status = 'pending'
RETURNING email
`

type RotateInviteTokenParams struct {
	TokenHash string
	ExpiresAt time.Time
	ID        int64
}

// Resend path (#318): overwrites a pending invite's token hash and expiry with
// a freshly minted pair. The new hash makes the new link live; the old hash no
// longer matches any row, so the previously emailed link is dead (UNIQUE
// token_hash means the new value cannot collide). Only a pending row moves; a
// non-pending or non-existent id returns sql.ErrNoRows. RETURNING email lets
// the handler dispatch the new link without a second read.
func (q *Queries) RotateInviteToken(ctx context.Context, arg RotateInviteTokenParams) (string, error) {
	row := q.db.QueryRowContext(ctx, rotateInviteToken, arg.TokenHash, arg.ExpiresAt, arg.ID)
	var email string
	err := row.Scan(&email)
	return email, err
}
