// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"
	"database/sql"
)

const countMediaByQuizAndType = `-- name: CountMediaByQuizAndType :one
SELECT count(*) AS count
FROM media
WHERE quiz_id = ?1
  AND type = ?2
  AND ready = 1
`

type CountMediaByQuizAndTypeParams struct {
	QuizID int64
	Type   string
}

// Returns the number of ready media rows of one type for a quiz, so each upload
// route enforces a per-type library ceiling: an image upload counts only images
// and an audio upload counts only audio, so the two kinds never draw down each
// other's cap (#1059). Not-ready rows (in-flight or stranded uploads) are
// excluded so the count reflects only finished library rows, matching what
// ListMediaByQuiz shows (#992).
func (q *Queries) CountMediaByQuizAndType(ctx context.Context, arg CountMediaByQuizAndTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaByQuizAndType, arg.QuizID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    quiz_id, type, mime, path, thumb_path,
    width, height, size_bytes, sha256, duration_ms, description, original_filename,
    created_by_player_id, ready
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    0
)
RETURNING id, quiz_id, type, mime, path, thumb_path, width, height, size_bytes, sha256, created_by_player_id, created_at, ready, duration_ms, description, original_filename
`

type CreateMediaParams struct {
	QuizID            int64
	Type              string
	Mime              string
	Path              string
	ThumbPath         sql.NullString
	Width             sql.NullInt64
	Height            sql.NullInt64
	SizeBytes         int64
	Sha256            string
	DurationMs        sql.NullInt64
	Description       string
	OriginalFilename  string
	CreatedByPlayerID int64
}

// Inserts a per-quiz media row (#936) and returns it with the assigned id and
// created_at. The bytes already live on disk under the per-quiz directory; this
// row records the relative path plus the metadata the pipeline computed
// (dimensions, byte size, sha256 of the stored image). thumb_path is nullable
// because a non-image type (later) may not pre-generate a thumbnail.
//
// The row is inserted not-ready (ready = 0): a later MarkMediaReady flips it
// once the files are written and the paths recorded (#992). Until then the
// library list hides it, so an upload cancelled before the flip never appears,
// and the not-ready sweep drops the stranded row plus its files.
func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.QuizID,
		arg.Type,
		arg.Mime,
		arg.Path,
		arg.ThumbPath,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.Sha256,
		arg.DurationMs,
		arg.Description,
		arg.OriginalFilename,
		arg.CreatedByPlayerID,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Type,
		&i.Mime,
		&i.Path,
		&i.ThumbPath,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedByPlayerID,
		&i.CreatedAt,
		&i.Ready,
		&i.DurationMs,
		&i.Description,
		&i.OriginalFilename,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :execresult
DELETE FROM media
WHERE id = ?1
`

// Deletes a media row by id. The caller checks RowsAffected to distinguish a
// real delete from a no-op (missing id), and unlinks the files separately
// (best-effort) so a desync between row and file is reconciled by the cleanup
// tooling rather than failing the delete.
func (q *Queries) DeleteMedia(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteMedia, id)
}

const getMedia = `-- name: GetMedia :one
SELECT id, quiz_id, type, mime, path, thumb_path, width, height, size_bytes, sha256, created_by_player_id, created_at, ready, duration_ms, description, original_filename
FROM media
WHERE id = ?1
`

// Returns a single media row by id. sql.ErrNoRows means the id does not name a
// row; the store maps that to media.ErrMediaNotFound.
func (q *Queries) GetMedia(ctx context.Context, id int64) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Type,
		&i.Mime,
		&i.Path,
		&i.ThumbPath,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedByPlayerID,
		&i.CreatedAt,
		&i.Ready,
		&i.DurationMs,
		&i.Description,
		&i.OriginalFilename,
	)
	return i, err
}

const listMediaByQuiz = `-- name: ListMediaByQuiz :many
SELECT id, quiz_id, type, mime, path, thumb_path, width, height, size_bytes, sha256, created_by_player_id, created_at, ready, duration_ms, description, original_filename
FROM media
WHERE quiz_id = ?1
  AND ready = 1
ORDER BY created_at DESC, id DESC
`

// Returns every ready media row scoped to a quiz, newest first, for the
// per-quiz library grid. Ordered by id DESC as a stable tiebreaker since
// created_at has second resolution and a bulk upload can share a timestamp.
// ready = 1 hides a row whose upload was cancelled after the paths committed
// but before the ready flip, so a cancelled upload never shows in the library
// (#992).
func (q *Queries) ListMediaByQuiz(ctx context.Context, quizID int64) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Type,
			&i.Mime,
			&i.Path,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedByPlayerID,
			&i.CreatedAt,
			&i.Ready,
			&i.DurationMs,
			&i.Description,
			&i.OriginalFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleNotReadyMedia = `-- name: ListStaleNotReadyMedia :many
SELECT id, path, thumb_path
FROM media
WHERE ready = 0
  AND created_at < datetime('now', '-' || CAST(?1 AS INTEGER) || ' seconds')
ORDER BY id
`

type ListStaleNotReadyMediaRow struct {
	ID        int64
	Path      string
	ThumbPath sql.NullString
}

// Lists not-ready media rows older than the cutoff for the in-flight-upload
// sweep (#992). A row stays not-ready only between CreateMedia and the final
// MarkMediaReady; the sole way one lingers past that brief window is a request
// whose context was cancelled mid-upload, leaving a committed-but-hidden row.
// The cutoff is computed in SQL (datetime('now', '-<seconds> seconds')) so both
// sides of the comparison are SQLite text in the CURRENT_TIMESTAMP encoding
// rows are minted with, not a cross-format Go time.Time comparison. path and
// thumb_path come back so the sweep can unlink the files before deleting the
// row.
func (q *Queries) ListStaleNotReadyMedia(ctx context.Context, seconds int64) ([]ListStaleNotReadyMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaleNotReadyMedia, seconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleNotReadyMediaRow
	for rows.Next() {
		var i ListStaleNotReadyMediaRow
		if err := rows.Scan(&i.ID, &i.Path, &i.ThumbPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMediaReady = `-- name: MarkMediaReady :execresult
UPDATE media
SET ready = 1
WHERE id = ?1
`

// Flips a media row ready (#992): the final step of the two-phase upload, run
// only after the files are on disk and the paths recorded. Until this lands the
// library list hides the row, so a cancel before this flip leaves nothing the
// host can see. The caller checks RowsAffected to confirm the row still exists.
func (q *Queries) MarkMediaReady(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, markMediaReady, id)
}

const updateMediaDescription = `-- name: UpdateMediaDescription :execresult
UPDATE media
SET description = ?1
WHERE id = ?2
`

type UpdateMediaDescriptionParams struct {
	Description string
	ID          int64
}

// Sets the host-supplied description label of a media row (#1072). The caller
// checks RowsAffected to confirm the row still exists (a missing id maps to
// media.ErrMediaNotFound).
func (q *Queries) UpdateMediaDescription(ctx context.Context, arg UpdateMediaDescriptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateMediaDescription, arg.Description, arg.ID)
}

const updateMediaPaths = `-- name: UpdateMediaPaths :execresult
UPDATE media
SET path = ?1,
    thumb_path = ?2
WHERE id = ?3
`

type UpdateMediaPathsParams struct {
	Path      string
	ThumbPath sql.NullString
	ID        int64
}

// Sets the on-disk paths of a media row after the files are written. The row is
// inserted first to assign the id the filenames embed (<quizID>/<id>.jpg), so
// the paths cannot be known at insert time; this second write fills them in.
// The caller checks RowsAffected to confirm the row still exists.
func (q *Queries) UpdateMediaPaths(ctx context.Context, arg UpdateMediaPathsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateMediaPaths, arg.Path, arg.ThumbPath, arg.ID)
}
