// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"
	"database/sql"
)

const countMediaByQuiz = `-- name: CountMediaByQuiz :one
SELECT count(*) AS count
FROM media
WHERE quiz_id = ?1
`

// Returns the number of media rows for a quiz, for an upload-count guard and
// the library header.
func (q *Queries) CountMediaByQuiz(ctx context.Context, quizID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaByQuiz, quizID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
    quiz_id, type, mime, path, thumb_path,
    width, height, size_bytes, sha256, created_by_player_id
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
)
RETURNING id, quiz_id, type, mime, path, thumb_path, width, height, size_bytes, sha256, created_by_player_id, created_at
`

type CreateMediaParams struct {
	QuizID            int64
	Type              string
	Mime              string
	Path              string
	ThumbPath         sql.NullString
	Width             sql.NullInt64
	Height            sql.NullInt64
	SizeBytes         int64
	Sha256            string
	CreatedByPlayerID int64
}

// Inserts a per-quiz media row (#936) and returns it with the assigned id and
// created_at. The bytes already live on disk under the per-quiz directory; this
// row records the relative path plus the metadata the pipeline computed
// (dimensions, byte size, sha256 of the stored image). thumb_path is nullable
// because a non-image type (later) may not pre-generate a thumbnail.
func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.QuizID,
		arg.Type,
		arg.Mime,
		arg.Path,
		arg.ThumbPath,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.Sha256,
		arg.CreatedByPlayerID,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Type,
		&i.Mime,
		&i.Path,
		&i.ThumbPath,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedByPlayerID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :execresult
DELETE FROM media
WHERE id = ?1
`

// Deletes a media row by id. The caller checks RowsAffected to distinguish a
// real delete from a no-op (missing id), and unlinks the files separately
// (best-effort) so a desync between row and file is reconciled by the cleanup
// tooling rather than failing the delete.
func (q *Queries) DeleteMedia(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteMedia, id)
}

const getMedia = `-- name: GetMedia :one
SELECT id, quiz_id, type, mime, path, thumb_path, width, height, size_bytes, sha256, created_by_player_id, created_at
FROM media
WHERE id = ?1
`

// Returns a single media row by id. sql.ErrNoRows means the id does not name a
// row; the store maps that to media.ErrMediaNotFound.
func (q *Queries) GetMedia(ctx context.Context, id int64) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Type,
		&i.Mime,
		&i.Path,
		&i.ThumbPath,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedByPlayerID,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaByQuiz = `-- name: ListMediaByQuiz :many
SELECT id, quiz_id, type, mime, path, thumb_path, width, height, size_bytes, sha256, created_by_player_id, created_at
FROM media
WHERE quiz_id = ?1
ORDER BY created_at DESC, id DESC
`

// Returns every media row scoped to a quiz, newest first, for the per-quiz
// library grid. Ordered by id DESC as a stable tiebreaker since created_at has
// second resolution and a bulk upload can share a timestamp.
func (q *Queries) ListMediaByQuiz(ctx context.Context, quizID int64) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Type,
			&i.Mime,
			&i.Path,
			&i.ThumbPath,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedByPlayerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaPaths = `-- name: UpdateMediaPaths :execresult
UPDATE media
SET path = ?1,
    thumb_path = ?2
WHERE id = ?3
`

type UpdateMediaPathsParams struct {
	Path      string
	ThumbPath sql.NullString
	ID        int64
}

// Sets the on-disk paths of a media row after the files are written. The row is
// inserted first to assign the id the filenames embed (<quizID>/<id>.jpg), so
// the paths cannot be known at insert time; this second write fills them in.
// The caller checks RowsAffected to confirm the row still exists.
func (q *Queries) UpdateMediaPaths(ctx context.Context, arg UpdateMediaPathsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateMediaPaths, arg.Path, arg.ThumbPath, arg.ID)
}
