// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AdminAudit struct {
	ID             int64
	ActorPlayerID  sql.NullInt64
	TargetPlayerID int64
	Action         string
	Payload        string
	CreatedAt      time.Time
}

type EmailVerifyToken struct {
	TokenHash    string
	PlayerID     int64
	CreatedAt    time.Time
	ExpiresAt    time.Time
	ConsumedAt   sql.NullTime
	PendingEmail sql.NullString
}

type Game struct {
	ID        string
	QuizID    int64
	CreatedAt time.Time
	StartedAt sql.NullTime
}

type GameAnswer struct {
	ID             int64
	GameID         string
	PlayerID       int64
	GameQuestionID int64
	OptionID       int64
	AnsweredAt     time.Time
}

type GameParticipant struct {
	ID       int64
	GameID   string
	PlayerID int64
	QuizID   int64
	JoinedAt time.Time
}

type GameQuestion struct {
	ID         int64
	GameID     string
	QuestionID int64
	StartedAt  time.Time
	ExpiredAt  time.Time
}

type GameSeenRound struct {
	GameID  string
	RoundID int64
	Phase   string
	SeenAt  time.Time
}

type Invite struct {
	ID                int64
	Email             string
	InvitedByPlayerID sql.NullInt64
	TokenHash         string
	Status            string
	Note              sql.NullString
	ExpiresAt         time.Time
	CreatedAt         time.Time
	AcceptedAt        sql.NullTime
}

type Option struct {
	ID         int64
	QuestionID int64
	Text       string
	IsCorrect  bool
}

type PasswordResetToken struct {
	TokenHash  string
	PlayerID   int64
	CreatedAt  time.Time
	ExpiresAt  time.Time
	ConsumedAt sql.NullTime
}

type Player struct {
	ID                 int64
	DisplayName        string
	Email              sql.NullString
	PasswordHash       sql.NullString
	Role               string
	CreatedAt          time.Time
	DisplayNameClaimed int64
	EmailVerifiedAt    sql.NullTime
	SessionVersion     int64
	RoleChangedAt      sql.NullTime
}

type PlayerIdentity struct {
	ID        int64
	PlayerID  int64
	Provider  string
	Subject   string
	CreatedAt time.Time
}

type Question struct {
	ID               int64
	QuizID           int64
	RoundID          int64
	Text             string
	Position         int64
	ImageUrl         string
	TimeLimitSeconds sql.NullInt64
}

type Quiz struct {
	ID                int64
	Title             string
	Slug              string
	Description       string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	CreatedByPlayerID int64
	TimeLimitSeconds  int64
	Visibility        string
	Mode              string
}

type Round struct {
	ID        int64
	QuizID    int64
	Position  int64
	Title     string
	Summary   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	ID                string
	QuizID            int64
	HostPlayerID      int64
	JoinCode          string
	Phase             string
	GameSeq           int64
	CurrentRoundID    sql.NullInt64
	CurrentQuestionID sql.NullInt64
	QuestionStartedAt sql.NullTime
	QuestionExpiresAt sql.NullTime
	CreatedAt         time.Time
	StartedAt         sql.NullTime
	FinishedAt        sql.NullTime
	HostLastSeenAt    sql.NullTime
	StartAt           sql.NullTime
}

type SessionAnswer struct {
	ID         int64
	SessionID  string
	QuestionID int64
	PlayerID   int64
	OptionID   int64
	AnsweredAt time.Time
	Score      sql.NullInt64
	GameSeq    int64
}

type SessionPlayer struct {
	ID         int64
	SessionID  string
	PlayerID   int64
	IsReady    int64
	JoinedAt   time.Time
	LastSeenAt time.Time
	LeftAt     sql.NullTime
}
