// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Option struct {
	ID         int64
	QuestionID int64
	Text       string
	IsCorrect  bool
}

type Player struct {
	ID        int64
	Username  string
	Email     string
	CreatedAt time.Time
}

type Question struct {
	ID       int64
	QuizID   int64
	Text     string
	Position int64
}

type Quiz struct {
	ID          int64
	Title       string
	Slug        string
	Description string
	CreatedAt   time.Time
}
