// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Game struct {
	ID        string
	QuizID    int64
	CreatedAt time.Time
	StartedAt sql.NullTime
}

type GameAnswer struct {
	ID             int64
	GameID         string
	PlayerID       int64
	GameQuestionID int64
	OptionID       int64
	AnsweredAt     time.Time
}

type GameParticipant struct {
	ID       int64
	GameID   string
	PlayerID int64
	JoinedAt time.Time
}

type GameQuestion struct {
	ID         int64
	GameID     string
	QuestionID int64
	StartedAt  time.Time
	ExpiredAt  time.Time
}

type Option struct {
	ID         int64
	QuestionID int64
	Text       string
	IsCorrect  bool
}

type Player struct {
	ID        int64
	Username  string
	Email     string
	CreatedAt time.Time
}

type Question struct {
	ID       int64
	QuizID   int64
	Text     string
	Position int64
}

type Quiz struct {
	ID          int64
	Title       string
	Slug        string
	Description string
	CreatedAt   time.Time
}
