// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const claimPlayer = `-- name: ClaimPlayer :one
UPDATE players
SET username = ?1,
    password_hash = ?2,
    role = CASE
        WHEN CAST(?3 AS TEXT) = 'admin' THEN 'admin'
        WHEN NOT EXISTS (
            SELECT 1 FROM players p
            WHERE p.password_hash IS NOT NULL
               OR EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id)
        ) THEN 'admin'
        ELSE 'player'
    END,
    username_claimed = 1
WHERE players.id = ?4
  AND players.password_hash IS NULL
RETURNING id, username, email, password_hash, role, created_at, username_claimed
`

type ClaimPlayerParams struct {
	Username      string
	PasswordHash  sql.NullString
	RequestedRole string
	ID            int64
}

// Upgrades an anonymous (password_hash IS NULL) row in place so that an
// already-playing visitor keeps their player_id when they sign up. The
// WHERE password_hash IS NULL guard makes this idempotent: a second claim
// attempt against an already-credentialled row returns no rows, which the
// store maps to ErrPlayerAlreadyClaimed.
//
// The role CASE mirrors CreatePlayerWithCredentials so the "first
// credentialled registrant becomes admin" rule still triggers when the
// very first sign-up happens through the claim path (i.e. the registrant
// played anonymously first). The subquery aliases the players table as pp
// so the column reference in the WHERE is unambiguous against the row
// being updated. The credentialled-player check covers both password and
// OAuth identity so a deployment that bootstrapped its admin via Google
// doesn't auto-promote later password claimers.
//
// username_claimed is set to 1 because the visitor is explicitly choosing
// their username via the register form. This is the register-after-playing
// path: the row now represents a player who picked their own name, so it
// must look identical to a CreatePlayerWithCredentials row to downstream
// callers.
func (q *Queries) ClaimPlayer(ctx context.Context, arg ClaimPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, claimPlayer,
		arg.Username,
		arg.PasswordHash,
		arg.RequestedRole,
		arg.ID,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
	)
	return i, err
}

const claimPlayerForOAuth = `-- name: ClaimPlayerForOAuth :one
UPDATE players
SET email = ?1,
    role = CASE
        WHEN NOT EXISTS (
            SELECT 1 FROM players p
            WHERE p.password_hash IS NOT NULL
               OR EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id)
        ) THEN 'admin'
        ELSE 'player'
    END
WHERE players.id = ?2
  AND players.password_hash IS NULL
  AND players.email IS NULL
RETURNING id, username, email, password_hash, role, created_at, username_claimed
`

type ClaimPlayerForOAuthParams struct {
	Email sql.NullString
	ID    int64
}

// Upgrades a fully anonymous players row (no password_hash, no email)
// in place by attaching the OAuth-verified email. Lets a visitor who
// played anonymously keep their existing player_id (and therefore
// their game history and any custom username) when they sign in with
// Google for the first time. The username is left untouched: the
// visitor's auto-petname or PATCH-claimed name carries through onto
// the OAuth-linked row.
//
// The role CASE mirrors CreatePlayerFromOAuth so the first OAuth-only
// registrant still earns the admin promotion atomically. ELSE 'player'
// matches CreateAnonymousPlayer's fixed default; anonymous rows
// always start as 'player', so re-asserting it is a no-op in
// practice.
//
// The WHERE guards (password_hash IS NULL AND email IS NULL) make
// the update idempotent under concurrent callbacks. A second
// callback that lost the race sees the row already credentialled
// and matches no rows; the wrapper maps that to ErrPlayerNotFound
// so the handler can fall through to the create path with the same
// petname-collision retry it uses for cookieless visitors.
func (q *Queries) ClaimPlayerForOAuth(ctx context.Context, arg ClaimPlayerForOAuthParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, claimPlayerForOAuth, arg.Email, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
	)
	return i, err
}

const countAllPlayers = `-- name: CountAllPlayers :one
SELECT COUNT(*) FROM players
`

// Total players row count for the admin list pagination (#423).
func (q *Queries) CountAllPlayers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllPlayers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnonymousPlayer = `-- name: CreateAnonymousPlayer :one
INSERT INTO players (username, role)
VALUES (?1, 'player')
RETURNING id, username, email, password_hash, role, created_at, username_claimed
`

// Used by the EnsurePlayer middleware to back a fresh visitor with a real
// players row before they can play. email and password_hash are NULL; role
// is fixed to 'player' because the "first password-bearing registrant
// becomes admin" SQL above filters by password_hash IS NOT NULL, so an
// anonymous row never qualifies for promotion.
//
// username_claimed defaults to 0: the auto-generated petname is not a name
// the visitor picked, so the row is unclaimed until they rename via the
// PATCH /api/players/me endpoint or sign up through ClaimPlayer below.
func (q *Queries) CreateAnonymousPlayer(ctx context.Context, username string) (Player, error) {
	row := q.db.QueryRowContext(ctx, createAnonymousPlayer, username)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
	)
	return i, err
}

const createPlayerFromOAuth = `-- name: CreatePlayerFromOAuth :one
INSERT INTO players (username, email, role, username_claimed)
VALUES (
    ?1,
    ?2,
    CASE
        WHEN NOT EXISTS (
            SELECT 1 FROM players p
            WHERE p.password_hash IS NOT NULL
               OR EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id)
        ) THEN 'admin'
        ELSE 'player'
    END,
    1
)
RETURNING id, username, email, password_hash, role, created_at, username_claimed
`

type CreatePlayerFromOAuthParams struct {
	Username string
	Email    sql.NullString
}

// Insert a brand-new player row for a first-time OAuth sign-in. No
// password_hash (the player has no local credential), email comes from
// the verified id-token claim, username_claimed is set to 1 because the
// caller supplies an auto-generated petname that the player will be
// prompted to change via the existing claim-name modal.
//
// The role CASE mirrors CreatePlayerWithCredentials so an OAuth-only
// first registrant still earns the admin promotion atomically. This is
// intentional: a deployment that only uses Google sign-in must still
// be able to bootstrap its first admin without an out-of-band password
// step. Counting credentialled players (password OR linked OAuth
// identity) instead of only password-bearing rows keeps OAuth-only
// deployments from promoting *every* sign-in to admin. Without this,
// the second-and-onward Google sign-ins on a fresh DB would all see
// count(password_hash IS NOT NULL) == 0 and become admin.
func (q *Queries) CreatePlayerFromOAuth(ctx context.Context, arg CreatePlayerFromOAuthParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayerFromOAuth, arg.Username, arg.Email)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
	)
	return i, err
}

const createPlayerWithCredentials = `-- name: CreatePlayerWithCredentials :one
INSERT INTO players (username, password_hash, role, username_claimed)
VALUES (
    ?1,
    ?2,
    CASE
        WHEN CAST(?3 AS TEXT) = 'admin' THEN 'admin'
        WHEN NOT EXISTS (
            SELECT 1 FROM players p
            WHERE p.password_hash IS NOT NULL
               OR EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id)
        ) THEN 'admin'
        ELSE 'player'
    END,
    1
)
RETURNING id, username, email, password_hash, role, created_at, username_claimed
`

type CreatePlayerWithCredentialsParams struct {
	Username      string
	PasswordHash  sql.NullString
	RequestedRole string
}

// The role decision lives in SQL so the "first credentialled registrant
// becomes admin" rule is atomic. Two concurrent first-registrations would
// both observe count == 0 if we computed the role in Go and called INSERT
// separately, leaving us with two admins. Folding the check into the same
// INSERT serialises the decision against the row that gets written.
//
// The third placeholder is the role requested by the caller (env-list match,
// otherwise "player"). If "admin" is requested explicitly we honour that;
// otherwise we promote only when no credentialled player exists yet. A
// "credentialled" player has either a password_hash or a linked OAuth
// identity (player_identities row). The seeded admin (id=1) has neither
// and is intentionally ignored so the operator's first real registration
// replaces it as admin.
//
// username_claimed is set to 1 because a registering user explicitly chose
// their username at the register form. The column tracks "did the player
// pick this name themselves" (vs auto-generated petname), so a fresh
// registrant must be marked as claimed from the moment the row is written.
func (q *Queries) CreatePlayerWithCredentials(ctx context.Context, arg CreatePlayerWithCredentialsParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayerWithCredentials, arg.Username, arg.PasswordHash, arg.RequestedRole)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
	)
	return i, err
}

const getPlayerByEmail = `-- name: GetPlayerByEmail :one
SELECT id, username, email, password_hash, role, created_at, username_claimed
FROM players
WHERE email = ?
LIMIT 1
`

// Look up a player by email so the Google OAuth callback can link a
// fresh identity onto an existing row when the verified email matches
// (instead of creating a duplicate player). Returns sql.ErrNoRows when
// no row matches, which the store maps to ErrPlayerNotFound.
func (q *Queries) GetPlayerByEmail(ctx context.Context, email sql.NullString) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByEmail, email)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
	)
	return i, err
}

const getPlayerByProviderSubject = `-- name: GetPlayerByProviderSubject :one
SELECT p.id, p.username, p.email, p.password_hash, p.role, p.created_at, p.username_claimed
FROM players p
JOIN player_identities pi ON pi.player_id = p.id
WHERE pi.provider = ? AND pi.subject = ?
LIMIT 1
`

type GetPlayerByProviderSubjectParams struct {
	Provider string
	Subject  string
}

// Look up a player via their player_identities row. The OAuth callback
// runs this first; on a hit the caller knows the identity already
// exists and signs the player in without touching the email-based
// linking path.
func (q *Queries) GetPlayerByProviderSubject(ctx context.Context, arg GetPlayerByProviderSubjectParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByProviderSubject, arg.Provider, arg.Subject)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
	)
	return i, err
}

const getPlayerByUsername = `-- name: GetPlayerByUsername :one
SELECT id, username, email, password_hash, role, created_at, username_claimed
FROM players
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetPlayerByUsername(ctx context.Context, username string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByUsername, username)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
	)
	return i, err
}

const linkProviderIdentity = `-- name: LinkProviderIdentity :exec
INSERT INTO player_identities (player_id, provider, subject)
VALUES (?, ?, ?)
`

type LinkProviderIdentityParams struct {
	PlayerID int64
	Provider string
	Subject  string
}

// Attach a (provider, subject) pair to an existing players row. Called
// after CreatePlayerFromOAuth for the new-account path and after
// GetPlayerByEmail for the existing-email link path. The UNIQUE
// constraint on (provider, subject) prevents two players from claiming
// the same external identity.
func (q *Queries) LinkProviderIdentity(ctx context.Context, arg LinkProviderIdentityParams) error {
	_, err := q.db.ExecContext(ctx, linkProviderIdentity, arg.PlayerID, arg.Provider, arg.Subject)
	return err
}

const listAllPlayers = `-- name: ListAllPlayers :many
SELECT
    p.id, p.username, p.email, p.password_hash, p.role, p.created_at, p.username_claimed,
    EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id) AS has_oauth,
    CAST(COALESCE((SELECT pi.provider FROM player_identities pi WHERE pi.player_id = p.id LIMIT 1), '') AS TEXT) AS oauth_provider
FROM players p
ORDER BY p.created_at DESC, p.id DESC
LIMIT ?2 OFFSET ?1
`

type ListAllPlayersParams struct {
	RowOffset int64
	RowLimit  int64
}

type ListAllPlayersRow struct {
	ID              int64
	Username        string
	Email           sql.NullString
	PasswordHash    sql.NullString
	Role            string
	CreatedAt       time.Time
	UsernameClaimed int64
	HasOauth        bool
	OauthProvider   string
}

// Returns one page of players for the admin players list (#423),
// ordered by created_at DESC so newest sign-ups land first. The
// derived has_oauth / oauth_provider fields surface the OAuth-link
// state in the same row so the handler does not have to issue a
// per-row lookup. Finished-quiz aggregates come from a separate
// ListPlayerFinishStats call against the page's player_ids; keeping
// the aggregate out of this query keeps the SELECT under sqlc's
// type-inference comfort zone and avoids a CTE / window function.
func (q *Queries) ListAllPlayers(ctx context.Context, arg ListAllPlayersParams) ([]ListAllPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlayers, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPlayersRow
	for rows.Next() {
		var i ListAllPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UsernameClaimed,
			&i.HasOauth,
			&i.OauthProvider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerFinishStats = `-- name: ListPlayerFinishStats :many
SELECT
    gp.player_id AS player_id,
    COUNT(DISTINCT g.id) AS finished_count,
    CAST(MAX(g.created_at) AS TEXT) AS last_finished_at
FROM game_participants gp
JOIN games g ON g.id = gp.game_id
WHERE gp.player_id IN (/*SLICE:player_ids*/?)
  AND EXISTS (SELECT 1 FROM questions qe WHERE qe.quiz_id = g.quiz_id)
  AND (SELECT COUNT(*) FROM game_questions gq WHERE gq.game_id = g.id) >=
      (SELECT COUNT(*) FROM questions qc WHERE qc.quiz_id = g.quiz_id)
GROUP BY gp.player_id
`

type ListPlayerFinishStatsRow struct {
	PlayerID       int64
	FinishedCount  int64
	LastFinishedAt string
}

// Returns (finished_count, last_finished_at) for each supplied
// player_id. "Finished" matches the canonical definition used by
// ListMostActivePlayers / ListPopularQuizzes: every question of the
// quiz has been issued (game_questions rows >= questions rows) and
// the quiz still has questions (empty-quiz games don't count). Used
// by the admin players list (#423) to aggregate per-page without
// folding the condition into ListAllPlayers' SELECT.
// The CAST on MAX gives sqlc's SQLite engine an explicit type hint
// so the generated row's LastFinishedAt lands as a string rather
// than interface{}. sqlc cannot infer the type through MAX over a
// nullable column otherwise. The store wrapper parses the timestamp
// back to time.Time. Empty-group case never fires because the WHERE
// clause drops players with no finished games entirely.
func (q *Queries) ListPlayerFinishStats(ctx context.Context, playerIds []int64) ([]ListPlayerFinishStatsRow, error) {
	query := listPlayerFinishStats
	var queryParams []interface{}
	if len(playerIds) > 0 {
		for _, v := range playerIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:player_ids*/?", strings.Repeat(",?", len(playerIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:player_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerFinishStatsRow
	for rows.Next() {
		var i ListPlayerFinishStatsRow
		if err := rows.Scan(&i.PlayerID, &i.FinishedCount, &i.LastFinishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renamePlayer = `-- name: RenamePlayer :one
UPDATE players
SET username = ?1,
    username_claimed = 1
WHERE id = ?2
RETURNING id, username, email, password_hash, role, created_at, username_claimed
`

type RenamePlayerParams struct {
	Username string
	ID       int64
}

// Renames any player row by id, regardless of password / email / role.
// The dedicated profile-page endpoint (POST /profile/username, #410)
// uses this so authenticated players (password, OAuth, admin) can
// change their display name. Anonymous rows have their own narrower
// path via UpdatePlayerUsername above; this query is intentionally
// not gated by password_hash so the OAuth-only and admin cases also
// work.
//
// Returns the updated row when one was affected; the store wrapper
// maps sql.ErrNoRows to ErrPlayerNotFound and a UNIQUE constraint
// failure on players.username to ErrUsernameTaken so the handler can
// map both onto user-facing form errors.
func (q *Queries) RenamePlayer(ctx context.Context, arg RenamePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, renamePlayer, arg.Username, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
	)
	return i, err
}

const setPlayerPasswordHash = `-- name: SetPlayerPasswordHash :execrows
UPDATE players
SET password_hash    = ?1,
    username_claimed = 1
WHERE username = ?2
`

type SetPlayerPasswordHashParams struct {
	PasswordHash sql.NullString
	Username     string
}

// Used by the cmd/server -reset-password operator tool to rotate a single
// player's password without disturbing username / role / email. Returns the
// number of affected rows so the caller can map "no rows" to a "username not
// found" error.
//
// username_claimed is set to 1 alongside the password because once an
// operator has set a password on a row, the username is no longer an
// auto-assigned petname the player should be nudged to replace (#289). The
// migration 20260511120000 ran the same backfill at the time, but only for
// rows that already had a password_hash; later password sets via this
// query previously left username_claimed at 0, which made the seed
// admin (id=1) keep popping the claim-name modal in the player client.
func (q *Queries) SetPlayerPasswordHash(ctx context.Context, arg SetPlayerPasswordHashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPlayerPasswordHash, arg.PasswordHash, arg.Username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePlayerUsername = `-- name: UpdatePlayerUsername :one
UPDATE players
SET username = ?1,
    username_claimed = 1
WHERE id = ?2 AND password_hash IS NULL
RETURNING id, username, email, password_hash, role, created_at, username_claimed
`

type UpdatePlayerUsernameParams struct {
	Username string
	ID       int64
}

// Updates the username on an anonymous player row in place. The WHERE
// clause refuses the update when the player has already claimed a
// non-anonymous identity (password_hash IS NOT NULL), so the SQL is the
// atomic guard against a stale anonymous check in the service layer.
// Returns the updated row when one was affected; the wrapper distinguishes
// "not anonymous anymore" (sql.ErrNoRows) from "username collision"
// (UNIQUE constraint failure on players.username).
//
// username_claimed is set to 1 because this is the dedicated claim-name
// endpoint (PATCH /api/players/me); the visitor is explicitly picking
// their display name. After this update the row reads as "player chose
// this name" identically to the credentialled-registration path.
func (q *Queries) UpdatePlayerUsername(ctx context.Context, arg UpdatePlayerUsernameParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, updatePlayerUsername, arg.Username, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
	)
	return i, err
}
