// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"
	"database/sql"
)

const createPlayerWithCredentials = `-- name: CreatePlayerWithCredentials :one
INSERT INTO players (username, password_hash, role)
VALUES (
    ?1,
    ?2,
    CASE
        WHEN CAST(?3 AS TEXT) = 'admin' THEN 'admin'
        WHEN (SELECT COUNT(*) FROM players WHERE password_hash IS NOT NULL) = 0 THEN 'admin'
        ELSE 'player'
    END
)
RETURNING id, username, email, password_hash, role, created_at
`

type CreatePlayerWithCredentialsParams struct {
	Username      string
	PasswordHash  sql.NullString
	RequestedRole string
}

// The role decision lives in SQL so the "first password-bearing registrant
// becomes admin" rule is atomic. Two concurrent first-registrations would
// both observe count == 0 if we computed the role in Go and called INSERT
// separately, leaving us with two admins. Folding the check into the same
// INSERT serialises the decision against the row that gets written.
//
// The third placeholder is the role requested by the caller (env-list match,
// otherwise "player"). If "admin" is requested explicitly we honour that;
// otherwise we promote when there are no other rows with a password_hash
// (legacy seed admin without a password is intentionally ignored).
func (q *Queries) CreatePlayerWithCredentials(ctx context.Context, arg CreatePlayerWithCredentialsParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayerWithCredentials, arg.Username, arg.PasswordHash, arg.RequestedRole)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerByUsername = `-- name: GetPlayerByUsername :one
SELECT id, username, email, password_hash, role, created_at
FROM players
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetPlayerByUsername(ctx context.Context, username string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByUsername, username)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
