// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const claimPlayer = `-- name: ClaimPlayer :one
UPDATE players
SET username = ?1,
    password_hash = ?2,
    email = ?3,
    role = CASE
        WHEN CAST(?4 AS TEXT) = 'admin' THEN 'admin'
        WHEN NOT EXISTS (
            SELECT 1 FROM players p
            WHERE p.password_hash IS NOT NULL
               OR EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id)
        ) THEN 'admin'
        ELSE 'player'
    END,
    username_claimed = 1
WHERE players.id = ?5
  AND players.password_hash IS NULL
  AND players.email IS NULL
RETURNING id, username, email, password_hash, role, created_at, username_claimed, email_verified_at, session_version
`

type ClaimPlayerParams struct {
	Username      string
	PasswordHash  sql.NullString
	Email         sql.NullString
	RequestedRole string
	ID            int64
}

// Upgrades an anonymous (password_hash IS NULL) row in place so that an
// already-playing visitor keeps their player_id when they sign up. The
// WHERE password_hash IS NULL guard makes this idempotent: a second claim
// attempt against an already-credentialled row returns no rows, which the
// store maps to ErrPlayerAlreadyClaimed.
//
// The role CASE mirrors CreatePlayerWithCredentials so the "first
// credentialled registrant becomes admin" rule still triggers when the
// very first sign-up happens through the claim path (i.e. the registrant
// played anonymously first). The subquery aliases the players table as pp
// so the column reference in the WHERE is unambiguous against the row
// being updated. The credentialled-player check covers both password and
// OAuth identity so a deployment that bootstrapped its admin via Google
// doesn't auto-promote later password claimers.
//
// username_claimed is set to 1 because the visitor is explicitly choosing
// their username via the register form. This is the register-after-playing
// path: the row now represents a player who picked their own name, so it
// must look identical to a CreatePlayerWithCredentials row to downstream
// callers.
func (q *Queries) ClaimPlayer(ctx context.Context, arg ClaimPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, claimPlayer,
		arg.Username,
		arg.PasswordHash,
		arg.Email,
		arg.RequestedRole,
		arg.ID,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
		&i.EmailVerifiedAt,
		&i.SessionVersion,
	)
	return i, err
}

const claimPlayerForOAuth = `-- name: ClaimPlayerForOAuth :one
UPDATE players
SET email = ?1,
    email_verified_at = CURRENT_TIMESTAMP,
    role = CASE
        WHEN NOT EXISTS (
            SELECT 1 FROM players p
            WHERE p.password_hash IS NOT NULL
               OR EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id)
        ) THEN 'admin'
        ELSE 'player'
    END
WHERE players.id = ?2
  AND players.password_hash IS NULL
  AND players.email IS NULL
RETURNING id, username, email, password_hash, role, created_at, username_claimed, email_verified_at, session_version
`

type ClaimPlayerForOAuthParams struct {
	Email sql.NullString
	ID    int64
}

// Upgrades a fully anonymous players row (no password_hash, no email)
// in place by attaching the OAuth-verified email. Lets a visitor who
// played anonymously keep their existing player_id (and therefore
// their game history and any custom username) when they sign in with
// Google for the first time. The username is left untouched: the
// visitor's auto-petname or PATCH-claimed name carries through onto
// the OAuth-linked row.
//
// The role CASE mirrors CreatePlayerFromOAuth so the first OAuth-only
// registrant still earns the admin promotion atomically. ELSE 'player'
// matches CreateAnonymousPlayer's fixed default; anonymous rows
// always start as 'player', so re-asserting it is a no-op in
// practice.
//
// The WHERE guards (password_hash IS NULL AND email IS NULL) make
// the update idempotent under concurrent callbacks. A second
// callback that lost the race sees the row already credentialled
// and matches no rows; the wrapper maps that to ErrPlayerNotFound
// so the handler can fall through to the create path with the same
// petname-collision retry it uses for cookieless visitors.
func (q *Queries) ClaimPlayerForOAuth(ctx context.Context, arg ClaimPlayerForOAuthParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, claimPlayerForOAuth, arg.Email, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
		&i.EmailVerifiedAt,
		&i.SessionVersion,
	)
	return i, err
}

const consumeEmailVerifyToken = `-- name: ConsumeEmailVerifyToken :one
UPDATE email_verify_tokens
SET consumed_at = ?1
WHERE token_hash = ?2
  AND consumed_at IS NULL
  AND expires_at > ?3
RETURNING player_id, pending_email
`

type ConsumeEmailVerifyTokenParams struct {
	ConsumedAt sql.NullTime
	TokenHash  string
	Now        time.Time
}

type ConsumeEmailVerifyTokenRow struct {
	PlayerID     int64
	PendingEmail sql.NullString
}

// Atomic consume: succeeds only when the row is still unconsumed and not
// expired. Returns the player_id so the caller can stamp email_verified_at
// in the same transaction, plus pending_email so the caller can branch on
// the in-session email-change variant (#497) without a second round trip.
// The caller passes the wall clock as 'now' so both sides of the
// expires_at comparison use the same RFC3339 encoding the modernc/sqlite
// driver writes - mixing time.Time with CURRENT_TIMESTAMP produces strings
// of different lengths and the lexicographic comparison silently lies.
// sql.ErrNoRows means the token was consumed, expired, or never existed;
// the caller maps that to a single user-facing "this link is no longer
// valid" response.
func (q *Queries) ConsumeEmailVerifyToken(ctx context.Context, arg ConsumeEmailVerifyTokenParams) (ConsumeEmailVerifyTokenRow, error) {
	row := q.db.QueryRowContext(ctx, consumeEmailVerifyToken, arg.ConsumedAt, arg.TokenHash, arg.Now)
	var i ConsumeEmailVerifyTokenRow
	err := row.Scan(&i.PlayerID, &i.PendingEmail)
	return i, err
}

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET consumed_at = ?1
WHERE token_hash = ?2
  AND consumed_at IS NULL
  AND expires_at > ?3
RETURNING player_id
`

type ConsumePasswordResetTokenParams struct {
	ConsumedAt sql.NullTime
	TokenHash  string
	Now        time.Time
}

// Atomic consume: succeeds only when the row is still unconsumed and
// not expired. Returns the player_id so the caller can stamp the new
// password_hash + bump session_version in the same transaction. The
// caller passes 'now' on both sides so the comparison runs in the
// driver's RFC3339 encoding (same gotcha email_verify_tokens dodged).
// sql.ErrNoRows means consumed, expired, or never existed; the caller
// maps that to a single user-facing "link is no longer valid" response.
func (q *Queries) ConsumePasswordResetToken(ctx context.Context, arg ConsumePasswordResetTokenParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, consumePasswordResetToken, arg.ConsumedAt, arg.TokenHash, arg.Now)
	var player_id int64
	err := row.Scan(&player_id)
	return player_id, err
}

const countAllPlayers = `-- name: CountAllPlayers :one
SELECT COUNT(*) FROM players
`

// Total players row count for the admin list pagination (#423).
func (q *Queries) CountAllPlayers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllPlayers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnonymousPlayer = `-- name: CreateAnonymousPlayer :one
INSERT INTO players (username, role)
VALUES (?1, 'player')
RETURNING id, username, email, password_hash, role, created_at, username_claimed, email_verified_at, session_version
`

// Used by the EnsurePlayer middleware to back a fresh visitor with a real
// players row before they can play. email and password_hash are NULL; role
// is fixed to 'player' because the "first password-bearing registrant
// becomes admin" SQL above filters by password_hash IS NOT NULL, so an
// anonymous row never qualifies for promotion.
//
// username_claimed defaults to 0: the auto-generated petname is not a name
// the visitor picked, so the row is unclaimed until they rename via the
// PATCH /api/players/me endpoint or sign up through ClaimPlayer below.
func (q *Queries) CreateAnonymousPlayer(ctx context.Context, username string) (Player, error) {
	row := q.db.QueryRowContext(ctx, createAnonymousPlayer, username)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
		&i.EmailVerifiedAt,
		&i.SessionVersion,
	)
	return i, err
}

const createEmailVerifyToken = `-- name: CreateEmailVerifyToken :exec
INSERT INTO email_verify_tokens (token_hash, player_id, expires_at, pending_email)
VALUES (?1, ?2, ?3, ?4)
`

type CreateEmailVerifyTokenParams struct {
	TokenHash    string
	PlayerID     int64
	ExpiresAt    time.Time
	PendingEmail sql.NullString
}

// Stores the sha256 hash of a freshly minted verify-email token. The raw
// token only exists on the way out the door in the email; a DB leak should
// not be replayable against GET /verify-email.
//
// pending_email is NULL for the register-time path and the resend variant;
// the in-session email-change path (#497) sets it to the new address the
// visitor wants to switch to so the consume side can swap players.email
// atomically when the link is clicked. Holding the new address here rather
// than on the players row keeps the current verified email live until the
// visitor actually proves they control the new mailbox.
func (q *Queries) CreateEmailVerifyToken(ctx context.Context, arg CreateEmailVerifyTokenParams) error {
	_, err := q.db.ExecContext(ctx, createEmailVerifyToken,
		arg.TokenHash,
		arg.PlayerID,
		arg.ExpiresAt,
		arg.PendingEmail,
	)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (token_hash, player_id, expires_at)
VALUES (?1, ?2, ?3)
`

type CreatePasswordResetTokenParams struct {
	TokenHash string
	PlayerID  int64
	ExpiresAt time.Time
}

// Stores the sha256 hash of a freshly minted reset-password token. The
// raw token only exists on the way out the door in the email; a DB leak
// should not be replayable against POST /reset-password.
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordResetToken, arg.TokenHash, arg.PlayerID, arg.ExpiresAt)
	return err
}

const createPlayerFromOAuth = `-- name: CreatePlayerFromOAuth :one
INSERT INTO players (username, email, email_verified_at, role, username_claimed)
VALUES (
    ?1,
    ?2,
    CURRENT_TIMESTAMP,
    CASE
        WHEN NOT EXISTS (
            SELECT 1 FROM players p
            WHERE p.password_hash IS NOT NULL
               OR EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id)
        ) THEN 'admin'
        ELSE 'player'
    END,
    1
)
RETURNING id, username, email, password_hash, role, created_at, username_claimed, email_verified_at, session_version
`

type CreatePlayerFromOAuthParams struct {
	Username string
	Email    sql.NullString
}

// Insert a brand-new player row for a first-time OAuth sign-in. No
// password_hash (the player has no local credential), email comes from
// the verified id-token claim, username_claimed is set to 1 because the
// caller supplies an auto-generated petname that the player will be
// prompted to change via the existing claim-name modal.
//
// The role CASE mirrors CreatePlayerWithCredentials so an OAuth-only
// first registrant still earns the admin promotion atomically. This is
// intentional: a deployment that only uses Google sign-in must still
// be able to bootstrap its first admin without an out-of-band password
// step. Counting credentialled players (password OR linked OAuth
// identity) instead of only password-bearing rows keeps OAuth-only
// deployments from promoting *every* sign-in to admin. Without this,
// the second-and-onward Google sign-ins on a fresh DB would all see
// count(password_hash IS NOT NULL) == 0 and become admin.
func (q *Queries) CreatePlayerFromOAuth(ctx context.Context, arg CreatePlayerFromOAuthParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayerFromOAuth, arg.Username, arg.Email)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
		&i.EmailVerifiedAt,
		&i.SessionVersion,
	)
	return i, err
}

const createPlayerWithCredentials = `-- name: CreatePlayerWithCredentials :one
INSERT INTO players (username, password_hash, email, role, username_claimed)
VALUES (
    ?1,
    ?2,
    ?3,
    CASE
        WHEN CAST(?4 AS TEXT) = 'admin' THEN 'admin'
        WHEN NOT EXISTS (
            SELECT 1 FROM players p
            WHERE p.password_hash IS NOT NULL
               OR EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id)
        ) THEN 'admin'
        ELSE 'player'
    END,
    1
)
RETURNING id, username, email, password_hash, role, created_at, username_claimed, email_verified_at, session_version
`

type CreatePlayerWithCredentialsParams struct {
	Username      string
	PasswordHash  sql.NullString
	Email         sql.NullString
	RequestedRole string
}

// The role decision lives in SQL so the "first credentialled registrant
// becomes admin" rule is atomic. Two concurrent first-registrations would
// both observe count == 0 if we computed the role in Go and called INSERT
// separately, leaving us with two admins. Folding the check into the same
// INSERT serialises the decision against the row that gets written.
//
// The third placeholder is the role requested by the caller (env-list match,
// otherwise "player"). If "admin" is requested explicitly we honour that;
// otherwise we promote only when no credentialled player exists yet. A
// "credentialled" player has either a password_hash or a linked OAuth
// identity (player_identities row). The seeded admin (id=1) has neither
// and is intentionally ignored so the operator's first real registration
// replaces it as admin.
//
// username_claimed is set to 1 because a registering user explicitly chose
// their username at the register form. The column tracks "did the player
// pick this name themselves" (vs auto-generated petname), so a fresh
// registrant must be marked as claimed from the moment the row is written.
func (q *Queries) CreatePlayerWithCredentials(ctx context.Context, arg CreatePlayerWithCredentialsParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayerWithCredentials,
		arg.Username,
		arg.PasswordHash,
		arg.Email,
		arg.RequestedRole,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
		&i.EmailVerifiedAt,
		&i.SessionVersion,
	)
	return i, err
}

const deleteExpiredEmailVerifyTokens = `-- name: DeleteExpiredEmailVerifyTokens :exec
DELETE FROM email_verify_tokens
WHERE expires_at <= ?1
`

// Housekeeping for the startup sweep. Drops every row whose link has
// expired so the table does not grow without bound. The caller passes
// 'now' so the comparison runs in the same encoding the driver writes
// (see the ConsumeEmailVerifyToken note above).
func (q *Queries) DeleteExpiredEmailVerifyTokens(ctx context.Context, now time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredEmailVerifyTokens, now)
	return err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE expires_at <= ?1
`

// Housekeeping for the startup sweep. UTC across the wire so the
// comparison stays lexicographically sane regardless of the host
// timezone.
func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context, now time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResetTokens, now)
	return err
}

const getEmailVerifyToken = `-- name: GetEmailVerifyToken :one
SELECT token_hash, player_id, created_at, expires_at, consumed_at, pending_email
FROM email_verify_tokens
WHERE token_hash = ?1
LIMIT 1
`

// Look up by token hash. Caller checks expires_at vs the wall clock and
// consumed_at IS NULL before treating it as live.
func (q *Queries) GetEmailVerifyToken(ctx context.Context, tokenHash string) (EmailVerifyToken, error) {
	row := q.db.QueryRowContext(ctx, getEmailVerifyToken, tokenHash)
	var i EmailVerifyToken
	err := row.Scan(
		&i.TokenHash,
		&i.PlayerID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.PendingEmail,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT token_hash, player_id, created_at, expires_at, consumed_at
FROM password_reset_tokens
WHERE token_hash = ?1
LIMIT 1
`

// Look up a reset row by hash. Returned regardless of consumed_at /
// expires_at - the caller decides whether to treat it as live.
func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.PlayerID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getPlayerByEmail = `-- name: GetPlayerByEmail :one
SELECT id, username, email, password_hash, role, created_at, username_claimed, email_verified_at, session_version
FROM players
WHERE email = ?
LIMIT 1
`

// Look up a player by email so the Google OAuth callback can link a
// fresh identity onto an existing row when the verified email matches
// (instead of creating a duplicate player). Returns sql.ErrNoRows when
// no row matches, which the store maps to ErrPlayerNotFound.
func (q *Queries) GetPlayerByEmail(ctx context.Context, email sql.NullString) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByEmail, email)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
		&i.EmailVerifiedAt,
		&i.SessionVersion,
	)
	return i, err
}

const getPlayerByProviderSubject = `-- name: GetPlayerByProviderSubject :one
SELECT p.id, p.username, p.email, p.password_hash, p.role, p.created_at, p.username_claimed, p.email_verified_at, p.session_version
FROM players p
JOIN player_identities pi ON pi.player_id = p.id
WHERE pi.provider = ? AND pi.subject = ?
LIMIT 1
`

type GetPlayerByProviderSubjectParams struct {
	Provider string
	Subject  string
}

// Look up a player via their player_identities row. The OAuth callback
// runs this first; on a hit the caller knows the identity already
// exists and signs the player in without touching the email-based
// linking path.
func (q *Queries) GetPlayerByProviderSubject(ctx context.Context, arg GetPlayerByProviderSubjectParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByProviderSubject, arg.Provider, arg.Subject)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
		&i.EmailVerifiedAt,
		&i.SessionVersion,
	)
	return i, err
}

const getPlayerByUsername = `-- name: GetPlayerByUsername :one
SELECT id, username, email, password_hash, role, created_at, username_claimed, email_verified_at, session_version
FROM players
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetPlayerByUsername(ctx context.Context, username string) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByUsername, username)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
		&i.EmailVerifiedAt,
		&i.SessionVersion,
	)
	return i, err
}

const linkProviderIdentity = `-- name: LinkProviderIdentity :exec
INSERT INTO player_identities (player_id, provider, subject)
VALUES (?, ?, ?)
`

type LinkProviderIdentityParams struct {
	PlayerID int64
	Provider string
	Subject  string
}

// Attach a (provider, subject) pair to an existing players row. Called
// after CreatePlayerFromOAuth for the new-account path and after
// GetPlayerByEmail for the existing-email link path. The UNIQUE
// constraint on (provider, subject) prevents two players from claiming
// the same external identity.
func (q *Queries) LinkProviderIdentity(ctx context.Context, arg LinkProviderIdentityParams) error {
	_, err := q.db.ExecContext(ctx, linkProviderIdentity, arg.PlayerID, arg.Provider, arg.Subject)
	return err
}

const listAllPlayers = `-- name: ListAllPlayers :many
SELECT
    p.id, p.username, p.email, p.password_hash, p.role, p.created_at, p.username_claimed, p.email_verified_at, p.session_version,
    EXISTS (SELECT 1 FROM player_identities pi WHERE pi.player_id = p.id) AS has_oauth,
    CAST(COALESCE((SELECT pi.provider FROM player_identities pi WHERE pi.player_id = p.id ORDER BY pi.provider LIMIT 1), '') AS TEXT) AS oauth_provider
FROM players p
ORDER BY p.created_at DESC, p.id DESC
LIMIT ?2 OFFSET ?1
`

type ListAllPlayersParams struct {
	RowOffset int64
	RowLimit  int64
}

type ListAllPlayersRow struct {
	ID              int64
	Username        string
	Email           sql.NullString
	PasswordHash    sql.NullString
	Role            string
	CreatedAt       time.Time
	UsernameClaimed int64
	EmailVerifiedAt sql.NullTime
	SessionVersion  int64
	HasOauth        bool
	OauthProvider   string
}

// Returns one page of players for the admin players list (#423),
// ordered by created_at DESC so newest sign-ups land first. The
// derived has_oauth / oauth_provider fields surface the OAuth-link
// state in the same row so the handler does not have to issue a
// per-row lookup. Finished-quiz aggregates come from a separate
// ListPlayerFinishStats call against the page's player_ids; keeping
// the aggregate out of this query keeps the SELECT under sqlc's
// type-inference comfort zone and avoids a CTE / window function.
// The oauth_provider subquery uses ORDER BY pi.provider so a player
// with multiple linked identities (future multi-provider support)
// always surfaces the same alphabetically-first one rather than a
// nondeterministic pick.
func (q *Queries) ListAllPlayers(ctx context.Context, arg ListAllPlayersParams) ([]ListAllPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlayers, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPlayersRow
	for rows.Next() {
		var i ListAllPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UsernameClaimed,
			&i.EmailVerifiedAt,
			&i.SessionVersion,
			&i.HasOauth,
			&i.OauthProvider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayerFinishStats = `-- name: ListPlayerFinishStats :many
SELECT
    gp.player_id AS player_id,
    COUNT(DISTINCT g.id) AS finished_count,
    CAST(MAX(g.created_at) AS TEXT) AS last_finished_at
FROM game_participants gp
JOIN games g ON g.id = gp.game_id
WHERE gp.player_id IN (/*SLICE:player_ids*/?)
  AND EXISTS (SELECT 1 FROM questions qe WHERE qe.quiz_id = g.quiz_id)
  AND (SELECT COUNT(*) FROM game_questions gq WHERE gq.game_id = g.id) >=
      (SELECT COUNT(*) FROM questions qc WHERE qc.quiz_id = g.quiz_id)
GROUP BY gp.player_id
`

type ListPlayerFinishStatsRow struct {
	PlayerID       int64
	FinishedCount  int64
	LastFinishedAt string
}

// Returns (finished_count, last_finished_at) for each supplied
// player_id. A game counts as finished when every question of its
// quiz has been issued (game_questions row count >= questions row
// count) and the quiz still has at least one question (an empty
// quiz can't be finished). Used by the admin players list (#423)
// to aggregate per-page without folding the condition into
// ListAllPlayers' SELECT.
// The CAST on MAX gives sqlc's SQLite engine an explicit type hint
// so the generated row's LastFinishedAt lands as a string rather
// than interface{}. sqlc cannot infer the type through MAX over a
// nullable column otherwise. The store wrapper parses the timestamp
// back to time.Time. Empty-group case never fires because the WHERE
// clause drops players with no finished games entirely.
func (q *Queries) ListPlayerFinishStats(ctx context.Context, playerIds []int64) ([]ListPlayerFinishStatsRow, error) {
	query := listPlayerFinishStats
	var queryParams []interface{}
	if len(playerIds) > 0 {
		for _, v := range playerIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:player_ids*/?", strings.Repeat(",?", len(playerIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:player_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayerFinishStatsRow
	for rows.Next() {
		var i ListPlayerFinishStatsRow
		if err := rows.Scan(&i.PlayerID, &i.FinishedCount, &i.LastFinishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPlayerEmailVerifiedIfNew = `-- name: MarkPlayerEmailVerifiedIfNew :execrows
UPDATE players
SET email_verified_at = CURRENT_TIMESTAMP
WHERE id = ?1
  AND email_verified_at IS NULL
`

// Stamps email_verified_at when currently NULL. Idempotent.
func (q *Queries) MarkPlayerEmailVerifiedIfNew(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPlayerEmailVerifiedIfNew, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renamePlayer = `-- name: RenamePlayer :one
UPDATE players
SET username = ?1,
    username_claimed = 1
WHERE id = ?2
RETURNING id, username, email, password_hash, role, created_at, username_claimed, email_verified_at, session_version
`

type RenamePlayerParams struct {
	Username string
	ID       int64
}

// Renames any player row by id, regardless of password / email / role.
// The dedicated profile-page endpoint (POST /profile/username, #410)
// uses this so authenticated players (password, OAuth, admin) can
// change their display name. Anonymous rows have their own narrower
// path via UpdatePlayerUsername above; this query is intentionally
// not gated by password_hash so the OAuth-only and admin cases also
// work.
//
// Returns the updated row when one was affected; the store wrapper
// maps sql.ErrNoRows to ErrPlayerNotFound and a UNIQUE constraint
// failure on players.username to ErrUsernameTaken so the handler can
// map both onto user-facing form errors.
func (q *Queries) RenamePlayer(ctx context.Context, arg RenamePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, renamePlayer, arg.Username, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
		&i.EmailVerifiedAt,
		&i.SessionVersion,
	)
	return i, err
}

const resetPlayerPassword = `-- name: ResetPlayerPassword :execrows
UPDATE players
SET password_hash = ?1,
    session_version = session_version + 1
WHERE id = ?2
`

type ResetPlayerPasswordParams struct {
	PasswordHash sql.NullString
	ID           int64
}

// Atomically rotates password_hash and bumps session_version on the
// given row. The session_version increment is the security-critical
// part: every in-flight cookie carries the version it was issued at,
// so a bump invalidates every other session the moment this commits.
// Returns the number of affected rows; the caller checks for >0 to
// distinguish a successful reset from a player_id pointing nowhere.
func (q *Queries) ResetPlayerPassword(ctx context.Context, arg ResetPlayerPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetPlayerPassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPlayerPasswordHash = `-- name: SetPlayerPasswordHash :execrows
UPDATE players
SET password_hash    = ?1,
    username_claimed = 1
WHERE email = ?2
`

type SetPlayerPasswordHashParams struct {
	PasswordHash sql.NullString
	Email        sql.NullString
}

// Used by the cmd/server -reset-password operator tool to rotate a single
// player's password without disturbing username / role / email. Returns the
// number of affected rows so the caller can map "no rows" to an "email
// not found" error. The lookup is by email (the post-#446 login credential)
// so the operator's reset target matches what the player types into /login.
//
// username_claimed is set to 1 alongside the password because once an
// operator has set a password on a row, the username is no longer an
// auto-assigned petname the player should be nudged to replace (#289). The
// migration 20260511120000 ran the same backfill at the time, but only for
// rows that already had a password_hash; later password sets via this
// query previously left username_claimed at 0, which made the seed
// admin (id=1) keep popping the claim-name modal in the player client.
func (q *Queries) SetPlayerPasswordHash(ctx context.Context, arg SetPlayerPasswordHashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPlayerPasswordHash, arg.PasswordHash, arg.Email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const swapPlayerEmail = `-- name: SwapPlayerEmail :execrows
UPDATE players
SET email = ?1,
    email_verified_at = CURRENT_TIMESTAMP,
    session_version = session_version + 1
WHERE id = ?2
`

type SwapPlayerEmailParams struct {
	Email sql.NullString
	ID    int64
}

// Atomically replaces players.email with the supplied address and stamps
// email_verified_at (re-stamped because the new address has just been
// proven via the verify link). The session_version bump invalidates every
// other live cookie for this account so a stolen verify link cannot ride
// an existing session on a different device.
//
// Used only by the in-session email-change consume path (#497); the
// register-time consumer keeps calling MarkPlayerEmailVerifiedIfNew. A
// UNIQUE collision on players.email surfaces as the driver's constraint
// error - the store wrapper maps it onto ErrEmailTaken so the consumer
// can render a "that address is no longer free" page instead of 500ing.
func (q *Queries) SwapPlayerEmail(ctx context.Context, arg SwapPlayerEmailParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, swapPlayerEmail, arg.Email, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePlayerUsername = `-- name: UpdatePlayerUsername :one
UPDATE players
SET username = ?1,
    username_claimed = 1
WHERE id = ?2 AND password_hash IS NULL
RETURNING id, username, email, password_hash, role, created_at, username_claimed, email_verified_at, session_version
`

type UpdatePlayerUsernameParams struct {
	Username string
	ID       int64
}

// Updates the username on an anonymous player row in place. The WHERE
// clause refuses the update when the player has already claimed a
// non-anonymous identity (password_hash IS NOT NULL), so the SQL is the
// atomic guard against a stale anonymous check in the service layer.
// Returns the updated row when one was affected; the wrapper distinguishes
// "not anonymous anymore" (sql.ErrNoRows) from "username collision"
// (UNIQUE constraint failure on players.username).
//
// username_claimed is set to 1 because this is the dedicated claim-name
// endpoint (PATCH /api/players/me); the visitor is explicitly picking
// their display name. After this update the row reads as "player chose
// this name" identically to the credentialled-registration path.
func (q *Queries) UpdatePlayerUsername(ctx context.Context, arg UpdatePlayerUsernameParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, updatePlayerUsername, arg.Username, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UsernameClaimed,
		&i.EmailVerifiedAt,
		&i.SessionVersion,
	)
	return i, err
}
