// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quizzes.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const bumpQuizPlayCountForGame = `-- name: BumpQuizPlayCountForGame :exec
UPDATE quizzes
SET play_count = play_count + 1
WHERE quizzes.id = (SELECT quiz_id FROM games WHERE games.id = ?)
`

// Increments the durable hit counter (#891) for the quiz that owns this solo
// game. Resolves the quiz from the game id so the caller only signals "this
// play completed" without threading the quiz id. Never decremented; the CHECK
// on quizzes.play_count keeps it non-negative.
func (q *Queries) BumpQuizPlayCountForGame(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, bumpQuizPlayCountForGame, id)
	return err
}

const bumpQuizPlayCountForSession = `-- name: BumpQuizPlayCountForSession :exec
UPDATE quizzes
SET play_count = play_count + 1
WHERE quizzes.id = (SELECT quiz_id FROM sessions WHERE sessions.id = ?)
`

// Increments the durable hit counter (#891) for the quiz a live session is
// playing. Resolves the quiz from the session id. A session with a NULL
// quiz_id (a quiz-less room) matches no quiz row, so the bump is a safe no-op.
func (q *Queries) BumpQuizPlayCountForSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, bumpQuizPlayCountForSession, id)
	return err
}

const createOption = `-- name: CreateOption :one
INSERT INTO options (question_id, text, is_correct)
VALUES (?, ?, ?)
RETURNING id, question_id, text, is_correct
`

type CreateOptionParams struct {
	QuestionID int64
	Text       string
	IsCorrect  bool
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error) {
	row := q.db.QueryRowContext(ctx, createOption, arg.QuestionID, arg.Text, arg.IsCorrect)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (quiz_id, round_id, text, position, image_media_id, audio_media_id, audio_repeat, time_limit_seconds)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, quiz_id, round_id, text, position, time_limit_seconds, image_media_id, audio_media_id, audio_repeat
`

type CreateQuestionParams struct {
	QuizID           int64
	RoundID          int64
	Text             string
	Position         int64
	ImageMediaID     sql.NullInt64
	AudioMediaID     sql.NullInt64
	AudioRepeat      int64
	TimeLimitSeconds sql.NullInt64
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion,
		arg.QuizID,
		arg.RoundID,
		arg.Text,
		arg.Position,
		arg.ImageMediaID,
		arg.AudioMediaID,
		arg.AudioRepeat,
		arg.TimeLimitSeconds,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.RoundID,
		&i.Text,
		&i.Position,
		&i.TimeLimitSeconds,
		&i.ImageMediaID,
		&i.AudioMediaID,
		&i.AudioRepeat,
	)
	return i, err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (title, slug, description, created_by_player_id, time_limit_seconds, visibility, mode, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, title, slug, description, created_at, updated_at, created_by_player_id, time_limit_seconds, visibility, mode, play_count
`

type CreateQuizParams struct {
	Title             string
	Slug              string
	Description       string
	CreatedByPlayerID int64
	TimeLimitSeconds  int64
	Visibility        string
	Mode              string
}

// created_by_player_id is NOT NULL with an FK to players.id (migration
// 20260520200000 / #281). [QuizStore.CreateQuiz] short-circuits with
// ErrCreatorRequired when the caller forgot to stamp the session
// admin, so the FK constraint is the second line of defence.
func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, createQuiz,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.CreatedByPlayerID,
		arg.TimeLimitSeconds,
		arg.Visibility,
		arg.Mode,
	)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByPlayerID,
		&i.TimeLimitSeconds,
		&i.Visibility,
		&i.Mode,
		&i.PlayCount,
	)
	return i, err
}

const deleteOption = `-- name: DeleteOption :execresult
DELETE FROM options
WHERE id = ?
`

func (q *Queries) DeleteOption(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOption, id)
}

const deleteQuestion = `-- name: DeleteQuestion :execresult
DELETE FROM questions
WHERE id = ?
`

func (q *Queries) DeleteQuestion(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteQuestion, id)
}

const deleteQuiz = `-- name: DeleteQuiz :execresult
DELETE
FROM quizzes
WHERE id = ?
`

func (q *Queries) DeleteQuiz(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteQuiz, id)
}

const getOption = `-- name: GetOption :one
SELECT id, question_id, text, is_correct
FROM options
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetOption(ctx context.Context, id int64) (Option, error) {
	row := q.db.QueryRowContext(ctx, getOption, id)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
	)
	return i, err
}

const getOptionsByIDs = `-- name: GetOptionsByIDs :many
SELECT id, question_id, text, is_correct
FROM options
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetOptionsByIDs(ctx context.Context, ids []int64) ([]Option, error) {
	query := getOptionsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, quiz_id, round_id, text, position, time_limit_seconds, image_media_id, audio_media_id, audio_repeat
FROM questions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetQuestion(ctx context.Context, id int64) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.RoundID,
		&i.Text,
		&i.Position,
		&i.TimeLimitSeconds,
		&i.ImageMediaID,
		&i.AudioMediaID,
		&i.AudioRepeat,
	)
	return i, err
}

const getQuiz = `-- name: GetQuiz :one
SELECT q.id,
       q.title,
       q.slug,
       q.description,
       q.created_at,
       q.updated_at,
       q.created_by_player_id,
       q.time_limit_seconds,
       q.visibility,
       q.mode,
       q.play_count,
       p.display_name AS created_by_display_name
FROM quizzes q
         JOIN players p ON p.id = q.created_by_player_id
WHERE q.id = ?
LIMIT 1
`

type GetQuizRow struct {
	ID                   int64
	Title                string
	Slug                 string
	Description          string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CreatedByPlayerID    int64
	TimeLimitSeconds     int64
	Visibility           string
	Mode                 string
	PlayCount            int64
	CreatedByDisplayName string
}

// Same INNER JOIN as ListQuizzes so single-quiz fetches carry the
// creator's display_name for the admin view's "Created by ..." line. See
// ListQuizzes for why the LEFT JOIN was dropped (#359).
func (q *Queries) GetQuiz(ctx context.Context, id int64) (GetQuizRow, error) {
	row := q.db.QueryRowContext(ctx, getQuiz, id)
	var i GetQuizRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByPlayerID,
		&i.TimeLimitSeconds,
		&i.Visibility,
		&i.Mode,
		&i.PlayCount,
		&i.CreatedByDisplayName,
	)
	return i, err
}

const getQuizVisibility = `-- name: GetQuizVisibility :one
SELECT visibility
FROM quizzes
WHERE id = ?
LIMIT 1
`

// Returns just the visibility column for a quiz. Used by the read-path
// visibility gate, which only needs visibility + existence and must not
// pay the questions/options fan-out that GetQuiz materialises.
func (q *Queries) GetQuizVisibility(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getQuizVisibility, id)
	var visibility string
	err := row.Scan(&visibility)
	return visibility, err
}

const listLiveQuizzes = `-- name: ListLiveQuizzes :many
SELECT q.id,
       q.title,
       q.slug,
       q.description,
       q.created_at,
       q.updated_at,
       q.created_by_player_id,
       q.time_limit_seconds,
       q.visibility,
       q.mode,
       q.play_count,
       p.display_name AS created_by_display_name
FROM quizzes q
         JOIN players p ON p.id = q.created_by_player_id
WHERE q.mode = 'live'
ORDER BY q.updated_at DESC, q.id DESC
`

type ListLiveQuizzesRow struct {
	ID                   int64
	Title                string
	Slug                 string
	Description          string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CreatedByPlayerID    int64
	TimeLimitSeconds     int64
	Visibility           string
	Mode                 string
	PlayCount            int64
	CreatedByDisplayName string
}

// Live-mode variant of ListQuizzes (#836). Filters to mode = 'live' so the
// host intermission picker only offers hostable quizzes. Visibility is left
// unfiltered, matching CreateSession, which gates a host on mode = 'live'
// alone (any live quiz is hostable, regardless of who created it).
func (q *Queries) ListLiveQuizzes(ctx context.Context) ([]ListLiveQuizzesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLiveQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveQuizzesRow
	for rows.Next() {
		var i ListLiveQuizzesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByPlayerID,
			&i.TimeLimitSeconds,
			&i.Visibility,
			&i.Mode,
			&i.PlayCount,
			&i.CreatedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionIDsByQuestionID = `-- name: ListOptionIDsByQuestionID :many
SELECT id
FROM options
WHERE question_id = ?
`

func (q *Queries) ListOptionIDsByQuestionID(ctx context.Context, questionID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listOptionIDsByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByQuestionID = `-- name: ListOptionsByQuestionID :many
SELECT id, question_id, text, is_correct
FROM options
WHERE question_id = ?
`

func (q *Queries) ListOptionsByQuestionID(ctx context.Context, questionID int64) ([]Option, error) {
	rows, err := q.db.QueryContext(ctx, listOptionsByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByQuizID = `-- name: ListOptionsByQuizID :many
SELECT o.id, o.question_id, o.text, o.is_correct
FROM options o
         JOIN questions q ON q.id = o.question_id
WHERE q.quiz_id = ?
ORDER BY o.question_id, o.id
`

// Returns every option for a quiz in one round-trip so callers can group
// options by question in Go instead of running one query per question.
func (q *Queries) ListOptionsByQuizID(ctx context.Context, quizID int64) ([]Option, error) {
	rows, err := q.db.QueryContext(ctx, listOptionsByQuizID, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicQuizzes = `-- name: ListPublicQuizzes :many
SELECT q.id,
       q.title,
       q.slug,
       q.description,
       q.created_at,
       q.updated_at,
       q.created_by_player_id,
       q.time_limit_seconds,
       q.visibility,
       q.mode,
       q.play_count,
       p.display_name AS created_by_display_name
FROM quizzes q
         JOIN players p ON p.id = q.created_by_player_id
WHERE q.visibility = 'public'
  AND q.mode = 'solo'
ORDER BY q.updated_at DESC, q.id DESC
`

type ListPublicQuizzesRow struct {
	ID                   int64
	Title                string
	Slug                 string
	Description          string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CreatedByPlayerID    int64
	TimeLimitSeconds     int64
	Visibility           string
	Mode                 string
	PlayCount            int64
	CreatedByDisplayName string
}

// Public-facing variant of ListQuizzes (#103). Filters to visibility =
// 'public' so unlisted and private quizzes never appear in the player
// client's quiz picker or on the home page's all-quizzes view. The
// mode = 'solo' filter (MP-0 / #677) keeps live (hosted-only) quizzes
// out of the solo browse paths too.
func (q *Queries) ListPublicQuizzes(ctx context.Context) ([]ListPublicQuizzesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublicQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicQuizzesRow
	for rows.Next() {
		var i ListPublicQuizzesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByPlayerID,
			&i.TimeLimitSeconds,
			&i.Visibility,
			&i.Mode,
			&i.PlayCount,
			&i.CreatedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionIDsByQuizID = `-- name: ListQuestionIDsByQuizID :many
SELECT id
FROM questions
WHERE quiz_id = ?
ORDER BY position
`

func (q *Queries) ListQuestionIDsByQuizID(ctx context.Context, quizID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionIDsByQuizID, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionIDsByRoundID = `-- name: ListQuestionIDsByRoundID :many
SELECT id
FROM questions
WHERE round_id = ?
ORDER BY position
`

// Lists the question IDs attached to a round, snapshotted up front by the
// round delete so it can clean up each question's dependent game_questions
// and game_answers rows before dropping the round. questions.round_id has
// ON DELETE CASCADE, but the played-game rows that reference those
// questions do not, so the round delete must wipe them in FK order first.
func (q *Queries) ListQuestionIDsByRoundID(ctx context.Context, roundID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionIDsByRoundID, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByQuizID = `-- name: ListQuestionsByQuizID :many
SELECT id, quiz_id, round_id, text, position, time_limit_seconds, image_media_id, audio_media_id, audio_repeat
FROM questions
WHERE quiz_id = ?
ORDER BY position
`

func (q *Queries) ListQuestionsByQuizID(ctx context.Context, quizID int64) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionsByQuizID, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.RoundID,
			&i.Text,
			&i.Position,
			&i.TimeLimitSeconds,
			&i.ImageMediaID,
			&i.AudioMediaID,
			&i.AudioRepeat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizzes = `-- name: ListQuizzes :many
SELECT q.id,
       q.title,
       q.slug,
       q.description,
       q.created_at,
       q.updated_at,
       q.created_by_player_id,
       q.time_limit_seconds,
       q.visibility,
       q.mode,
       q.play_count,
       p.display_name AS created_by_display_name
FROM quizzes q
         JOIN players p ON p.id = q.created_by_player_id
ORDER BY q.updated_at DESC, q.id DESC
`

type ListQuizzesRow struct {
	ID                   int64
	Title                string
	Slug                 string
	Description          string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	CreatedByPlayerID    int64
	TimeLimitSeconds     int64
	Visibility           string
	Mode                 string
	PlayCount            int64
	CreatedByDisplayName string
}

// INNER JOIN on players so the admin list can render "Created by ..."
// alongside each quiz without an N+1 lookup. created_by_player_id is
// NOT NULL (since migration 20260520200000 / #281) and references
// players(id) with no player-delete path, so the join always matches;
// the previous LEFT JOIN + sql.NullString in the wrapper was dead
// defensive code that masked a real invariant (#359). If a future
// migration adds player deletion, restore the LEFT JOIN with an
// explicit "Unknown" rendering instead of letting deleted-creator
// quizzes silently render a blank "Created by" line.
//
// visibility comes back unfiltered so the admin list can show every
// row regardless of who can play it; the public-facing API filters
// explicitly via ListPublicQuizzes (#103).
func (q *Queries) ListQuizzes(ctx context.Context) ([]ListQuizzesRow, error) {
	rows, err := q.db.QueryContext(ctx, listQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuizzesRow
	for rows.Next() {
		var i ListQuizzesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByPlayerID,
			&i.TimeLimitSeconds,
			&i.Visibility,
			&i.Mode,
			&i.PlayCount,
			&i.CreatedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxQuestionPosition = `-- name: MaxQuestionPosition :one
SELECT CAST(COALESCE(MAX(position), 0) AS INTEGER) AS max_position
FROM questions
WHERE quiz_id = ?
`

// Returns the highest position in use for the given quiz, or 0 when the
// quiz has no questions yet. The CAST + COALESCE forces sqlc to type
// the result as int64 instead of interface{} (raw MAX can return NULL).
// Callers add 1 to get the next-position to assign on a new question.
func (q *Queries) MaxQuestionPosition(ctx context.Context, quizID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxQuestionPosition, quizID)
	var max_position int64
	err := row.Scan(&max_position)
	return max_position, err
}

const moveQuestionToRound = `-- name: MoveQuestionToRound :execresult
UPDATE questions
SET round_id = ?
WHERE id = ?
`

type MoveQuestionToRoundParams struct {
	RoundID int64
	ID      int64
}

// Reassigns a question to a different round within the same quiz (#444).
// Position is unchanged - questions stay in quiz-wide position order, so
// a round change is a single column rewrite.
func (q *Queries) MoveQuestionToRound(ctx context.Context, arg MoveQuestionToRoundParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, moveQuestionToRound, arg.RoundID, arg.ID)
}

const questionCountsByQuiz = `-- name: QuestionCountsByQuiz :many
SELECT quiz_id, COUNT(*) AS question_count
FROM questions
GROUP BY quiz_id
`

type QuestionCountsByQuizRow struct {
	QuizID        int64
	QuestionCount int64
}

// Returns one row per quiz that has at least one question. Quizzes with
// zero questions are absent; callers should treat a missing entry as 0.
// Used by the admin list to render "{N} questions" alongside ListQuizzes
// without coupling the count into the Quiz domain type.
func (q *Queries) QuestionCountsByQuiz(ctx context.Context) ([]QuestionCountsByQuizRow, error) {
	rows, err := q.db.QueryContext(ctx, questionCountsByQuiz)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionCountsByQuizRow
	for rows.Next() {
		var i QuestionCountsByQuizRow
		if err := rows.Scan(&i.QuizID, &i.QuestionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quizExists = `-- name: QuizExists :one
SELECT EXISTS(SELECT 1 FROM quizzes WHERE id = ?) AS quiz_exists
`

// Cheap existence check for a quiz by ID. Returns 1 when the row exists,
// 0 otherwise. Used by handlers and services that need to validate the
// quiz is real before doing further work but do not need the full tree
// of questions and options that GetQuiz materialises.
func (q *Queries) QuizExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, quizExists, id)
	var quiz_exists bool
	err := row.Scan(&quiz_exists)
	return quiz_exists, err
}

const updateOption = `-- name: UpdateOption :execresult
UPDATE options
SET text = ?,
    is_correct = ?
WHERE id = ?
`

type UpdateOptionParams struct {
	Text      string
	IsCorrect bool
	ID        int64
}

func (q *Queries) UpdateOption(ctx context.Context, arg UpdateOptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateOption, arg.Text, arg.IsCorrect, arg.ID)
}

const updateQuestion = `-- name: UpdateQuestion :execresult
UPDATE questions
SET text               = ?,
    position           = ?,
    image_media_id     = ?,
    audio_media_id     = ?,
    audio_repeat       = ?,
    time_limit_seconds = ?
WHERE id = ?
`

type UpdateQuestionParams struct {
	Text             string
	Position         int64
	ImageMediaID     sql.NullInt64
	AudioMediaID     sql.NullInt64
	AudioRepeat      int64
	TimeLimitSeconds sql.NullInt64
	ID               int64
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateQuestion,
		arg.Text,
		arg.Position,
		arg.ImageMediaID,
		arg.AudioMediaID,
		arg.AudioRepeat,
		arg.TimeLimitSeconds,
		arg.ID,
	)
}

const updateQuestionPosition = `-- name: UpdateQuestionPosition :execresult
UPDATE questions
SET position = ?
WHERE id = ?
`

type UpdateQuestionPositionParams struct {
	Position int64
	ID       int64
}

// Position-only update. Used by the reorder flow (#16) to swap a pair
// of questions atomically inside a transaction without rewriting the
// text/image fields.
func (q *Queries) UpdateQuestionPosition(ctx context.Context, arg UpdateQuestionPositionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateQuestionPosition, arg.Position, arg.ID)
}

const updateQuiz = `-- name: UpdateQuiz :execresult
UPDATE quizzes
SET title              = ?,
    slug               = ?,
    description        = ?,
    time_limit_seconds = ?,
    visibility         = ?,
    mode               = ?,
    updated_at         = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateQuizParams struct {
	Title            string
	Slug             string
	Description      string
	TimeLimitSeconds int64
	Visibility       string
	Mode             string
	ID               int64
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateQuiz,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.TimeLimitSeconds,
		arg.Visibility,
		arg.Mode,
		arg.ID,
	)
}

const updateQuizMode = `-- name: UpdateQuizMode :execresult
UPDATE quizzes
SET mode       = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateQuizModeParams struct {
	Mode string
	ID   int64
}

// Flips just the play mode without touching the question tree, so the
// solo/live toggle (#830) cannot clobber a concurrent question edit the way
// the full UpdateQuiz would.
func (q *Queries) UpdateQuizMode(ctx context.Context, arg UpdateQuizModeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateQuizMode, arg.Mode, arg.ID)
}
