// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quizzes.sql

package db

import (
	"context"
	"database/sql"
)

const createOption = `-- name: CreateOption :one
INSERT INTO options (question_id, text, is_correct)
VALUES (?, ?, ?)
RETURNING id, question_id, text, is_correct
`

type CreateOptionParams struct {
	QuestionID int64
	Text       string
	IsCorrect  bool
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error) {
	row := q.db.QueryRowContext(ctx, createOption, arg.QuestionID, arg.Text, arg.IsCorrect)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (quiz_id, text, position)
VALUES (?, ?, ?)
RETURNING id, quiz_id, text, position
`

type CreateQuestionParams struct {
	QuizID   int64
	Text     string
	Position int64
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion, arg.QuizID, arg.Text, arg.Position)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Text,
		&i.Position,
	)
	return i, err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (title, slug, description)
VALUES (?, ?, ?)
RETURNING id, title, slug, description, created_at
`

type CreateQuizParams struct {
	Title       string
	Slug        string
	Description string
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, createQuiz, arg.Title, arg.Slug, arg.Description)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOption = `-- name: DeleteOption :execresult
DELETE FROM options
WHERE id = ?
`

func (q *Queries) DeleteOption(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOption, id)
}

const deleteQuestion = `-- name: DeleteQuestion :execresult
DELETE FROM questions
WHERE id = ?
`

func (q *Queries) DeleteQuestion(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteQuestion, id)
}

const deleteQuiz = `-- name: DeleteQuiz :execresult
DELETE
FROM quizzes
WHERE id = ?
`

func (q *Queries) DeleteQuiz(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteQuiz, id)
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, quiz_id, text, position
FROM questions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetQuestion(ctx context.Context, id int64) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Text,
		&i.Position,
	)
	return i, err
}

const getQuiz = `-- name: GetQuiz :one
SELECT id, title, slug, description, created_at
FROM quizzes
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetQuiz(ctx context.Context, id int64) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, getQuiz, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listOptionIDsByQuestionID = `-- name: ListOptionIDsByQuestionID :many
SELECT id
FROM options
WHERE question_id = ?
`

func (q *Queries) ListOptionIDsByQuestionID(ctx context.Context, questionID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listOptionIDsByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByQuestionID = `-- name: ListOptionsByQuestionID :many
SELECT id, question_id, text, is_correct
FROM options
WHERE question_id = ?
`

func (q *Queries) ListOptionsByQuestionID(ctx context.Context, questionID int64) ([]Option, error) {
	rows, err := q.db.QueryContext(ctx, listOptionsByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionIDsByQuizID = `-- name: ListQuestionIDsByQuizID :many
SELECT id
FROM questions
WHERE quiz_id = ?
ORDER BY position
`

func (q *Queries) ListQuestionIDsByQuizID(ctx context.Context, quizID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionIDsByQuizID, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByQuizID = `-- name: ListQuestionsByQuizID :many
SELECT id, quiz_id, text, position
FROM questions
WHERE quiz_id = ?
ORDER BY position
`

func (q *Queries) ListQuestionsByQuizID(ctx context.Context, quizID int64) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionsByQuizID, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Text,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizzes = `-- name: ListQuizzes :many
SELECT id, title, slug, description, created_at
FROM quizzes
ORDER BY id
`

func (q *Queries) ListQuizzes(ctx context.Context) ([]Quiz, error) {
	rows, err := q.db.QueryContext(ctx, listQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quiz
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOption = `-- name: UpdateOption :execresult
UPDATE options
SET text = ?,
    is_correct = ?
WHERE id = ?
`

type UpdateOptionParams struct {
	Text      string
	IsCorrect bool
	ID        int64
}

func (q *Queries) UpdateOption(ctx context.Context, arg UpdateOptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateOption, arg.Text, arg.IsCorrect, arg.ID)
}

const updateQuestion = `-- name: UpdateQuestion :execresult
UPDATE questions
SET text = ?,
    position = ?
WHERE id = ?
`

type UpdateQuestionParams struct {
	Text     string
	Position int64
	ID       int64
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateQuestion, arg.Text, arg.Position, arg.ID)
}

const updateQuiz = `-- name: UpdateQuiz :execresult
UPDATE quizzes
SET title       = ?,
    slug        = ?,
    description = ?
WHERE id = ?
`

type UpdateQuizParams struct {
	Title       string
	Slug        string
	Description string
	ID          int64
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateQuiz,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ID,
	)
}
