// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quizzes.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createOption = `-- name: CreateOption :one
INSERT INTO options (question_id, text, is_correct)
VALUES (?, ?, ?)
RETURNING id, question_id, text, is_correct
`

type CreateOptionParams struct {
	QuestionID int64
	Text       string
	IsCorrect  bool
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error) {
	row := q.db.QueryRowContext(ctx, createOption, arg.QuestionID, arg.Text, arg.IsCorrect)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (quiz_id, text, position, image_url)
VALUES (?, ?, ?, ?)
RETURNING id, quiz_id, text, position, image_url
`

type CreateQuestionParams struct {
	QuizID   int64
	Text     string
	Position int64
	ImageUrl string
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion,
		arg.QuizID,
		arg.Text,
		arg.Position,
		arg.ImageUrl,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Text,
		&i.Position,
		&i.ImageUrl,
	)
	return i, err
}

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (title, slug, description, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, title, slug, description, created_at, updated_at
`

type CreateQuizParams struct {
	Title       string
	Slug        string
	Description string
}

func (q *Queries) CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, createQuiz, arg.Title, arg.Slug, arg.Description)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOption = `-- name: DeleteOption :execresult
DELETE FROM options
WHERE id = ?
`

func (q *Queries) DeleteOption(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOption, id)
}

const deleteQuestion = `-- name: DeleteQuestion :execresult
DELETE FROM questions
WHERE id = ?
`

func (q *Queries) DeleteQuestion(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteQuestion, id)
}

const deleteQuiz = `-- name: DeleteQuiz :execresult
DELETE
FROM quizzes
WHERE id = ?
`

func (q *Queries) DeleteQuiz(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteQuiz, id)
}

const getOption = `-- name: GetOption :one
SELECT id, question_id, text, is_correct
FROM options
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetOption(ctx context.Context, id int64) (Option, error) {
	row := q.db.QueryRowContext(ctx, getOption, id)
	var i Option
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
	)
	return i, err
}

const getOptionsByIDs = `-- name: GetOptionsByIDs :many
SELECT id, question_id, text, is_correct
FROM options
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetOptionsByIDs(ctx context.Context, ids []int64) ([]Option, error) {
	query := getOptionsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, quiz_id, text, position, image_url
FROM questions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetQuestion(ctx context.Context, id int64) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Text,
		&i.Position,
		&i.ImageUrl,
	)
	return i, err
}

const getQuiz = `-- name: GetQuiz :one
SELECT id, title, slug, description, created_at, updated_at
FROM quizzes
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetQuiz(ctx context.Context, id int64) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, getQuiz, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOptionIDsByQuestionID = `-- name: ListOptionIDsByQuestionID :many
SELECT id
FROM options
WHERE question_id = ?
`

func (q *Queries) ListOptionIDsByQuestionID(ctx context.Context, questionID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listOptionIDsByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByQuestionID = `-- name: ListOptionsByQuestionID :many
SELECT id, question_id, text, is_correct
FROM options
WHERE question_id = ?
`

func (q *Queries) ListOptionsByQuestionID(ctx context.Context, questionID int64) ([]Option, error) {
	rows, err := q.db.QueryContext(ctx, listOptionsByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionIDsByQuizID = `-- name: ListQuestionIDsByQuizID :many
SELECT id
FROM questions
WHERE quiz_id = ?
ORDER BY position
`

func (q *Queries) ListQuestionIDsByQuizID(ctx context.Context, quizID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionIDsByQuizID, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByQuizID = `-- name: ListQuestionsByQuizID :many
SELECT id, quiz_id, text, position, image_url
FROM questions
WHERE quiz_id = ?
ORDER BY position
`

func (q *Queries) ListQuestionsByQuizID(ctx context.Context, quizID int64) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionsByQuizID, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Text,
			&i.Position,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizzes = `-- name: ListQuizzes :many
SELECT id, title, slug, description, created_at, updated_at
FROM quizzes
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListQuizzes(ctx context.Context) ([]Quiz, error) {
	rows, err := q.db.QueryContext(ctx, listQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quiz
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const questionCountsByQuiz = `-- name: QuestionCountsByQuiz :many
SELECT quiz_id, COUNT(*) AS question_count
FROM questions
GROUP BY quiz_id
`

type QuestionCountsByQuizRow struct {
	QuizID        int64
	QuestionCount int64
}

// Returns one row per quiz that has at least one question. Quizzes with
// zero questions are absent; callers should treat a missing entry as 0.
// Used by the admin list to render "{N} questions" alongside ListQuizzes
// without coupling the count into the Quiz domain type.
func (q *Queries) QuestionCountsByQuiz(ctx context.Context) ([]QuestionCountsByQuizRow, error) {
	rows, err := q.db.QueryContext(ctx, questionCountsByQuiz)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionCountsByQuizRow
	for rows.Next() {
		var i QuestionCountsByQuizRow
		if err := rows.Scan(&i.QuizID, &i.QuestionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOption = `-- name: UpdateOption :execresult
UPDATE options
SET text = ?,
    is_correct = ?
WHERE id = ?
`

type UpdateOptionParams struct {
	Text      string
	IsCorrect bool
	ID        int64
}

func (q *Queries) UpdateOption(ctx context.Context, arg UpdateOptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateOption, arg.Text, arg.IsCorrect, arg.ID)
}

const updateQuestion = `-- name: UpdateQuestion :execresult
UPDATE questions
SET text = ?,
    position = ?,
    image_url = ?
WHERE id = ?
`

type UpdateQuestionParams struct {
	Text     string
	Position int64
	ImageUrl string
	ID       int64
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateQuestion,
		arg.Text,
		arg.Position,
		arg.ImageUrl,
		arg.ID,
	)
}

const updateQuiz = `-- name: UpdateQuiz :execresult
UPDATE quizzes
SET title       = ?,
    slug        = ?,
    description = ?,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateQuizParams struct {
	Title       string
	Slug        string
	Description string
	ID          int64
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateQuiz,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ID,
	)
}
