// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package db

import (
	"context"
	"strings"
)

const deletePlayersByIDs = `-- name: DeletePlayersByIDs :exec
DELETE
FROM players
WHERE id IN (/*SLICE:ids*/?)
  AND role = 'player'
  AND email IS NULL
  AND password_hash IS NULL
  AND display_name_claimed = 0
`

// Hard-deletes the given player rows. Run last in the anonymous-player
// sweep, after every game_* row that references them has been removed.
// Re-asserts the anonymity predicate so the delete is a no-op for any id
// that was claimed (registered, verified, or renamed) between the snapshot
// and this delete (#1175): a guest active in that TOCTOU window survives.
func (q *Queries) DeletePlayersByIDs(ctx context.Context, ids []int64) error {
	query := deletePlayersByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const listAbandonedGameIDs = `-- name: ListAbandonedGameIDs :many
SELECT g.id
FROM games g
WHERE g.created_at < datetime('now', '-' || CAST(?1 AS INTEGER) || ' days')
  AND NOT (
        (SELECT COUNT(*) FROM questions qc WHERE qc.quiz_id = g.quiz_id) > 0
    AND (SELECT COUNT(*) FROM game_questions gqc WHERE gqc.game_id = g.id) >=
        (SELECT COUNT(*) FROM questions qc WHERE qc.quiz_id = g.quiz_id)
  )
`

// Lists ids of games that are NOT finished and were created more than 30
// days ago (#627). A game is "finished" when every question of its quiz
// has been issued as a game_question -- the same finisher predicate the
// leaderboard queries use. created_at is used (not started_at) because
// started_at is NULL for a game that was created but never started, and
// such a game is exactly the kind of abandonment this sweep prunes. The
// window in days is a caller-supplied integer, but the cutoff is computed
// in SQL (datetime('now', '-<days> days')) so both sides of the comparison
// are SQLite text in the CURRENT_TIMESTAMP encoding rows are minted with,
// not a cross-format Go time.Time comparison.
func (q *Queries) ListAbandonedGameIDs(ctx context.Context, days int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAbandonedGameIDs, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameIDsForPlayers = `-- name: ListGameIDsForPlayers :many
SELECT DISTINCT gp.game_id
FROM game_participants gp
WHERE gp.player_id IN (/*SLICE:player_ids*/?)
`

// Lists every distinct game id any of the given players participates in.
// The anonymous-player sweep snapshots these up front so the dependent
// game_* deletes hit a stable set as the participant rows drain (#626).
func (q *Queries) ListGameIDsForPlayers(ctx context.Context, playerIds []int64) ([]string, error) {
	query := listGameIDsForPlayers
	var queryParams []interface{}
	if len(playerIds) > 0 {
		for _, v := range playerIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:player_ids*/?", strings.Repeat(",?", len(playerIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:player_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var game_id string
		if err := rows.Scan(&game_id); err != nil {
			return nil, err
		}
		items = append(items, game_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleAnonymousPlayerIDs = `-- name: ListStaleAnonymousPlayerIDs :many
SELECT p.id
FROM players p
WHERE p.role = 'player'
  AND p.email IS NULL
  AND p.password_hash IS NULL
  AND p.display_name_claimed = 0
  AND p.created_at < datetime('now', '-' || CAST(?1 AS INTEGER) || ' days')
  AND NOT EXISTS (
        SELECT 1
        FROM game_participants gp
                 JOIN games g ON g.id = gp.game_id
        WHERE gp.player_id = p.id
          AND (SELECT COUNT(*) FROM questions qc WHERE qc.quiz_id = g.quiz_id) > 0
          AND (SELECT COUNT(*) FROM game_questions gqc WHERE gqc.game_id = g.id) >=
              (SELECT COUNT(*) FROM questions qc WHERE qc.quiz_id = g.quiz_id)
  )
`

// Lists ids of anonymous players minted more than 90 days ago that hold no
// finished game. "Anonymous" is a guest who never claimed an account:
// role 'player' with no email, no password, and a display name still
// auto-generated (display_name_claimed = 0). created_at is the mint time
// (there is no last-seen column), so the cutoff is "minted more than the
// retention window ago". The window in days is a caller-supplied integer,
// but the cutoff is computed in SQL (datetime('now', '-<days> days')) so
// both sides of the comparison are SQLite text in the CURRENT_TIMESTAMP
// encoding rows are minted with; a bound Go time.Time would arrive in the
// driver's time.Time.String() text encoding and the cross-format
// comparison would silently lie. A
// guest with a finished game is kept regardless of age so the sweep never
// erases a leaderboard score (#626); "finished" is every question of the
// quiz issued as a game_question, the same finisher predicate the
// leaderboard uses.
func (q *Queries) ListStaleAnonymousPlayerIDs(ctx context.Context, days int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listStaleAnonymousPlayerIDs, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
