// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rounds.sql

package db

import (
	"context"
	"database/sql"
)

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (quiz_id, position, title, summary)
VALUES (?, ?, ?, ?)
RETURNING id, quiz_id, position, title, summary, created_at, updated_at
`

type CreateRoundParams struct {
	QuizID   int64
	Position int64
	Title    string
	Summary  string
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRowContext(ctx, createRound,
		arg.QuizID,
		arg.Position,
		arg.Title,
		arg.Summary,
	)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Position,
		&i.Title,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRound = `-- name: DeleteRound :execresult
DELETE FROM rounds
WHERE id = ?
`

func (q *Queries) DeleteRound(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRound, id)
}

const getDefaultRound = `-- name: GetDefaultRound :one
SELECT id, quiz_id, position, title, summary, created_at, updated_at
FROM rounds
WHERE quiz_id = ?
ORDER BY position
LIMIT 1
`

// Returns the lowest-position round for a quiz. Every quiz has at least
// one round (the default 'Round 1' created by migration
// 20260530000000), so question-insert paths resolve the round to attach
// a new question to via this query until slice 3 adds real round
// selection.
func (q *Queries) GetDefaultRound(ctx context.Context, quizID int64) (Round, error) {
	row := q.db.QueryRowContext(ctx, getDefaultRound, quizID)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Position,
		&i.Title,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRound = `-- name: GetRound :one
SELECT id, quiz_id, position, title, summary, created_at, updated_at
FROM rounds
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetRound(ctx context.Context, id int64) (Round, error) {
	row := q.db.QueryRowContext(ctx, getRound, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.Position,
		&i.Title,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoundsByQuiz = `-- name: ListRoundsByQuiz :many
SELECT id, quiz_id, position, title, summary, created_at, updated_at
FROM rounds
WHERE quiz_id = ?
ORDER BY position
`

func (q *Queries) ListRoundsByQuiz(ctx context.Context, quizID int64) ([]Round, error) {
	rows, err := q.db.QueryContext(ctx, listRoundsByQuiz, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Round
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Position,
			&i.Title,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRound = `-- name: UpdateRound :execresult
UPDATE rounds
SET title      = ?,
    summary = ?,
    position   = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateRoundParams struct {
	Title    string
	Summary  string
	Position int64
	ID       int64
}

func (q *Queries) UpdateRound(ctx context.Context, arg UpdateRoundParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRound,
		arg.Title,
		arg.Summary,
		arg.Position,
		arg.ID,
	)
}

const updateRoundPosition = `-- name: UpdateRoundPosition :execresult
UPDATE rounds
SET position = ?
WHERE id = ?
`

type UpdateRoundPositionParams struct {
	Position int64
	ID       int64
}

// Position-only update used by the per-row up/down reorder buttons.
// Mirrors UpdateBreakPosition so the move path can rewrite a single
// column without touching title/summary or updated_at - the reorder
// is not a content edit.
func (q *Queries) UpdateRoundPosition(ctx context.Context, arg UpdateRoundPositionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRoundPosition, arg.Position, arg.ID)
}
