// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, quiz_id, host_player_id, join_code)
VALUES (?, ?, ?, ?)
RETURNING id, quiz_id, host_player_id, join_code, phase, created_at, started_at, finished_at
`

type CreateSessionParams struct {
	ID           string
	QuizID       int64
	HostPlayerID int64
	JoinCode     string
}

// Inserts a hosted session. id is an xid generated by the store; join_code
// is the collision-checked short code minted by the domain layer. phase
// defaults to 'lobby' at the DB level. A duplicate join_code trips the
// UNIQUE constraint, which the store surfaces so the caller can regenerate.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.QuizID,
		arg.HostPlayerID,
		arg.JoinCode,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.HostPlayerID,
		&i.JoinCode,
		&i.Phase,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, quiz_id, host_player_id, join_code, phase, created_at, started_at, finished_at
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.HostPlayerID,
		&i.JoinCode,
		&i.Phase,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getSessionByJoinCode = `-- name: GetSessionByJoinCode :one
SELECT id, quiz_id, host_player_id, join_code, phase, created_at, started_at, finished_at
FROM sessions
WHERE join_code = ?
`

// Resolves a typed/scanned room code to its session. join_code is UNIQUE so
// this returns at most one row.
func (q *Queries) GetSessionByJoinCode(ctx context.Context, joinCode string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByJoinCode, joinCode)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.HostPlayerID,
		&i.JoinCode,
		&i.Phase,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getSessionPlayer = `-- name: GetSessionPlayer :one
SELECT id, session_id, player_id, display_name, is_ready, joined_at, last_seen_at, left_at
FROM session_players
WHERE session_id = ?
  AND player_id = ?
`

type GetSessionPlayerParams struct {
	SessionID string
	PlayerID  int64
}

func (q *Queries) GetSessionPlayer(ctx context.Context, arg GetSessionPlayerParams) (SessionPlayer, error) {
	row := q.db.QueryRowContext(ctx, getSessionPlayer, arg.SessionID, arg.PlayerID)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.DisplayName,
		&i.IsReady,
		&i.JoinedAt,
		&i.LastSeenAt,
		&i.LeftAt,
	)
	return i, err
}

const joinCodeExists = `-- name: JoinCodeExists :one
SELECT EXISTS(SELECT 1 FROM sessions WHERE join_code = ?) AS code_exists
`

// Cheap existence probe for a candidate join code so the generator can
// regenerate on collision before paying for the INSERT.
func (q *Queries) JoinCodeExists(ctx context.Context, joinCode string) (bool, error) {
	row := q.db.QueryRowContext(ctx, joinCodeExists, joinCode)
	var code_exists bool
	err := row.Scan(&code_exists)
	return code_exists, err
}

const listSessionPlayers = `-- name: ListSessionPlayers :many
SELECT id, session_id, player_id, display_name, is_ready, joined_at, last_seen_at, left_at
FROM session_players
WHERE session_id = ?
  AND left_at IS NULL
ORDER BY joined_at, id
`

// The lobby roster in join order. Excludes players who have left (left_at
// set, MP-10) so the lobby shows the current room.
func (q *Queries) ListSessionPlayers(ctx context.Context, sessionID string) ([]SessionPlayer, error) {
	rows, err := q.db.QueryContext(ctx, listSessionPlayers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionPlayer
	for rows.Next() {
		var i SessionPlayer
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PlayerID,
			&i.DisplayName,
			&i.IsReady,
			&i.JoinedAt,
			&i.LastSeenAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionPlayerReady = `-- name: SetSessionPlayerReady :execresult
UPDATE session_players
SET is_ready     = ?,
    last_seen_at = CURRENT_TIMESTAMP
WHERE session_id = ?
  AND player_id = ?
`

type SetSessionPlayerReadyParams struct {
	IsReady   int64
	SessionID string
	PlayerID  int64
}

// Toggles a participant's ready flag and refreshes last_seen_at. Scoped to
// (session_id, player_id) so it only ever touches the caller's own roster
// row. The execresult lets the store map zero rows affected to "not a
// participant".
func (q *Queries) SetSessionPlayerReady(ctx context.Context, arg SetSessionPlayerReadyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setSessionPlayerReady, arg.IsReady, arg.SessionID, arg.PlayerID)
}

const upsertSessionPlayer = `-- name: UpsertSessionPlayer :one
INSERT INTO session_players (session_id, player_id, display_name)
VALUES (?, ?, ?)
ON CONFLICT (session_id, player_id)
    DO UPDATE SET display_name = excluded.display_name,
                  left_at      = NULL,
                  last_seen_at = CURRENT_TIMESTAMP
RETURNING id, session_id, player_id, display_name, is_ready, joined_at, last_seen_at, left_at
`

type UpsertSessionPlayerParams struct {
	SessionID   string
	PlayerID    int64
	DisplayName string
}

// Adds a player to a session's roster, or revives an existing row on
// re-join (clearing left_at and refreshing last_seen_at + display_name).
// A per-session display-name collision trips UNIQUE (session_id,
// display_name); the caller retries with a petname. The (session_id,
// player_id) UNIQUE makes the upsert idempotent for the same player.
func (q *Queries) UpsertSessionPlayer(ctx context.Context, arg UpsertSessionPlayerParams) (SessionPlayer, error) {
	row := q.db.QueryRowContext(ctx, upsertSessionPlayer, arg.SessionID, arg.PlayerID, arg.DisplayName)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.DisplayName,
		&i.IsReady,
		&i.JoinedAt,
		&i.LastSeenAt,
		&i.LeftAt,
	)
	return i, err
}
