// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const armSessionStart = `-- name: ArmSessionStart :execresult
UPDATE sessions
SET start_at = ?
WHERE id = ?
  AND started_at IS NULL
`

type ArmSessionStartParams struct {
	StartAt sql.NullTime
	ID      string
}

// Arms the host's last-call countdown: stamps start_at with the absolute
// server deadline at which the runner begins the game. Scoped to a session
// still in the lobby (started_at IS NULL, the same "not yet begun" gate
// StartSession uses) so arming a started game is a no-op; re-arming while in
// the lobby overwrites the deadline (the host can re-arm). The execresult lets
// the store map zero rows affected to "not in the lobby".
func (q *Queries) ArmSessionStart(ctx context.Context, arg ArmSessionStartParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, armSessionStart, arg.StartAt, arg.ID)
}

const cancelSessionStart = `-- name: CancelSessionStart :execresult
UPDATE sessions
SET start_at = NULL
WHERE id = ?
  AND started_at IS NULL
`

// Cancels an armed last-call countdown by clearing start_at. Scoped to a
// session still in the lobby (started_at IS NULL) so a cancel after the game
// has begun is a no-op. The execresult lets the store map zero rows affected
// to "not in the lobby".
func (q *Queries) CancelSessionStart(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, cancelSessionStart, id)
}

const countActivePlayersForSession = `-- name: CountActivePlayersForSession :one
SELECT count(*) AS active_count
FROM session_players sp
WHERE sp.session_id = ?1
  AND sp.left_at IS NULL
  AND sp.last_seen_at >= CAST(?2 AS TEXT)
`

type CountActivePlayersForSessionParams struct {
	SessionID string
	Since     string
}

// Number of roster players still active (last_seen_at within the heartbeat
// window), excluding those who have left. Lets the runner tell an empty / all-
// stale roster (which must time out, never early-close) from a roster with at
// least one active player. since is the active-window cutoff the runner computes
// from its injected clock, bound as a CURRENT_TIMESTAMP-format text string (see
// CountActivePlayersUnansweredForQuestion for why a bound time.Time is wrong).
func (q *Queries) CountActivePlayersForSession(ctx context.Context, arg CountActivePlayersForSessionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivePlayersForSession, arg.SessionID, arg.Since)
	var active_count int64
	err := row.Scan(&active_count)
	return active_count, err
}

const countActivePlayersUnansweredForQuestion = `-- name: CountActivePlayersUnansweredForQuestion :one
SELECT count(*) AS unanswered_count
FROM session_players sp
WHERE sp.session_id = ?1
  AND sp.left_at IS NULL
  AND sp.last_seen_at >= CAST(?2 AS TEXT)
  AND NOT EXISTS (
      SELECT 1
      FROM session_answers sa
      WHERE sa.session_id = sp.session_id
        AND sa.question_id = ?3
        AND sa.player_id = sp.player_id
  )
`

type CountActivePlayersUnansweredForQuestionParams struct {
	SessionID  string
	Since      string
	QuestionID int64
}

// Number of roster players who are still active (last_seen_at within the
// heartbeat window) but have not yet picked for the given session question. The
// runner early-closes a question once this reaches 0, so a dropped player whose
// last_seen_at has gone stale no longer holds the question open. Excludes
// players who have left (left_at set). since is the active-window cutoff the
// runner computes from its injected clock, bound as a CURRENT_TIMESTAMP-format
// text string ('YYYY-MM-DD HH:MM:SS') so both sides of the comparison share the
// encoding last_seen_at is stored in; a bound Go time.Time would arrive in a
// different format and the cross-format string comparison would silently lie
// (the same trap retention.sql documents).
func (q *Queries) CountActivePlayersUnansweredForQuestion(ctx context.Context, arg CountActivePlayersUnansweredForQuestionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivePlayersUnansweredForQuestion, arg.SessionID, arg.Since, arg.QuestionID)
	var unanswered_count int64
	err := row.Scan(&unanswered_count)
	return unanswered_count, err
}

const countSessionAnswersForQuestion = `-- name: CountSessionAnswersForQuestion :one
SELECT count(*) AS answer_count
FROM session_answers
WHERE session_id = ?
  AND question_id = ?
`

type CountSessionAnswersForQuestionParams struct {
	SessionID  string
	QuestionID int64
}

// Number of players who have picked for the given session question. The runner
// closes a question early once this reaches the active-player count.
func (q *Queries) CountSessionAnswersForQuestion(ctx context.Context, arg CountSessionAnswersForQuestionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionAnswersForQuestion, arg.SessionID, arg.QuestionID)
	var answer_count int64
	err := row.Scan(&answer_count)
	return answer_count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, quiz_id, host_player_id, join_code)
VALUES (?, ?, ?, ?)
RETURNING id, quiz_id, host_player_id, join_code, phase, current_round_id, current_question_id, question_started_at, question_expires_at, created_at, started_at, finished_at, host_last_seen_at, start_at
`

type CreateSessionParams struct {
	ID           string
	QuizID       int64
	HostPlayerID int64
	JoinCode     string
}

// Inserts a hosted session. id is an xid generated by the store; join_code
// is the collision-checked short code minted by the domain layer. phase
// defaults to 'lobby' at the DB level. A duplicate join_code trips the
// UNIQUE constraint, which the store surfaces so the caller can regenerate.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.QuizID,
		arg.HostPlayerID,
		arg.JoinCode,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.HostPlayerID,
		&i.JoinCode,
		&i.Phase,
		&i.CurrentRoundID,
		&i.CurrentQuestionID,
		&i.QuestionStartedAt,
		&i.QuestionExpiresAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HostLastSeenAt,
		&i.StartAt,
	)
	return i, err
}

const deleteSessionAnswersForPlayerOnQuiz = `-- name: DeleteSessionAnswersForPlayerOnQuiz :exec
DELETE FROM session_answers
WHERE player_id = ?1
  AND session_id IN (SELECT id FROM sessions WHERE quiz_id = ?2)
`

type DeleteSessionAnswersForPlayerOnQuizParams struct {
	PlayerID int64
	QuizID   int64
}

// Hard-deletes the player's recorded picks across every session of the given
// quiz. Run before DeleteSessionPlayersForPlayerOnQuiz so the answer rows go
// first (session_answers has no FK to session_players, so order is not
// enforced, but deleting children-then-roster reads cleanly).
func (q *Queries) DeleteSessionAnswersForPlayerOnQuiz(ctx context.Context, arg DeleteSessionAnswersForPlayerOnQuizParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionAnswersForPlayerOnQuiz, arg.PlayerID, arg.QuizID)
	return err
}

const deleteSessionPlayersForPlayerOnQuiz = `-- name: DeleteSessionPlayersForPlayerOnQuiz :exec
DELETE FROM session_players
WHERE player_id = ?1
  AND session_id IN (SELECT id FROM sessions WHERE quiz_id = ?2)
`

type DeleteSessionPlayersForPlayerOnQuizParams struct {
	PlayerID int64
	QuizID   int64
}

// Hard-deletes the player's roster rows across every session of the given
// quiz, clearing the replay gate so the player can join a new session of it.
func (q *Queries) DeleteSessionPlayersForPlayerOnQuiz(ctx context.Context, arg DeleteSessionPlayersForPlayerOnQuizParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionPlayersForPlayerOnQuiz, arg.PlayerID, arg.QuizID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, quiz_id, host_player_id, join_code, phase, current_round_id, current_question_id, question_started_at, question_expires_at, created_at, started_at, finished_at, host_last_seen_at, start_at
FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.HostPlayerID,
		&i.JoinCode,
		&i.Phase,
		&i.CurrentRoundID,
		&i.CurrentQuestionID,
		&i.QuestionStartedAt,
		&i.QuestionExpiresAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HostLastSeenAt,
		&i.StartAt,
	)
	return i, err
}

const getSessionByJoinCode = `-- name: GetSessionByJoinCode :one
SELECT id, quiz_id, host_player_id, join_code, phase, current_round_id, current_question_id, question_started_at, question_expires_at, created_at, started_at, finished_at, host_last_seen_at, start_at
FROM sessions
WHERE join_code = ?
`

// Resolves a typed/scanned room code to its session. join_code is UNIQUE so
// this returns at most one row.
func (q *Queries) GetSessionByJoinCode(ctx context.Context, joinCode string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByJoinCode, joinCode)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.QuizID,
		&i.HostPlayerID,
		&i.JoinCode,
		&i.Phase,
		&i.CurrentRoundID,
		&i.CurrentQuestionID,
		&i.QuestionStartedAt,
		&i.QuestionExpiresAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.HostLastSeenAt,
		&i.StartAt,
	)
	return i, err
}

const getSessionPlayer = `-- name: GetSessionPlayer :one
SELECT id, session_id, player_id, is_ready, joined_at, last_seen_at, left_at
FROM session_players
WHERE session_id = ?
  AND player_id = ?
`

type GetSessionPlayerParams struct {
	SessionID string
	PlayerID  int64
}

func (q *Queries) GetSessionPlayer(ctx context.Context, arg GetSessionPlayerParams) (SessionPlayer, error) {
	row := q.db.QueryRowContext(ctx, getSessionPlayer, arg.SessionID, arg.PlayerID)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.IsReady,
		&i.JoinedAt,
		&i.LastSeenAt,
		&i.LeftAt,
	)
	return i, err
}

const joinCodeExists = `-- name: JoinCodeExists :one
SELECT EXISTS(SELECT 1 FROM sessions WHERE join_code = ?) AS code_exists
`

// Cheap existence probe for a candidate join code so the generator can
// regenerate on collision before paying for the INSERT.
func (q *Queries) JoinCodeExists(ctx context.Context, joinCode string) (bool, error) {
	row := q.db.QueryRowContext(ctx, joinCodeExists, joinCode)
	var code_exists bool
	err := row.Scan(&code_exists)
	return code_exists, err
}

const listFinishedSessionPlaysForPlayer = `-- name: ListFinishedSessionPlaysForPlayer :many
SELECT
    s.quiz_id              AS quiz_id,
    CAST(q.title AS TEXT)  AS quiz_title,
    s.finished_at          AS finished_at
FROM sessions s
JOIN quizzes q ON q.id = s.quiz_id
WHERE s.phase = 'finished'
  AND s.finished_at = (
      SELECT MAX(s2.finished_at)
      FROM sessions s2
      JOIN session_players sp2 ON sp2.session_id = s2.id
      WHERE s2.quiz_id = s.quiz_id
        AND s2.phase = 'finished'
        AND sp2.player_id = ?1
  )
  AND EXISTS (
      SELECT 1 FROM session_players sp
      WHERE sp.session_id = s.id
        AND sp.player_id = ?1
  )
GROUP BY s.quiz_id
ORDER BY s.finished_at DESC, s.quiz_id DESC
LIMIT ?2
`

type ListFinishedSessionPlaysForPlayerParams struct {
	PlayerID int64
	RowLimit int64
}

type ListFinishedSessionPlaysForPlayerRow struct {
	QuizID     int64
	QuizTitle  string
	FinishedAt sql.NullTime
}

// Finished live-quiz plays for the given player, newest-first, one row per
// quiz. A play is a roster row in a finished session; collapsing to one row
// per quiz keeps the admin detail list to "quizzes this player has played"
// rather than every individual session. finished_at is the most recent
// finish time among the player's sessions of that quiz, read off the
// representative session row (not aggregated) so it stays a typed DATETIME.
// Joined to quizzes for the title so the detail view renders without a
// second round trip.
func (q *Queries) ListFinishedSessionPlaysForPlayer(ctx context.Context, arg ListFinishedSessionPlaysForPlayerParams) ([]ListFinishedSessionPlaysForPlayerRow, error) {
	rows, err := q.db.QueryContext(ctx, listFinishedSessionPlaysForPlayer, arg.PlayerID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFinishedSessionPlaysForPlayerRow
	for rows.Next() {
		var i ListFinishedSessionPlaysForPlayerRow
		if err := rows.Scan(&i.QuizID, &i.QuizTitle, &i.FinishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSessionIDs = `-- name: ListLiveSessionIDs :many
SELECT id
FROM sessions
WHERE phase != 'finished'
ORDER BY created_at, id
`

// Ids of every session not yet finished, in creation order. The runner scans
// these each beat to auto-start lobbies and advance in-flight games; finished
// sessions are skipped so the scan stays bounded to active rooms.
func (q *Queries) ListLiveSessionIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLiveSessionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionAnswersForQuestion = `-- name: ListSessionAnswersForQuestion :many
SELECT sa.player_id,
       sa.option_id,
       sa.answered_at,
       sa.score,
       o.is_correct
FROM session_answers sa
         JOIN options o ON o.id = sa.option_id
WHERE sa.session_id = ?
  AND sa.question_id = ?
ORDER BY sa.answered_at, sa.id
`

type ListSessionAnswersForQuestionParams struct {
	SessionID  string
	QuestionID int64
}

type ListSessionAnswersForQuestionRow struct {
	PlayerID   int64
	OptionID   int64
	AnsweredAt time.Time
	Score      sql.NullInt64
	IsCorrect  bool
}

// Every pick for the given session question in answered order, joined to the
// chosen option's correctness. Drives scoring at close and the answered-order
// view. is_correct is the option flag; the runner only surfaces it to clients
// in the reveal phase. Deliberately NOT filtered by session_players.left_at:
// this read also backs scoring at close (the runner scores every recorded
// pick), so a player who answered then left must still be scored, which keeps
// their contribution to the quiz leaderboard intact (MP-10 decision 3). The
// answered-order badges drop left players at the display layer instead, gated
// on the live roster the state read already carries.
func (q *Queries) ListSessionAnswersForQuestion(ctx context.Context, arg ListSessionAnswersForQuestionParams) ([]ListSessionAnswersForQuestionRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionAnswersForQuestion, arg.SessionID, arg.QuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionAnswersForQuestionRow
	for rows.Next() {
		var i ListSessionAnswersForQuestionRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.OptionID,
			&i.AnsweredAt,
			&i.Score,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionFinalStandings = `-- name: ListSessionFinalStandings :many
SELECT sp.player_id                              AS player_id,
       CAST(p.display_name AS TEXT)              AS display_name,
       CAST(COALESCE(SUM(sa.score), 0) AS INTEGER) AS total_score
FROM session_players sp
         JOIN players p ON p.id = sp.player_id
         LEFT JOIN session_answers sa
                   ON sa.session_id = sp.session_id AND sa.player_id = sp.player_id
WHERE sp.session_id = ?1
  AND (sp.left_at IS NULL
       OR EXISTS (SELECT 1 FROM session_answers sa2
                  WHERE sa2.session_id = sp.session_id AND sa2.player_id = sp.player_id))
GROUP BY sp.player_id, p.display_name
ORDER BY total_score DESC, p.display_name
`

type ListSessionFinalStandingsRow struct {
	PlayerID    int64
	DisplayName string
	TotalScore  int64
}

// Per-player final standings for a session: cumulative score across the whole
// session, anchored on the roster so non-answerers appear at 0. display_name is
// the player's CURRENT players.display_name (#716), joined live so a rename
// shows in the final standings. Same ordering as ListSessionStandings; used at
// the finished phase, where there is no "current round" to break out. A player
// belongs in the final standings if they are still present (left_at IS NULL) OR
// have actually played (recorded at least one session answer): the finished
// board is a stable record of everyone who played, so a player who answered and
// then closed their browser keeps their score across a TV refresh (#766).
// Someone who left during the lobby/intro without ever answering never played
// and so does not appear.
func (q *Queries) ListSessionFinalStandings(ctx context.Context, sessionID string) ([]ListSessionFinalStandingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionFinalStandings, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionFinalStandingsRow
	for rows.Next() {
		var i ListSessionFinalStandingsRow
		if err := rows.Scan(&i.PlayerID, &i.DisplayName, &i.TotalScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionPlayers = `-- name: ListSessionPlayers :many
SELECT sp.id,
       sp.session_id,
       sp.player_id,
       CAST(p.display_name AS TEXT) AS display_name,
       sp.is_ready,
       sp.joined_at,
       sp.last_seen_at,
       sp.left_at
FROM session_players sp
         JOIN players p ON p.id = sp.player_id
WHERE sp.session_id = ?
  AND sp.left_at IS NULL
ORDER BY sp.joined_at, sp.id
`

type ListSessionPlayersRow struct {
	ID          int64
	SessionID   string
	PlayerID    int64
	DisplayName string
	IsReady     int64
	JoinedAt    time.Time
	LastSeenAt  time.Time
	LeftAt      sql.NullTime
}

// The lobby roster in join order. Excludes players who have left (left_at
// set, MP-10) so the lobby shows the current room. display_name is the
// player's CURRENT players.display_name (#716), joined live so a rename shows
// everywhere rather than a per-session snapshot.
func (q *Queries) ListSessionPlayers(ctx context.Context, sessionID string) ([]ListSessionPlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionPlayers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionPlayersRow
	for rows.Next() {
		var i ListSessionPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PlayerID,
			&i.DisplayName,
			&i.IsReady,
			&i.JoinedAt,
			&i.LastSeenAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionStandings = `-- name: ListSessionStandings :many
SELECT sp.player_id                 AS player_id,
       CAST(p.display_name AS TEXT) AS display_name,
       CAST(COALESCE(SUM(CASE WHEN q.round_id = ?1 THEN sa.score END), 0) AS INTEGER) AS round_score,
       CAST(COALESCE(SUM(sa.score), 0) AS INTEGER)                                                      AS total_score
FROM session_players sp
         JOIN players p ON p.id = sp.player_id
         LEFT JOIN session_answers sa
                   ON sa.session_id = sp.session_id AND sa.player_id = sp.player_id
         LEFT JOIN questions q ON q.id = sa.question_id
WHERE sp.session_id = ?2
  AND (sp.left_at IS NULL
       OR EXISTS (SELECT 1 FROM session_answers sa2
                  WHERE sa2.session_id = sp.session_id AND sa2.player_id = sp.player_id))
GROUP BY sp.player_id, p.display_name
ORDER BY total_score DESC, p.display_name
`

type ListSessionStandingsParams struct {
	RoundID   int64
	SessionID string
}

type ListSessionStandingsRow struct {
	PlayerID    int64
	DisplayName string
	RoundScore  int64
	TotalScore  int64
}

// Per-player standings for a session: the score the player earned in the given
// round (round_score) and their cumulative score across the whole session
// (total_score). Anchored on the roster (LEFT JOIN to scored answers) so a
// player who never answered still appears at 0, which the bar graph needs. The
// round is selected by questions.round_id; coalesce turns "no scored answer" /
// "score still NULL" into 0. display_name is the player's CURRENT
// players.display_name (#716), joined live so a rename shows in the standings.
// Ordered by total_score desc, then display_name so ranking is stable across
// reads. A player belongs in the standings if they are still present
// (left_at IS NULL) OR have actually played (recorded at least one session
// answer): the standings are a stable record of everyone who played, so a player
// who answered and then closed their browser keeps their score on the board
// across a TV refresh (#766). Someone who left during the lobby/intro without
// ever answering never played and so does not appear.
func (q *Queries) ListSessionStandings(ctx context.Context, arg ListSessionStandingsParams) ([]ListSessionStandingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionStandings, arg.RoundID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionStandingsRow
	for rows.Next() {
		var i ListSessionStandingsRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.DisplayName,
			&i.RoundScore,
			&i.TotalScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionPlayerLeft = `-- name: MarkSessionPlayerLeft :execresult
UPDATE session_players
SET left_at = CURRENT_TIMESTAMP
WHERE player_id = ?1
  AND left_at IS NULL
  AND session_id = (SELECT id FROM sessions WHERE join_code = ?2)
`

type MarkSessionPlayerLeftParams struct {
	PlayerID int64
	JoinCode string
}

// Marks the participant as having left the session identified by join code,
// stamping left_at so the live presence reads (roster, answered-order badges)
// drop them immediately. The standings deliberately keep a left player who has
// already answered, so their score stays on the board across a TV refresh
// (#766). Scoped to left_at IS NULL so a second leave is a no-op rather than
// re-stamping the timestamp; the execresult lets the store map zero rows
// affected to "not an active participant". Keyed on join code so the handler
// need only carry the code it already gates on.
func (q *Queries) MarkSessionPlayerLeft(ctx context.Context, arg MarkSessionPlayerLeftParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markSessionPlayerLeft, arg.PlayerID, arg.JoinCode)
}

const playerFinishedSessionForQuiz = `-- name: PlayerFinishedSessionForQuiz :one
SELECT EXISTS (
    SELECT 1
    FROM session_players sp
    JOIN sessions s ON s.id = sp.session_id
    WHERE sp.player_id = ?1
      AND s.quiz_id = ?2
      AND s.phase = 'finished'
) AS has_finished
`

type PlayerFinishedSessionForQuizParams struct {
	PlayerID int64
	QuizID   int64
}

// Reports whether the player has a roster row in a finished session of the
// given quiz. Backs the replay gate: a live quiz may be played once, so a
// player who already sat through a finished session of it is blocked from
// joining a new one until an admin resets their participation.
func (q *Queries) PlayerFinishedSessionForQuiz(ctx context.Context, arg PlayerFinishedSessionForQuizParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, playerFinishedSessionForQuiz, arg.PlayerID, arg.QuizID)
	var has_finished bool
	err := row.Scan(&has_finished)
	return has_finished, err
}

const refreshSessionPlayerLastSeenAt = `-- name: RefreshSessionPlayerLastSeenAt :exec
UPDATE session_players
SET last_seen_at = CAST(?1 AS TEXT)
WHERE session_id = ?2
  AND player_id = ?3
`

type RefreshSessionPlayerLastSeenAtParams struct {
	Seen      string
	SessionID string
	PlayerID  int64
}

// Stamps a participant's last_seen_at to a bound timestamp, the answer-as-
// liveness refresh: recording a pick proves the player is present, so the
// answer write bumps last_seen_at in the same transaction (see #712). seen is
// bound as a CURRENT_TIMESTAMP-format text string ('YYYY-MM-DD HH:MM:SS') via
// the CAST, so the value lands in the exact encoding the active-window
// comparison in CountActivePlayersForSession reads (a bound Go time.Time would
// arrive in a different format and the cross-format string compare would
// silently lie). Bound (not CURRENT_TIMESTAMP) so a fake-clock test stays
// deterministic.
func (q *Queries) RefreshSessionPlayerLastSeenAt(ctx context.Context, arg RefreshSessionPlayerLastSeenAtParams) error {
	_, err := q.db.ExecContext(ctx, refreshSessionPlayerLastSeenAt, arg.Seen, arg.SessionID, arg.PlayerID)
	return err
}

const sessionHasPlayer = `-- name: SessionHasPlayer :one
SELECT EXISTS (
    SELECT 1
    FROM session_players sp
    JOIN sessions s ON s.id = sp.session_id
    WHERE s.join_code = ?1
      AND sp.player_id = ?2
) AS has_player
`

type SessionHasPlayerParams struct {
	JoinCode string
	PlayerID int64
}

// Reports whether the player has EVER held a roster row in the session
// identified by join code, regardless of left_at. Backs the reconnect/resume
// gate in Service.Join: a prior participant - including one whose row is marked
// left_at (e.g. a beforeunload leave beacon fired on a reload) - may re-Join
// past the lobby, which revives their row. Deliberately NOT filtered by left_at,
// unlike the live roster read, so a reloading player who just left can still
// resume; a player who never joined matches nothing and is rejected as a late
// joiner.
func (q *Queries) SessionHasPlayer(ctx context.Context, arg SessionHasPlayerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, sessionHasPlayer, arg.JoinCode, arg.PlayerID)
	var has_player bool
	err := row.Scan(&has_player)
	return has_player, err
}

const setSessionAnswerScore = `-- name: SetSessionAnswerScore :exec
UPDATE session_answers
SET score = ?
WHERE session_id = ?
  AND question_id = ?
  AND player_id = ?
`

type SetSessionAnswerScoreParams struct {
	Score      sql.NullInt64
	SessionID  string
	QuestionID int64
	PlayerID   int64
}

// Writes the computed score for one pick at question close.
func (q *Queries) SetSessionAnswerScore(ctx context.Context, arg SetSessionAnswerScoreParams) error {
	_, err := q.db.ExecContext(ctx, setSessionAnswerScore,
		arg.Score,
		arg.SessionID,
		arg.QuestionID,
		arg.PlayerID,
	)
	return err
}

const setSessionFinished = `-- name: SetSessionFinished :exec
UPDATE sessions
SET phase               = 'finished',
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL,
    finished_at         = CURRENT_TIMESTAMP
WHERE id = ?
`

// Ends the session: marks it finished and clears the per-question runner
// columns.
func (q *Queries) SetSessionFinished(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setSessionFinished, id)
	return err
}

const setSessionPlayerReady = `-- name: SetSessionPlayerReady :execresult
UPDATE session_players
SET is_ready     = ?,
    last_seen_at = CURRENT_TIMESTAMP
WHERE session_id = ?
  AND player_id = ?
`

type SetSessionPlayerReadyParams struct {
	IsReady   int64
	SessionID string
	PlayerID  int64
}

// Toggles a participant's ready flag and refreshes last_seen_at. Scoped to
// (session_id, player_id) so it only ever touches the caller's own roster
// row. The execresult lets the store map zero rows affected to "not a
// participant".
func (q *Queries) SetSessionPlayerReady(ctx context.Context, arg SetSessionPlayerReadyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setSessionPlayerReady, arg.IsReady, arg.SessionID, arg.PlayerID)
}

const setSessionQuestion = `-- name: SetSessionQuestion :exec
UPDATE sessions
SET phase               = 'question',
    current_round_id    = ?,
    current_question_id = ?,
    question_started_at = ?,
    question_expires_at = ?
WHERE id = ?
`

type SetSessionQuestionParams struct {
	CurrentRoundID    sql.NullInt64
	CurrentQuestionID sql.NullInt64
	QuestionStartedAt sql.NullTime
	QuestionExpiresAt sql.NullTime
	ID                string
}

// Issues a question: records the current round + question and the server
// answer window (started_at -> expires_at), and moves into the question phase.
func (q *Queries) SetSessionQuestion(ctx context.Context, arg SetSessionQuestionParams) error {
	_, err := q.db.ExecContext(ctx, setSessionQuestion,
		arg.CurrentRoundID,
		arg.CurrentQuestionID,
		arg.QuestionStartedAt,
		arg.QuestionExpiresAt,
		arg.ID,
	)
	return err
}

const setSessionReveal = `-- name: SetSessionReveal :exec
UPDATE sessions
SET phase = 'reveal'
WHERE id = ?
`

// Moves the session into the reveal phase, leaving the current question and
// its window in place so a reader still sees which question is being revealed.
func (q *Queries) SetSessionReveal(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setSessionReveal, id)
	return err
}

const setSessionRoundIntro = `-- name: SetSessionRoundIntro :exec
UPDATE sessions
SET phase               = 'round_intro',
    current_round_id    = ?,
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL
WHERE id = ?
`

type SetSessionRoundIntroParams struct {
	CurrentRoundID sql.NullInt64
	ID             string
}

// Moves the session into the round_intro phase for the given round and clears
// the per-question runner columns (the intro screen runs before any question
// is issued).
func (q *Queries) SetSessionRoundIntro(ctx context.Context, arg SetSessionRoundIntroParams) error {
	_, err := q.db.ExecContext(ctx, setSessionRoundIntro, arg.CurrentRoundID, arg.ID)
	return err
}

const setSessionRoundResults = `-- name: SetSessionRoundResults :exec
UPDATE sessions
SET phase               = 'round_results',
    current_question_id = NULL,
    question_started_at = NULL,
    question_expires_at = NULL
WHERE id = ?
`

// Moves the session into the round_results phase shown after the last question
// of a round (before the next round's intro). current_round_id stays put so the
// state read knows which round just finished; the per-question runner columns
// are cleared because no question is live in this phase.
func (q *Queries) SetSessionRoundResults(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setSessionRoundResults, id)
	return err
}

const startSession = `-- name: StartSession :execresult
UPDATE sessions
SET started_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND started_at IS NULL
`

// Stamps started_at and moves the session out of the lobby. Scoped to a
// session still in the lobby so a re-issued start (host double-click, or the
// auto-start racing the host) is a no-op rather than resetting the clock.
func (q *Queries) StartSession(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, startSession, id)
}

const touchSessionHostLastSeen = `-- name: TouchSessionHostLastSeen :execresult
UPDATE sessions
SET host_last_seen_at = CURRENT_TIMESTAMP
WHERE join_code = ?1
`

// Refreshes the host's host_last_seen_at, the host-presence heartbeat. The SSE
// events handler calls it when the host's connection opens and periodically
// while it is held, so a host who disconnects mid-game goes stale and the
// runner's abandon sweep finishes the lingering session (MP-10). Keyed on
// join_code so the handler need only carry the code it already gates on. The
// execresult lets the store tell a missed update (unknown code) from a hit.
func (q *Queries) TouchSessionHostLastSeen(ctx context.Context, joinCode string) (sql.Result, error) {
	return q.db.ExecContext(ctx, touchSessionHostLastSeen, joinCode)
}

const touchSessionPlayerLastSeen = `-- name: TouchSessionPlayerLastSeen :execresult
UPDATE session_players
SET last_seen_at = CURRENT_TIMESTAMP
WHERE player_id = ?1
  AND session_id = (SELECT id FROM sessions WHERE join_code = ?2)
`

type TouchSessionPlayerLastSeenParams struct {
	PlayerID int64
	JoinCode string
}

// Refreshes a participant's last_seen_at, the active-player heartbeat. The SSE
// events handler calls it when the connection opens and periodically while it
// is held, so a dropped player's last_seen_at goes stale and the runner stops
// counting them as active (MP-10). Keyed on (join_code, player_id) so the
// handler need only carry the code it already gates on.
func (q *Queries) TouchSessionPlayerLastSeen(ctx context.Context, arg TouchSessionPlayerLastSeenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, touchSessionPlayerLastSeen, arg.PlayerID, arg.JoinCode)
}

const upsertSessionAnswer = `-- name: UpsertSessionAnswer :exec
INSERT INTO session_answers (session_id, question_id, player_id, option_id, answered_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (session_id, question_id, player_id)
    DO UPDATE SET option_id   = excluded.option_id,
                  answered_at = excluded.answered_at
`

type UpsertSessionAnswerParams struct {
	SessionID  string
	QuestionID int64
	PlayerID   int64
	OptionID   int64
	AnsweredAt time.Time
}

// Records a player's pick for the current session question. answered_at is the
// server timestamp the pick landed. Idempotent on (session_id, question_id,
// player_id): a re-submit overwrites the option and timestamp rather than
// duplicating, so a double-tap before close is the last pick rather than an
// error. score stays NULL until the question closes.
func (q *Queries) UpsertSessionAnswer(ctx context.Context, arg UpsertSessionAnswerParams) error {
	_, err := q.db.ExecContext(ctx, upsertSessionAnswer,
		arg.SessionID,
		arg.QuestionID,
		arg.PlayerID,
		arg.OptionID,
		arg.AnsweredAt,
	)
	return err
}

const upsertSessionPlayer = `-- name: UpsertSessionPlayer :one
INSERT INTO session_players (session_id, player_id)
VALUES (?, ?)
ON CONFLICT (session_id, player_id)
    DO UPDATE SET left_at      = NULL,
                  last_seen_at = CURRENT_TIMESTAMP
RETURNING id, session_id, player_id, is_ready, joined_at, last_seen_at, left_at
`

type UpsertSessionPlayerParams struct {
	SessionID string
	PlayerID  int64
}

// Adds a player to a session's roster, or revives an existing row on re-join
// (clearing left_at and refreshing last_seen_at). The display name is no
// longer stored per session (#716): the roster reads join players and select
// the current players.display_name, so a rename propagates everywhere. The
// (session_id, player_id) UNIQUE makes the upsert idempotent for the same
// player.
func (q *Queries) UpsertSessionPlayer(ctx context.Context, arg UpsertSessionPlayerParams) (SessionPlayer, error) {
	row := q.db.QueryRowContext(ctx, upsertSessionPlayer, arg.SessionID, arg.PlayerID)
	var i SessionPlayer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.IsReady,
		&i.JoinedAt,
		&i.LastSeenAt,
		&i.LeftAt,
	)
	return i, err
}
